let livro_cs3 ={

  /* metadados 2 */
  metadados:{
	  i18n:false,
	  formularioRegistro_campos_formatosValidos:['texto','numero','data','url','lista','nome','usuario','senha','usuarioAcessivel','senhaAcessivel'],
	  infografico_estilosValidos:['basicoPaisagem','basicoRetrato','explosaoPaisagem','circuitoPaisagem','cobraPaisagem','cobraPaisagem2', 'cobraRetrato','gPaisagem'] 
  },

  versao:'0.1.00',
  nomeFantasia: '',
  nomeTecnico:'CS3',
  resumo:'John von Neumann foi um matemático húngaro, considerado um dos mais importantes matemáticos do século XX que fez parte do time de construtores do ENIAC.',
  isbn:'',
  autores:[],
  editor:'',
  local:'',
  ano:'',

  versaoAdaptacao:'',
  nomeAdaptacaoo: '',
  autoresAdaptacao:[],
  local:'',
  escola:'',
  ano:'',
  url:'',
  codigoCid11:'', /* opc */
  descritivoPerfilAluno:'',
  resumoAdaptacao:'',


  capa:{
		urlImagemCapa:'',
		urlImagemSegundaCapa: '',
  },

  visaogeral:{
	  infografico:{
		  titulo:'Resumo do Módulo CS3',
		  /* idem licoes */
	  }},
  
   /* conteudo */
  unidade1:{
	  titulo:'',
	  descricao:'',
	  licao1:{
		  id:'CSXAULA01CODE',
		  /** padroesCurriculares: 
		  titulo:'Lição 01. Eletricidade e Circuitos em Papel',**/
      infografico:{titulo:'Lição 01. Explorando a Eletricidade e Seus Segredos',
      tituloSimplificado:'Eletricidade',
      estiloPadrao:'basicoPaisagem',
      /** urlVideo:'',
      urlPodcast:'', **/
      cenas:[
        {ordem:1,
        predecessor:0,
        texto:'A <b>eletricidade</b> é um tipo de energia que chega em nossas casas por meio das chamadas <b>redes elétricas</b>, como podemos observar pelos grandes cabos e postes que vemos nas ruas.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExplElet/img_1.png',
        promptImagem:'Uma imagem em close de um fio de uma rede elétrica irradiando luz para representar a transmissão da energia elétrica entre postes de fiação em uma cidade metropolitana em um dia nublado, photo, poster', 
        imagemFonte:'ideogram',
        textoDescritivoImagem:'',},

        {ordem:2,
        predecessor:1,
        texto:'Em casa, usamos eletricidade para esquentar água, esfriar alimentos na geladeira e ligar aparelhos como lâmpadas, TVs e, é claro, os computadores e até robôs.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExplElet/img_2.png',
        promptImagem:'Uma imagem divida em quatro, cada uma com close em: um microondas aquecendo um alimento sobre um armário de cozinha; uma geladeira ligada na tomada sobre o piso da cozinha; uma televisão presa em um painel de parede, exibindo um filme; um notebook sobre uma mesa de escritório, exibindo uma página da WEB, photo, poster', 
        imagemFonte:'ideogram',
        textoDescritivoImagem:'',},

        {ordem:3,
        predecessor:2,
        texto:'Computadores portáteis, robôs e outros aparelhos chamados <b>eletrônicos</b> podem funcionar sem estarem conectados à tomada, desde que possuam baterias.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExplElet/img_3.png',
        promptImagem:'Uma imagem de vista superior sobre uma bancada, sobre a qual estão diversos tipos de aparelhos eletrônicos, como televisores, smatphones, notebooks, barbeadores, teclado musical, entre outros, photo, poster', 
        imagemFonte:'ideogram',
        textoDescritivoImagem:'',},

        {ordem:4,
        predecessor:3,
        texto:'Já as <b>baterias</b> são componentes que armazenam energia por um tempo. Quando a energia acaba, recarregamos as baterias nas tomadas que trazem energia da rede elétrica.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExplElet/img_4.png',
        promptImagem:'Uma imagem de um celular em uma mesa sendo recarregado enquanto o celular está ligando em uma tomada com uma bateria de celular sobressalente ao seu lado, photo, poster', 
        imagemFonte:'ideogram',
        textoDescritivoImagem:'',},

        {ordem:5,
        predecessor:4,
        texto:'Existem muitos tipos de aparelhos eletrônicos, para diferentes finalidades. Neste curso, mais do que usar, vamos criar dispositivos eletrônicos variados.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExplElet/img_5.png',
        promptImagem:'Uma imagem de um prateleira de metal com todo tipo de aparelho eletrônico, para as mais diversas finalidades, poster, photo', 
        imagemFonte:'ideogram',
        textoDescritivoImagem:'',},
                       
        {ordem:6,
        predecessor:5,
        texto:'Todo aparelho eletrônico é formado por <b>componentes</b>. Vamos aprender quais são os principais componentes, antes de criar nossos próprios inventos.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExplElet/img_6.png',
        promptImagem:'imagem em close de um computador aberto sobre uma bancada, exibindo seus componentes eletrônicos, photo', 
        imagemFonte:'ideogram',
        textoDescritivoImagem:'',},

        {ordem:7,
        predecessor:6,
        texto:'Um primeiro tipo de componente é chamado de <b>gerador</b>. Ele fornece energia para os demais componentes.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExplElet/img_7.png',
        promptImagem:'Imagem em close de uma bateria de 9 volts, photo', 
        imagemFonte:'ideogram',
        textoDescritivoImagem:'',},

        {ordem:8,
        predecessor:7,
        texto:'Há também os <b>controladores</b>, componentes que as pessoas usam para controlar os aparelhos.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExplElet/img_8.png',
        promptImagem:'Imagem de uma caixa de som com close no botão de tunner do volume, photo', 
        imagemFonte:'ideogram',
        textoDescritivoImagem:'',},

        {ordem:9,
        predecessor:8,
        texto:'Já os componentes <b>condutores</b> servem para transportar a energia elétrica entre os componentes.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExplElet/img_9.png',
        promptImagem:'Imagem em close de um cabo condutor de corrente elétrica sobre uma mesa de madeira, o fio está cortando na ponta, de onde saem vários fios desencapados de cobre, photo, poster', 
        imagemFonte:'ideogram',
        textoDescritivoImagem:'',},

        {ordem:10,
        predecessor:9,
        texto:'Por fim, os componentes <b>atuadores</b> são aqueles que executam a ação principal do aparelho, seja acender uma luz, fazer algum movimento ou outra qualquer.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExplElet/img_10.png',
        promptImagem:'imagem em close de uma pilha de 3Volts presa em soquete ligado a dois fios de cobre para alimentar um led de, photo', 
        imagemFonte:'ideogram',
        textoDescritivoImagem:'',},

        {ordem:11,
        predecessor:10,
        texto:'Juntando esses quatro tipos de componentes, podemos criar diferentes inventos para explorar os mistérios da eletricidade.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpressoRecriado:'Juntando esses quatro tipos de componentes, podemos criar diferentes inventos para explorar os mistérios da eletricidade. A diversão e o aprendizado estão prestes a começar!',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExplElet/img_11.png',
        promptImagem:'Imagem de um notebook aberto, em manutenção, mostrando a bateria, a placa mãe, e a casing, photo', 
        imagemFonte:'ideogram',
        textoDescritivoImagem:'',},

        {ordem:12,
        predecessor:11,
        texto:'A diversão e o aprendizado estão prestes a começar! Prontos para desvendar os segredos da eletricidade?',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:0,
        imagemImpresso:0,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExplElet/img_12.png',
        promptImagem:'Imagem de uma criança montando um circuito em papel, usando uma fita condutora de cobre, uma bateria de lítio 3 volts e um LED (ight-emitting diode) verde, com expressão de entusiasmo, photo', 
        imagemFonte:'ideogram',
        textoDescritivoImagem:'',},
      
       ]}},


    licao2:{},

    licao3:{
      id:'CSXAULA03CODE',
      /** padroesCurriculares: 
       titulo:'Lição 03. Dispositivos Computacionais.',**/
       infografico:{titulo:'Lição 03. Computador e Dispositivos Computacionais',
       tituloSimplificado:'O Computador',
       estiloPadrao:'basicoPaisagem',
       /** urlVideo:'',
       urlPodcast:'', **/
       cenas:[
         {ordem:1,
         predecessor:0,
         texto:'Hoje, nós vamos descobrir como é divertido programar computadores.', //Estes serão seus primeiros passos na ciência da computação.',
         urlAudioTexto:'',
         textoSimplificado:'',
         textoImpresso:1,
         imagemImpresso:1,
         urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Comp/img_1.png',
         promptImagem:'arte digital de uma adolescente gargalhando de felicidade, com olhos arregalados de euforia, sentada em sua mesa em frente ao laptop com dos dois braços levantados, como se estivesse comemorando, em um pano de fundo com cores brilhantes e vibrantes, 3d render', 
         imagemFonte:'ideogram',
         textoDescritivoImagem:'',},

         {ordem:2,
         predecessor:1,
         texto:'Você já brincou com um computador ou celular? Eles são aparelhos eletrônicos e possuem diversas partes.',
         urlAudioTexto:'',
         textoSimplificado:'',
         textoImpresso:1,
         imagemImpresso:1,
         urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Comp/img_2.png',
         promptImagem:'Arte digital de dois adolescentes profundamente envolvido em um jogos de computador, em que um deles está jogando no computador e o outro está jogando em um smartphone de última geração, em um pano de fundo com cores brilhantes e vibrantes, 3d render', 
         imagemFonte:'ideogram',
         textoDescritivoImagem:'',},

         {ordem:3,
         predecessor:2,
         texto:'O computador de mesa, por exemplo, tem quatro partes: a torre, o teclado, o monitor e o mouse.',
         urlAudioTexto:'',
         textoSimplificado:'',
         textoImpresso:1,
         imagemImpresso:1,
         urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Comp/img_3.png',
         promptImagem:'Arte digital de um computador desktop composto por uma CPU, um monitor ultrafino widescreen , um mouse e um teclado, em um pano de fundo sem nenhuma elemento adicional com um degrade de cores brilhantes e vibrantes, 3d render', 
         imagemFonte:'ideogram',
         textoDescritivoImagem:'',},

         {ordem:4,
         predecessor:3,
         texto:`Na <b>torre</b> existem componentes como as memórias, onde o computador armazena dados. E o processor, que funciona como o "cérebro do computador".`,
         urlAudioTexto:'',
         textoSimplificado:'',
         textoImpresso:1,
         imagemImpresso:1,
         urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Comp/img_4.png',
         promptImagem:'Arte digital do gabinete de um computador desktop, em um pano de fundo sem nenhum elemento adicional com um degrade de cores brilhantes e vibrantes, 3d render', 
         imagemFonte:'ideogram',
         textoDescritivoImagem:'',},

         {ordem:5,
         predecessor:4,
         texto:'Com o <b>teclado</b> e o <b>mouse</b>, nós conseguimos digitar, mover e clicar em objetos exibidos na tela, chamada de <b>monitor</b>.',
         urlAudioTexto:'',
         textoSimplificado:'',
         textoImpresso:1,
         imagemImpresso:1,
         urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Comp/img_5.png',
         promptImagem:'Arte digital do gabinete de um computador desktop, sem teclado, sem mouse e sem monitor, em um pano de fundo sem nenhum elemento adicional com um degrade de cores brilhantes e vibrantes, 3d render', 
         imagemFonte:'ideogram',
         textoDescritivoImagem:'',},

         {ordem:6,
         predecessor:5,
         texto:'Podemos também conectar outros dispositivos ao computador, como caixas de som ou impressoras.',
         urlAudioTexto:'',
         textoSimplificado:'',
         textoImpresso:1,
         imagemImpresso:1,
         urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Comp/img_6.png',
         promptImagem:'Arte digital de um computador desktop composto por uma CPU, um monitor ultrafino widescreen , um mouse e um teclado, uma caixa de som e uma impressora em um pano de fundo sem nenhuma elemento adicional com um degrade de cores brilhantes e vibrantes, 3d render', 
         imagemFonte:'ideogram',
         textoDescritivoImagem:'',},

         {ordem:7,
         predecessor:6,
         texto:'Celulares e tablets também são computadores, embora pequenos, para caberem na palma das nossas mãos.',
         urlAudioTexto:'',
         textoSimplificado:'',
         textoImpresso:1,
         imagemImpresso:1,
         urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Comp/img_7.png',
         promptImagem:'Arte digital em close de um tablet e um smartphone, um deles sendo usado por uma pessoa negra e o outro por uma pessoa branca, com mãos perfeitas, sem deformação, em um pano de fundo com cores brilhantes e vibrantes, 3d render', 
         imagemFonte:'ideogram',
         textoDescritivoImagem:'',},

         {ordem:8,
         predecessor:7,
         texto:'Mas existem computadores ainda menores, embutidos dentro de carros, TVs e até mesmo brinquedos. Eles tornam estes aparelhos mais inteligentes e capazes de nos ajudar no dia a dia.',
         urlAudioTexto:'',
         textoSimplificado:'',
         textoImpresso:1,
         imagemImpresso:1,
         urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Comp/img_8.png',
         promptImagem:'Arte digital em mosaico retangular de diversos dispositivos inteligentes que possuem um computador embutido, como um carro de última geração, uma TV, um assistente de voz, uma geladeira e um brinquedo robótico, em um pano de fundo com cores brilhantes e vibrantes', 
         imagemFonte:'ideogram',
         textoDescritivoImagem:'',},

         {ordem:9,
         predecessor:8,
         texto:'Mas, afinal, o que é um computador? É uma máquina que pode ser programada para nos ajudar nas mais variadas tarefas, seja no trabalho, na escola ou em momentos de lazer.',
         urlAudioTexto:'',
         textoSimplificado:'',
         textoImpresso:1,
         imagemImpresso:1,
         urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Comp/img_9.png',
         promptImagem:'Arte digital em perspectiva isométrica, mostrando cada parte de um computador desktop isoladamente, exibindo Torre CPU, monitor, mouse, teclado, impressora, scanner, caixa de som, pen drive, hd externo, em um pano de fundo sem nenhuma elemento adicional com um degrade de cores brilhantes e vibrantes, 3d render', 
         imagemFonte:'ideogram',
         textoDescritivoImagem:'Arte digital de um computador com símbolos representando vários usos fluindo da tela, como símbolos de um controlador de videogame, um badalo de filme, uma câmera, uma nota musical, um livro, um carro, um robô, em um pano de fundo sem nenhuma elemento adicional com um degrade de cores brilhantes e vibrantes, 3d render',},

         {ordem:10,
         predecessor:9,
         texto:'Neste curso, vamos aprender a criar jogos, inventos eletrônicos, a programar robôs e montar inventos. Tudo isso é <b>ciência da computação</b>!',
         urlAudioTexto:'',
         textoSimplificado:'',
         textoImpresso:1,
         imagemImpresso:1,
         urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Comp/img_10.png',
         promptImagem:'', 
         imagemFonte:'ideogram',
         textoDescritivoImagem:'',},
       
        ]}},

    licao4:{
      id:'CSXAULA04CODE',
      /** padroesCurriculares: 
      titulo:'Lição 04. Algoritmo++',**/
		  infografico:{titulo:'Lição 04. Algoritmos no Nosso Dia a Dia',
        tituloSimplificado:'Algoritmos',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Um <b>algoritmo</b> é como uma receita que explica a uma pessoa ou máquina, passo a passo, como realizar uma tarefa de modo correto.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Alg/img_1.png',
          promptImagem:'Pintura digital de uma mulher e um robô seguindo uma trilha no chão feita pelas peças de um quebra cabeça até chegarem ao quebra-cabeça montado à frente deles, 3d render, typography, painting', 
          imagemFonte:'ideogram',
          textoDescritivoImagem:'r',},

          {ordem:2,
          predecessor:1,
          texto:'Algumas vezes, os algoritmos são representados por figuras ou símbolos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Alg/img_2.png',
          promptImagem:'Pintura digital de um painel dividido em 9 quadrados, cada um representando um passo de uma atividade de ginástica, com a mesma pessoa em poses diferentes, ensinando como fazer o exercícioCrie um algoritmo pictográfico formado por 9 quadrados, onde cada quadrado está ilustrado exatamente com a mesma pessoa, usando a mesma roupa, porém em poses diferentes entre si. As poses devem representar os passos sequenciais de uma atividade aeróbica específica, como uma série de exercícios, 3d render, portrait photography', 
          imagemFonte:'ideogram',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Outras vezes, podemos chamá-los de <b>diagramas</b>, que são desenhos com formas ligadas por linhas, onde cada forma representa um passo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Alg/img_3.jpg',
          promptImagem:'imagem vibrante e alegre do diagrama de um algorimo', 
          imagemFonte:'leonardo',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Algoritmos podem ser escritos como uma lista numerada de passos para realizar uma tarefa simples.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Alg/img_4.jpg',
          promptImagem:'imagem vibrante e alegre dos passos para se fazer um origami de coração', 
          imagemFonte:'leonardo',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Alguns algoritmos são muito grandes e complicados, como aqueles que ajudam astronautas a resolver problemas no espaço.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Alg/img_5.jpg',
          promptImagem:`Create an ultra-realistic 3D image of two astronauts inside the International Space Station orbiting Earth, holding papers with troubleshooting algorithms to perform a maintenance procedure on the space station. In the background, depict space with stars, Earth, and the Moon. Ensure the astronauts are depicted in accurate spacesuits, with intricate details of the space station's exterior. Make the Earth and the Moon visually prominent with realistic textures and colors. The astronauts should be depicted floating in space, with one upside down and the other lying in the empty space with legs up, in a typical skydiver position. Both should be actively involved in the maintenance procedure, with one astronaut holding papers while the other examines the equipment.`, 
          imagemFonte:'leonardo',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'No mundo computacional, os chamados <b>programas de computador</b> também são algoritmos, escritos em uma linguagem que o computador entende.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Alg/img_6.jpg',
          promptImagem:`Create an ultra-realistic digital image of a programmer's workspace. In the scene, include a desktop with a monitor displaying programming code. The lines of text should represent the code, with specific elements such as loops or functions highlighted to indicate the program's structure. Additionally, include a programmer sitting in front of the desktop, typing on the keyboard. Ensure to realistically detail the reflection of the monitor on the programmer's glasses and face, as well as the body movements while typing, such as leaning slightly forward and positioning the hands on the keyboard accurately. Make sure the programmer's body shape is perfect, hyper-realistic, and that the keyboard has no defects or deformed keys.`, 
          imagemFonte:'leonardo',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Um bom algoritmo é importante para que uma tarefa seja realizada de modo perfeito, seja por uma pessoa ou máquina.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Alg/img_7.png',
          promptImagem:'Pintura digital de uma mulher segurando um papel com uma sequência de instruções e um robô com um painel em seu peito, escrito um código de programação, em que cada um segue as suas instruções para montar um outro robô, painting, 3d render', 
          imagemFonte:'ideogram',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Por isso, neste curso, vamos aprender algoritmos na prática, colocando a "mão na massa"!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/Alg/img_8.png',
          promptImagem:'Pintura digital de um adolescente muito animado enquanto programa um notebook em que sua tela está exibindo um codigo de programaçao, painting, 3d render', 
          imagemFonte:'ideogram',
          textoDescritivoImagem:'',},

      ]}},

    licao5:{
      id:'CSXAULA05CODE',
      /** padroesCurriculares: 
      titulo:'Lição 05. Robótica.',**/
      infografico:{titulo:'Lição 05. Robótica com Robôs de Duas Rodas',
      tituloSimplificado:'Robô de Duas Rodas',
      estiloPadrao:'basicoPaisagem',
      /** urlVideo:'',
      urlPodcast:'', **/
      cenas:[

        {ordem:1,
        predecessor:0,
        texto:'Um <b>robô</b> é uma máquina programável que executa tarefas automaticamente.', 
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/RoboDuRod/img_1.jpg',
        promptImagem:'Crie uma imagem 3D altamente realista de um robô industrial utilizado em uma montadora de automóveis. O robô deve ser projetado para realizar tarefas complexas de montagem na linha de produção, como soldagem, fixação de peças e pintura. Certifique-se de que o robô tenha um design robusto, com braços articulados e múltiplas ferramentas especializadas. Detalhe cada componente do robô com precisão, incluindo sensores, câmeras e outros dispositivos de controle. Garanta que a iluminação da cena destaque as características do robô e seu ambiente de trabalho na linha de produção automotiva.', 
        imagemFonte:'leonardo',
        textoDescritivoImagem:'',},

        {ordem:2,
        predecessor:1,
        texto:'Nós já vimos robôs em filmes e jogos... Eles podem ter pernas, rodas ou parecer com humanos. Mas vocês sabem como eles surgiram?',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/RoboDuRod/img_2.jpg',
        promptImagem:'Desenho tres robos ultrarrealistas. O primeiro deles é um rover de exploração espacial, com painel solar, movido a quatro rodas. O segundo é um robo com quatro patas, feito de metal, para ser um brinquedo em formato de um pet dog robótico. O terceiro com um formato humanoide, semelhante à personagem Alita, mas de cor vermelha e com fisionomia menos real, pois seu rosto é feito de borracha, não sendo capaz de expressar totalmente as fisionomias humnas. Acrescente cada um dos minimos detalhes de cada robô, baseando-se em robos reais, que estao sendo produzidos ou desenvolvidos nos dias atuais', 
        imagemFonte:'leonardo',
        textoDescritivoImagem:'',},

        {ordem:3,
        predecessor:2,
        texto:'Os robôs têm origens nos autômatos, antigos bonecos que se moviam sozinhos, realizando movimentos simples.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/RoboDuRod/img_3.jpg',
        promptImagem:'Cria uma foto altamente realística, em alto padrão de qualidade, ultra HD 4k, de três autômatos dispostos lado a lado, em que os dois autômatos da ponta estão dentro de caixas de vidro sobre suportes de madeira. Preserve todos os detalhes altamente realistas em máximo de fidelidade da foto original', 
        imagemFonte:'leonardo',
        textoDescritivoImagem:'',},

        {ordem:4,
        predecessor:3,
        texto:'Antigamente, para mudar algum movimento de um autômato, os inventores precisavam reconstruir suas partes.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/RoboDuRod/img_4.jpg',
        promptImagem:'Crie uma foto altamente realística, em alto padrão de qualidade, ultra HD 4k, das costas de um autômato dispostos, exibindo cada um dos detalhes das engrenagens e partes mecânicas que permitem que o autômato se mova de modo programático. Preserve todos os detalhes altamente realistas em máximo de fidelidade da foto original.', 
        imagemFonte:'leonardo',
        textoDescritivoImagem:'',},

        {ordem:5,
        predecessor:4,
        texto:'Já os robôs modernos possuem um computador como "cérebro". Por isso, basta alterar programas para modificar seus movimentos.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/RoboDuRod/img_5.jpg',
        promptImagem:'Crie uma imagem 3D ultra-realista de um braço robótico industrial moderno, destacando o interior aberto para manutenção, com foco no computador embutido para programação. Detalhe meticulosamente cada componente, incluindo sensores, câmeras e dispositivos de controle. Destaque a placa-mãe, memórias, bateria e processador do computador integrado. Certifique-se de que a iluminação destaque as características do robô e do ambiente de trabalho, evidenciando claramente que se trata de um braço robótico industrial.', 
        imagemFonte:'leonardo',
        textoDescritivoImagem:'',},

        {ordem:6,
        predecessor:5,
        texto:'Existem muitos tipos de robôs, utilizados para várias finalidades. Por exemplo, robôs industriais fazem tarefas como montar carros ou empacotar produtos.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/RoboDuRod/img_6.jpg',
        promptImagem:'Crie uma imagem 3D altamente realista de um robô empacotador industrial utilizado em uma indústria. O robô deve ser projetado para realizar tarefas complexas de montagem na linha de produção, como cortar, compactar, separar, furar tudo com alta precisão e empacotar, me velocidade incomparável Certifique-se de que o robô tenha um design robusto, com braços articulados e múltiplas ferramentas especializadas. Detalhe cada componente do robô com precisão, incluindo sensores, câmeras e outros dispositivos de controle. Garanta que a iluminação da cena destaque as características do robô e seu ambiente de trabalho na linha de produção de uma indústria alimentícia.', 
        imagemFonte:'leonardo',
        textoDescritivoImagem:'',},

        {ordem:7,
        predecessor:6,
        texto:'E robôs cirúrgicos auxiliam os médicos a operar pacientes.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/RoboDuRod/img_7.jpg',
        promptImagem:'Crie uma imagem 3D altamente realista de um cirurgião robô realizando uma cirurgia no cérebro de um ser humano, em uma sala de cirurgia. Detalhe cada componente do robô com precisão, incluindo sensores, câmeras e outros dispositivos de controle. Garanta que a iluminação da cena destaque as características do robô e seu ambiente de trabalho em um bloco cirúrgico em um ambiente claro, muito limpo e bem iluminado.', 
        imagemFonte:'leonardo',
        textoDescritivoImagem:'',},


        {ordem:8,
        predecessor:7,
        texto:'Já os robôs exploradores são capazes de se mover em locais perigosos e até em outros planetas.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/RoboDuRod/img_8.jpg',
        promptImagem:'Crie uma imagem 3D altamente realista de um robô explorador aventureiro em ação em Marte: o robô equipado com rodas e instrumentos científicos está navegando pelo terreno rochoso e vermelho de Marte, com o céu estrelado e o planeta Terra visíveis ao fundo. Certifique-se de que o robô tenha um design robusto, com braços articulados e múltiplas ferramentas especializadas. Detalhe cada componente do robô com precisão, incluindo sensores, câmeras e outros dispositivos de controle. Garanta que a iluminação da cena destaque as características do robô e seu ambiente de trabalho na linha de produção automotiva. Baseie-se no design do robô rover chamado Explorer, que foi enviado pela NASA na Missão à Marte.', 
        imagemFonte:'leonardo',
        textoDescritivoImagem:'',},

        {ordem:9,
        predecessor:8,
        texto:'No nosso curso, vamos programar robôs, começando com um robô que se move sobre duas rodas.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/RoboDuRod/img_9.jpg',
        promptImagem:'Crie uma imagem renderizada 3D altamente realista de um robô de um robô educacional que se move sobre duas rodas traseiras e possui dois sensores de ultrassom em sua fronteira. Certifique-se de que o robô tenha um design robusto. Detalhe cada componente do robô com precisão, incluindo sensores, LEDs, placas eletrônicas, circuito impresso. Garanta que a iluminação da cena destaque as características do robô e que o robô esteja em um sobre um piso de tom de chumbo.',
        imagemFonte:'leonardo',
        textoDescritivoImagem:'',},

        {ordem:10,
        predecessor:9,
        texto:'Podemos programar os robôs de duas rodas para se mover em diferentes velocidades e direções, mudar de cor, e muito mais.<p>Bem-vindo ao mundo dos robôs!',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/RoboDuRod/img_10.jpg',
        promptImagem:'Crie uma imagem renderizada 3D altamente realista de um robô de um robô educacional que se move sobre duas rodas traseiras e possui dois sensores de ultrassom em sua fronteira. Certifique-se de que o robô tenha um design robusto. Detalhe cada componente do robô com precisão, incluindo sensores, LEDs, casing transparente de placa revestindo seu circuito impresso, e extrutura metálica. Garanta que a iluminação da cena destaque as características do robô e que o robô esteja em um sobre um piso de tom de chumbo. Faça com que um dois leds azuis estejam acesos dentro do casing transparente localizado na parte superior do robô.', 
        imagemFonte:'leonardo',
        textoDescritivoImagem:'',},

      ]}},

    licao6:{},

    licao7:{},

  },

  unidade2:{
    titulo:'',
    descricao:'',
    licao8:{
      id:'CSXAULA08CODE',
      /** padroesCurriculares: 
     titulo:'Lição 08. Laços++.',**/
     infografico:{titulo:'Lição 08. Laço++',
     tituloSimplificado:'Laço',
     estiloPadrao:'basicoPaisagem',
     /** urlVideo:'',
     urlPodcast:'', **/
     cenas:[
       {ordem:1,
       predecessor:0,
      texto:'Hoje, vamos aprender a programar usando um comando poderoso dos algoritmos: os <b>laços</b>, também conhecidos como <b>loops</b>, em inglês.',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacoMM/img_1.png',
       promptImagem:'Arte digital 3D com cores vibrantes de duas setas curvas iniciando-se na extremidade final uma da outra, formando uma elipse, com o letreiro "4x" escrito no centro da elípse., 3d render, typography', 
       imagemFonte:'ideogram',
       textoDescritivoImagem:'',},

       {ordem:2,
       predecessor:1,
       texto:'Os laços permitem que o computador repita comandos várias vezes sem que tenhamos que escrevê-los de novo e de novo no algoritmo.',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacoMM/img_2.png',
       promptImagem:'Arte digital 3D com cores vibrantes de computador deskop all in one de tela ultrafina, em que o monitor está exibindo um código de programação. Envolva todo o código com um circulo externo, 3D, com o texto "repita 6 vezes" para indicar que aquele codigo está sendo executado pelo computador 6 vezes Use uma animação se necessário para enfatizar a repetição dos comandos., typography, 3d render', 
       imagemFonte:'ideogram',
       textoDescritivoImagem:'',},

       {ordem:3,
       predecessor:2,
       texto:'Usando laços, podemos fazer coisas impressionantes com poucos comandos.',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacoMM/img_3.png',
       promptImagem:'Crie uma arte digital 3D de um holograma de uma bailarina de porcelana girando sobre um projetor holográfico de um tablet. Utilize linhas circulares ao redor da bailarina para sugerir um movimento acelerado. Na tela do tablet, desenhe um círculo concêntrico com o feixe do holograma, e abaixo dele, insira o texto "10x" para indicar que a bailarina irá girar 10 vezes ao redor do seu eixo., 3d render, typography',
       //promptImagem:'Crie uma arte digital 3D de uma caixa de música com uma bailarina girando sobre ela. Utilize linhas circulares ao redor da bailarina para indicar um movimento acelerado. Adicione uma manivela na lateral da caixa de música, sugerindo movimento automático da manivela. Em frente à manivela, desenhe um círculo paralelo à caixa de música com o texto "10x" para indicar que a bailarinha vai girar 10 vezes ao redor do seu eixo, 3d render, typography', 
       imagemFonte:'ideogram',
       textoDescritivoImagem:'',},

       {ordem:4,
       predecessor:3,
       texto:'Por exemplo, ao criar um algoritmo para um robô industrial, podemos usar laços para instruir a repetição de ações como cortar, separar e parafusar peças.',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacoMM/img_4.png',
       promptImagem:'Crie uma arte digital 3D que represente um robô industrial cortando um lingote cilíndrico de ferro que está deitando sobre uma esteira deslizante horizontal. Inclua o texto "4x" externamente à cena para indicar que o lingote será cortado 4 vezes., 3d render, typography', 
       imagemFonte:'ideogram',
       textoDescritivoImagem:'',},

       {ordem:5,
       predecessor:4,
       texto:'Um algoritmo para um jogo de corrida pode usar um laço para fazer um carro dar 76 voltas na pista.',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacoMM/img_5.png',
       promptImagem:'Desenvolva uma arte digital 3D de uma televisão e um console de última geração com recurso de realidade 3D. Um jogador segura um controle remoto, voltado para a tela da TV, enquanto joga um jogo de corrida em primeira pessoa. Na tela, mostra-se a traseira de um carro que também está correndo no circuito, com o texto "76 voltas faltantes" sobre o veículo, indicando que ainda faltam 76 voltas para completar o circuito da corrida., 3d render, typography', 
       imagemFonte:'ideogram',
       textoDescritivoImagem:'',},

       {ordem:6,
       predecessor:5,
       texto:'Já imaginou criar um programa para um jogo onde uma personagem caminha enquanto dá várias piruetas? Com os laços, isso fica fácil!',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacoMM/img_6.png',
       promptImagem:'Crie uma arte digital 3D que retrata uma televisão e um console de última geração, com realidade aumentada 3D. Um jogador segura um controle remoto, direcionando-o para a tela da TV enquanto joga um jogo de MMORPGs. Na tela, destaca-se outro personagem do jogo, movendo-se rapidamente e realizando várias piruetas ao redor do personagem do jogador., 3d render, typography', 
       imagemFonte:'ideogram',
       textoDescritivoImagem:'',},

       {ordem:7,
       predecessor:6,
       texto:'Os laços podem ser utilizados dentro de outros laços. A isso chamamos de <b>laços aninhados</b>.',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacoMM/img_7.png',
       promptImagem:'print_plataformamm', 
       imagemFonte:'',
       textoDescritivoImagem:'',},

       {ordem:8,
       predecessor:7,
       texto:'Usando laços, nossos programas ficam mais poderosos e podemos criar coisas divertidas com menos esforço! Prontos para começar?',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacoMM/img_8.png',
       promptImagem:'Crie uma arte digital 3D que represente um monitor e um computador gamer de última geração, com realidade aumentada 3D. Um adolescente está sentado em uma escrivaninha, digitando no teclado enquanto testa um jogo que ele está programando. No monitor, destaca-se uma esfera 3D movendo-se rapidamente, quicando de um lado para o outro e colidindo com blocos que descem pela tela, explodindo ao serem atingidos e concedendo pontos ao jogador.', 
       imagemFonte:'ideogram',
       textoDescritivoImagem:'',},

      ]}},

    licao9:{},

    licao10:{
      id:'CSXAULA10CODE',
      /** padroesCurriculares: 
      titulo:'Lição 10. Expressão Condicional++',**/
		  infografico:{titulo:'Lição 10. Expressão Condicional++',
        tituloSimplificado:'Expressão Condicional',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
         cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Já percebeu quantas decisões tomamos todos os dias? Decidir qual cor de camisa vestir, estudar antes de brincar, escolher entre vôlei ou futebol... Tudo isso depende de diferentes condições.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExprCondMM/img_1.png',
          promptImagem:'Uma imagem dividida em três faixas: na primeira, um homem de negócios escolhe uma camiseta entre várias opções de cores em frente ao seu armário; na segunda, uma adolescente está sentada em uma mesa fazendo seu dever de casa, com uma televisão e um console de última geração exibindo um jogo de videogame ao fundo; na terceira, um adolescente vestido com uniforme de futsal segura uma bola debaixo do braço, enquanto uma adolescente com uniforme de vôlei segura uma bola de vôlei, ambos virados um para o outro em uma quadra poliesportiva, photo, poster', 
          imagemFonte:'ideogram',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Muitas vezes as pessoas nos dão instruções usando condições. Por exemplo: <p><code><b>se</b> está chovendo <br/>&nbsp;&nbsp;&nbsp;então leve guarda-chuva<br/>&nbsp;&nbsp;&nbsp;<b>senão</b> não leve guarda-chuva</code> <br/><br/>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExprCondMM/img_2.png',
          promptImagem:'Uma cena em close mostra uma mãe em pé, com expressão séria, entregando um "closed umbrella" nas mãos da filha, que está vestida com uniforme escolar. Ambas estão viradas uma para a outra na sala de estar de casa, com uma ampla janela ao fundo mostrando a chuva lá fora, poster, photo',
          imagemFonte:'ideogram',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Essas condições nos ajudam a decidir o que fazer em diferentes situações. Por exemplo, no trânsito: <p><code><b>se</b> o sinal estiver vermelho <br/>&nbsp;&nbsp;&nbsp;então pare<br/><br/><b>se</b> o sinal estiver verde <br/>&nbsp;&nbsp;&nbsp;então prossiga</code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExprCondMM/img_3.png',
          promptImagem:'Capture um close da traseira de um sedan parado antes da faixa de pedestres, com um semáforo vermelho claramente aceso ao lado, à frente do veículo, destacando a iluminação noturna em uma avenida movimentada da cidade, poster, photo',
          imagemFonte:'ideogram',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Condições não são úteis apenas para orientar humanos, mas também para programar computadores e componentes eletrônicos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpressoRecriado:'Condições não são úteis apenas para orientar humanos, mas também para programar computadores e componentes eletrônicos. Por exemplo, os semáforos de carro e pedestre estão conectados eletronicamente. Seus componentes eletrônicos garantem que os dois nunca tenham a mesma cor.',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExprCondMM/img_4.png',
          promptImagem:'imagem ultrarrealista que ilustre um adolescente de cerca de 15 anos programando um robô através de um laptop em uma sala de aula de ciências da computação. O adolescente deve ser visível digitando no laptop, com o código de programação refletindo expressões condicionais claramente visíveis na tela. Ao lado do adolescente, um pequeno robô de aparência futurista deve estar executando comandos, como desviar de um obstáculo. A imagem deve incluir detalhes realistas como texturas de cabelo, pele, tecido da roupa do adolescente, assim como detalhes metálicos e luzes no robô, buscando um alto padrão de qualidade e detalhes físicos que se assemelhem a uma fotografia real, poster, photo', 
          imagemFonte:'ideogram',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Por exemplo, os semáforos de carro e pedestre estão conectados eletronicamente. Seus componentes eletrônicos garantem que os dois nunca tenham a mesma cor.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:0,
          imagemImpresso:0,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExprCondMM/img_5.png',
          promptImagem:'Imagem de um cruzamento, em que pedestres estão atravessando na faixa de pedestre e carros estao parados, em ambosos lados da pista, em frente a um sinal vermelho, poster, photo', 
          imagemFonte:'ideogram',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Em algoritmos, utilizamos os termos <b>Se</b>, <b>Então</b> e <b>Senão</b> para expressar condicionais que uma pessoa ou uma máquina deverão obedecer. A isso chamamos <b>expressão condicional</b>. Veja um exemplo: <p><code><b>se</b> sinal = vermelho <br/>&nbsp;&nbsp;&nbsp;então pare<br/><br/><b>se</b> sinal = verde <br/>&nbsp;&nbsp;&nbsp;então prossiga</code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExprCondMM/img_6.png',
          promptImagem:'imagem de um carro ultrapassando um sinal verde, em velocidade acima dos 60 quilômetros por hora, em um rua de uma pequena cidade, em uma dia de sol, photo, poster', 
          imagemFonte:'ideogram',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Note que, para escrever essas condições, usamos sinais matemáticos, como <b>igual (=)</b>, <b>maior que (>)</b> e <b>menor que (<)</b>: <p><code><b>se</b> local atual = centro <br/>&nbsp;&nbsp;&nbsp;então pare <br/><b>se</b> velocidade do carro > 80 km <br/>&nbsp;&nbsp;&nbsp;então diminua a velocidade <br/><b>se</b> combustível do carro < 2 litros <br/>&nbsp;&nbsp;&nbsp;então coloque combustível</code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExprCondMM/img_7.webp',
          promptImagem:'imagem da vista de um motorista de um carro, assentando em frente ao volante, pagando um frentista após o abastecimento do veículo através do vídeo da porta da lateral esquerda do carro', 
          imagemFonte:'dall-e 3',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'E então? Estão prontos para praticar programação com condicionais?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/ExprCondMM/img_8.png',
          promptImagem:'imagem de foto realista, de aluno programando condicionais em um laptop, exibido claramente o trecho de código que exibe a programação de condicionais, poster, photo', 
          imagemFonte:'ideogram',
          textoDescritivoImagem:'',},
        
         ]}},

    licao11:{
      id:'CSXAULA11CODE',
      /** padroesCurriculares: 
      titulo:'Lição 11. Laços Avançados',**/
		  infografico:{titulo:'Lição 11. Laços Avançados',
      tituloSimplificado:'',
      estiloPadrao:'basicoPaisagem',
      /** urlVideo:'',
      urlPodcast:'', **/
      cenas:[
        {ordem:1,
        predecessor:0,
        texto:'Vocês já aprenderam sobre os <b>laços simples</b>, onde repetimos um grupo de comandos um número específico de vezes usando o comando <b>repita</b>.<p><code><b>repita</b> 15 <b>vezes</b><br/>&nbsp;&nbsp;&nbspfaça uma abdominal<br/></code>',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacosAvanc/img_1.webp',
        promptImagem:'Ilustre uma figura tipo pintura, utilizando tons de laranja, verde aquamarine, violeta e branco, que represente o seguinte laço de repetição: repita 15 vezes,  faça uma abdominal', 
        imagemFonte:'dall-e 3',
        textoDescritivoImagem:'',},

        {ordem:2,
        predecessor:1,
        texto:'Agora, vamos explorar algumas técnicas mais avançadas para tornar nossos programas mais eficientes e poderosos.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacosAvanc/img_2.webp',
        promptImagem:'Ilustre uma figura tipo pintura feita em aquarela, utilizando tons de laranja, verde aquamarine, violeta e branco, que representa um programa de computador que ficou mais compacto e eficiente porque o programador utilizou laços aninhados e laços repita e enquanto.', 
        imagemFonte:'dall-e 3',
        textoDescritivoImagem:'',},

        {ordem:3,
        predecessor:2,
        texto:'Uma dessas técnicas, chamada de <b>laços aninhados</b>, consiste em usar um laço dentro de outro. Desse modo, conseguimos reduzir o número de comandos repita.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacosAvanc/img_3.webp',
        promptImagem:'Ilustre uma figura tipo pintura feita em aquarela, utilizando tons de laranja, verde aquamarine, violeta e branco, com as bordas esmaecidas, até ficarem brancas, contendo gotas e manchas de pingos de tinta, mostrando agora o pedaço de corrente formado por três elos no formato de laço infinito (∞), orientado verticalmente com as pontas livres.', 
        imagemFonte:'dall-e 3',
        textoDescritivoImagem:'',},

        {ordem:4,
        predecessor:3,
        texto:'Comparem a quantidade de comandos necessários para desenhar três triângulos usando laços simples versus laços aninhados. É surpreendente como podemos reduzir a quantidade de comandos, não é?',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacosAvanc/img_4.jpg',
        promptImagem:'print', 
        imagemFonte:'code.org',
        textoDescritivoImagem:'',},

        {ordem:5,
        predecessor:4,
        texto:'Além disso, existem outros tipos de laços úteis, como o laço repita enquanto e o laço repita até.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacosAvanc/img_5.jpg',
        promptImagem:'print', 
        imagemFonte:'mmcode',
        textoDescritivoImagem:'',},

        {ordem:6,
        predecessor:5,
        texto:'Usamos o laço <b>repita enquanto</b> para repetir a execução de comandos enquanto uma condição for verdadeira.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacosAvanc/img_6.jpg',
        promptImagem:'print', 
        imagemFonte:'mmcode',
        textoDescritivoImagem:'',},

        {ordem:7,
        predecessor:6,
        texto:'Por exemplo, podemos usar o laço repita enquanto para programar o enchimento do bebedouro inteligente de um canil até que esteja cheio, garantindo água fresca para os animais.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacosAvanc/img_7.webp',
        promptImagem:'Ilustre uma figura tipo pintura feita em aquarela, utilizando tons de laranja, verde aquamarine, violeta e branco, com as bordas esmaecidas, até ficarem brancas, contendo gotas e manchas de pingos de tinta, que representa um programa de computador para o enchimento do bebedouro inteligente hightech no chao de um canil, com display do nível da agua, com um cachorro bebendo agua no bebedouro. ', 
        imagemFonte:'dall-e 3',
        textoDescritivoImagem:'',},

        {ordem:8,
        predecessor:7,
        texto:'Por sua vez, usamos o laço <b>repita até</b> para repetir a execução de comandos até que uma condição seja verdadeira.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacosAvanc/img_8.jpg',
        promptImagem:'print', 
        imagemFonte:'mmcode',
        textoDescritivoImagem:'',},
        
        {ordem:9,
        predecessor:8,
        texto:'Como exemplo, podemos usar o laço repita até para ligar o ar condicionado até que a temperatura alcance um valor que deixe a sala fresquinha, deixando as pessoas confortáveis.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacosAvanc/img_9.webp',
        promptImagem:'Ilustre uma figura tipo pintura feita em aquarela, utilizando tons de laranja, verde aquamarine, violeta e branco, com as bordas esmaecidas, até ficarem brancas,  de um sala de espera, mostrando clientes confortavelmente acomodados em um sofá, com foco em um ar-condicionado que está mantendo o ambiente fresco.', 
        imagemFonte:'dall-e 3',
        textoDescritivoImagem:'',},

        {ordem:10,
        predecessor:9,
        texto:'Laços aninhados e laços "repita enquanto/até" são recursos importantes das linguagens de programação, que possibilitam que nossos programas fiquem mais simples e compreensíveis.',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacosAvanc/img_10.webp',
        promptImagem:'lustre uma figura tipo pintura feita em aquarela, utilizando tons de laranja, verde aquamarine, violeta e branco, com as bordas esmaecidas, até ficarem brancas,  que mostra um programador em sua estação de trabalho, com um monitor exibindo claramente trechos de código que utilizam laços aninhados e laços "repita enquanto/até". A cena deve permitir visualizar como esses elementos tornam os programas mais simples, compreensíveis e poderosos, dentro de um ambiente de escritório decorado com livros de programação e fluxogramas.', 
        imagemFonte:'dall-e 3',
        textoDescritivoImagem:'',},

        {ordem:11,
        predecessor:10,
        texto:'E podemos combinar esses diferentes tipos de laços para criar programas ainda mais poderosos. Vamos praticar?',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CS3/LacosAvanc/img_11.webp',
        promptImagem:'Crie uma ilustração em estilo aquarela que representa um ambiente de sala de aula ou oficina, onde um grupo diversificado de pessoas está reunido ao redor de computadores, praticando programação. A cena capta a ideia de combinar laços aninhados com "laços repita" e "laços até" para criar programas poderosos, com elementos visuais como snippets de código coloridos e fluxogramas nas telas perfeitamente ilustrados. A paleta de cores inclui tons de laranja, verde aquamarine, violeta e branco, com as bordas esmaecidas e detalhes artísticos que reforçam o tema.', 
        imagemFonte:'dall-e 3',
        textoDescritivoImagem:'',},        

      ]}},

    licao12:{},

    licao13:{},

    licao14:{
      id:'CSXAULA14CODE',
      /** padroesCurriculares: 
     titulo:'Lição 14. Programação em Par e Depuração.',**/
     infografico:{titulo:'Lição 14. Programação em Par e Depuração',
     tituloSimplificado:'Depuração',
     estiloPadrao:'basicoPaisagem',
     /** urlVideo:'',
     urlPodcast:'', **/
     cenas:[
       {ordem:1,
       predecessor:0,
       texto:'<b>Programação em par</b> é quando duas pessoas trabalham juntas para escrever um programa de computador.',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'',
       promptImagem:'', 
       imagemFonte:'',
       textoDescritivoImagem:'',},
      
       {ordem:2,
       predecessor:1,
       texto:'Muitas vezes, podemos resolver problemas difíceis mais facilmente quando trabalhamos em dupla.',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'',
       promptImagem:'', 
       imagemFonte:'',
       textoDescritivoImagem:'',},   
         
       {ordem:3,
       predecessor:2,
       texto:'Quando duas pessoas programam em par, enquanto uma cria o programa a outra procura por erros. ',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'',
       promptImagem:'', 
       imagemFonte:'',
       textoDescritivoImagem:'',},

       {ordem:4,
       predecessor:3,
       texto:'Comparado a um jogo, é semelhante a quando um amigo opera o joystick e o outro observa e avisa sobre a aproximação de inimigos.',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'',
       promptImagem:'', 
       imagemFonte:'',
       textoDescritivoImagem:'',},
       
       {ordem:5,
       predecessor:4,
       texto:'Na programação em par, esses dois papéis possuem nomes. O <b>piloto</b> é quem opera e o <b>copiloto</b> é quem observa e procura pelos erros.',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'',
       promptImagem:'', 
       imagemFonte:'',
       textoDescritivoImagem:'',},

       {ordem:6,
       predecessor:5,
       texto:'Em programação, um erro é conhecido como <b>bug</b> (inseto, em inglês)...',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'',
       promptImagem:'', 
       imagemFonte:'',
       textoDescritivoImagem:'',},  

       {ordem:7,
       predecessor:6,
       texto:'E a procura pelo erro como <b>debug</b> (remoção do inseto). Em português, chamamos a isso de <b>depuração</b>.',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'',
       promptImagem:'', 
       imagemFonte:'',
       textoDescritivoImagem:'',},
       
       {ordem:8,
       predecessor:7,
       texto:'Siga essa dica importante: o piloto e o copiloto devem revezar suas funções para não ficarem cansados. Dessa forma, sua dupla fará programas de alta qualidade, com menos bugs.',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'',
       promptImagem:'', 
       imagemFonte:'',
       textoDescritivoImagem:'',},
         
       {ordem:9,
       predecessor:8,
       texto:'Então, lembrem-se: trabalhem em par para fazer bem feito, sempre revezando entre os papéis de piloto e copiloto.',
       urlAudioTexto:'',
       textoSimplificado:'',
       textoImpresso:1,
       imagemImpresso:1,
       urlImagem:'',
       promptImagem:'', 
       imagemFonte:'',
       textoDescritivoImagem:'',},        
     
      ]}},

    },


    unidade3:{
      titulo:'',
      descricao:'',
      licao15:{
        id:'CSXAULA15CODE',
        /** padroesCurriculares: 
        titulo:'Lição 15. Eventos++.',**/
        infografico:{titulo:'Lição 15. Eventos++',
        tituloSimplificado:'Eventos',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Como já aprendemos, um <b>evento</b> é um acontecimento ou ação que pode disparar uma rotina, provocando reações em resposta.', //Você sabe o que é um evento?
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Por exemplo, imagine que você está brincando e, de repente, um gato pula na sua frente. Qual seria sua reação a esse evento?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Na computação, muitos eventos são provocados pelos usuários, como chamamos as pessoas que usam o computador.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Um <b>evento de usuário</b>, em um sistema computacional, é disparado quando o usuário clica com o mouse ou aperta uma tecla do teclado, por exemplo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Os programas de computador são escritos para responder a esses eventos. Por exemplo, abrindo janelas ou movendo personagens em jogos quando ocorre um evento de usuário.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Celulares, tablets e relógios inteligentes são computadores móveis que permitem outros tipos de eventos do usuário. Por exemplo, um toque na tela ou um simples movimento do dispositivo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Alguns programas podem funcionar sem interagir com os usuários. Mas a maioria dos programas que usamos, comos jogos ou aplicativos de redes sociais, estão sempre reagindo aos nossos eventos...',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Quando apertamos uma tecla, clicamos no mouse ou mexemos com um joystick.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:9,
          predecessor:8,
          texto:'Além de eventos de usuário, existem também <b>eventos internos</b> nos próprios computadores, celulares e tablets.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'',
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:10,
          predecessor:9,
          texto:'Por exemplo, se um desses dispositivos ficar muito quente, ele pode disparar um evento para que um programa o desligue.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'',
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
        
         ]}},
  
      licao16:{
        id:'CSXAULA16CODE',
        /** padroesCurriculares: 
        titulo:'Lição 16. Dados e Decomposição',**/
        infografico:{titulo:'Lição 16. Dados e Decomposição',
        tituloSimplificado:'Dados e Decomposição',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Vocês sabem o que são <b>dados</b> digitais?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:2,
          predecessor:1,
          texto:'Pensem neles como coisas que um computador guarda: nomes, lugares onde moramos, quantos anos temos, até fotos e vídeos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:3,
          predecessor:2,
          texto:'Um único <b>dado</b> sozinho, como a idade de alguém que não conhecemos, é só um número sem utilidade...',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:4,
          predecessor:3,
          texto:'Mas quando juntamos com outros dados como altura, endereço, nome, time preferido e foto de uma pessoa, os dados se tornam mais importantes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:5,
          predecessor:4,
          texto:'Por exemplo, se conhecemos os dados e vemos essa pessoa na rua, já saberemos muita coisa sobre ela!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'para essa cena chave, mostrar dados e fotos de uma pessoa em uma tela de celular e a mesma pessoa na rua', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:6,
          predecessor:5,
          texto:'Até agora, você vem resolvendo pequenos problemas no computador criando programas, algoritmos que o computador entende.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:7,
          predecessor:6,
          texto:'Mas muitos problemas maiores também envolvem dados...',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:8,
          predecessor:7,
          texto:'Por exemplo, se queremos fazer um aplicativo para cuidar de animais de estimação, é importante guardar dados para saber se cada animal é um gato ou cachorro, seu tamanho, raça e idade.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:9,
          predecessor:8,
          texto:'Com isso, podemos então fazer programas que se comportam diferente conforme cada animal, usando <b>condicionais</b>.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:10,
          predecessor:9,
          texto:'Por exemplo: se "animal = cachorro" então "passear por 30min com ele todo dia". Se animal = gato" então "deixar que explore o ambiente".',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:11,
          predecessor:10,
          texto:'Quando fazemos isso, nós estamos <b>decompondo</b> o problema, ou seja, dividindo ele em duas partes: dados e programas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:12,
          predecessor:11,
          texto:'Saber usar bem a <b>decomposição de problemas</b> nos ajudará a resolver problemas no computador e na vida.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:13,
          predecessor:12,
          texto:'Legal, né? Vamos entender poder da decomposição e da solução com dados e programas na prática!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
        ]}},

      licao17:{
        id:'CSXAULA17CODE',
        /** padroesCurriculares: 
        titulo:'Lição 17. Expressão Lógica',**/
        infografico:{titulo:'Lição 17. Expressão Lógica',
        tituloSimplificado:'Lógica',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Conforme nós já aprendemos, <b>expressões condicionais</b> como <b>Se</b> e <b>Então</b> são usadas para orientar a tomada de decisões. Por exemplo, no trânsito:<p><code><b>se</b> o sinal estiver vermelho então pare<br/><b>se</b> o sinal estiver verde então prossiga<br/></code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'', },
    
          {ordem:2,
          predecessor:1,
          texto:'Em programação, usamos "Se", "Então" e "Senão" para fazer determinar decisões usando sinais matemáticos como <b>igual (=)</b>, de <b>maior que (>)</b> e de <b>menor que (<)</b>. Veja o algoritmo a seguir: <p><code><b>se</b> sinal = vermelho <br/>&nbsp;&nbsp;&nbsp;então pare<br/><b>se</b> sinal = verde <br/>&nbsp;&nbsp;&nbsp; então prossiga</code>',
          urlAudioTexto:'',	
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'',
          imagemFonte:'',
          textoDescritivoImagem:'', },
    
          {ordem:3,
          predecessor:2,
          texto:'Podemos escrever decisões dentro de outras decisões. Assim, podemos definir as regras do trânsito, incluindo o sinal amarelo. Vejo o exemplo:<p><code><b>se</b> sinal = vermelho então pare<br/><b>senão se</b> sinal = verde então prossiga<br/><b>senão se</b> sinal = amarelo então<br/>&nbsp;&nbsp;&nbsp<b>se</b> já estiver passando sob o sinal<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbspentão prossiga<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp<b>senão</b> pare<br/></code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'',
          imagemFonte:'',
          textoDescritivoImagem:'', },
    
          {ordem:4,
          predecessor:3,
          texto:'Para juntar diferentes condições, usamos os termos <b>E/OU</b>. Eles são chamados de <b>Operadores Lógicos</b>. Compare o exemplo abaixo com o exemplo anterior:<p><code><b>se</b> sinal = vermelho então pare<br/><b>senão se</b> sinal = verde então prossiga<br/><b>senão se</b></b> sinal = amarelo e já estiver passando sob o sinal<br/>&nbsp;&nbsp;&nbsp;então prossiga <br/>&nbsp;&nbsp;&nbsp;<b>senão</b> pare<br/></code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'',
          imagemFonte:'',
          textoDescritivoImagem:'', },

          {ordem:5,
          predecessor:4,
          texto:'Operadores Lógicos ajudam a tomar decisões com base em diferentes informações, como sua agenda semanal. Por exemplo:<p><code><b>se</b> hora = 06h00 então <br/>&nbsp;&nbsp; <b>se</b> dia = sábado ou dia = domingo <br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; então durma um pouco mais<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>senão</b> vá para a escola<br/></code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'',
          imagemFonte:'',
          textoDescritivoImagem:'', },

          {ordem:6,
          predecessor:5,
          texto:'Além de <b>E/OU</b>, também temos o <b>NÃO</b>, que inverte uma decisão. Veja o exemplo:<p><code><b>se</b> estiver com sede então<br/>&nbsp;&nbsp; <b>se</b> não estiver de jejum então beba água<br/></code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'',
          imagemFonte:'',
          textoDescritivoImagem:'', }, 
            
          {ordem:7,
          predecessor:6,
          texto:'Muita coisa nova, não é? Mas não se preocupe, vamos praticar já para aprendermos a criar novos programas utilizando essas <b>Expressões Lógicas</b>.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'',
          imagemFonte:'',
          textoDescritivoImagem:'', },
        
        ]}},			
  
      licao18:{},

      licao19:{},

      licao20:{},

      licao21:{
        id:'CSXAULA21CODE',
        /** padroesCurriculares: 
        titulo:'Lição 21. Busca e Privacidade',**/
        infografico:{titulo:'Lição 21. Busca e Privacidade',
        tituloSimplificado:'Busca e Privacidade',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Hoje vamos aprender a <b>navegar</b>, ou seja, <b>usar</b> a internet com segurança!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:2,
          predecessor:1,
          texto:'Pensem na <b>internet</b> como uma biblioteca gigante cheia de informações sobre tudo que vocês podem imaginar.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:3,
          predecessor:2,
          texto:'Quando queremos explorar essa biblioteca, usamos algo chamado <b>navegador</b>, que é como um guia que nos ajuda a achar o que precisamos nessa imensa biblioteca online.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:4,
          predecessor:3,
          texto:'Com o navegador, podemos procurar por qualquer coisa digitando em <b>sites de busca</b>.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:5,
          predecessor:4,
          texto:'Mas, temos que tomar cuidado com os <b>dados pessoais</b> que informamos na internet...',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:6,
          predecessor:5,
          texto:'<b>Dados pessoais</b> revelam coisas sobre nós, como onde moramos ou o que gostamos de fazer. E isso pode ser usado por pessoas com más intenções para nos enganar... o que, infelizmente, é muito comum.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:7,
          predecessor:6,
          texto:'Por isso, é muito importante não digitar esses dados na internet, quando os sites pedem, sem ter alguém orientando.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:8,
          predecessor:7,
          texto:'Também é bom evitar sites que parecem estranhos ou que oferecem coisas que são boas demais para ser verdade. Eles podem tentar fazer vocês baixarem programas ruins que estragam o computador e pegam suas informações.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:9,
          predecessor:8,
          texto:'Se algo parecer suspeito, falem com um adulto de confiança.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:10,
          predecessor:9,
          texto:'Com esses cuidados, podemos usar a internet de forma segura e divertida.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:11,
          predecessor:10,
          texto:'Prontos para começar a explorar a internet com segurança?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
        ]}},

      },

    unidade4:{
      titulo:'',
      descricao:'',
      licao22:{
        id:'CSXAULA22CODE',
        /** padroesCurriculares: 
        titulo:'Lição 22. Os Primórdios da Animação.',**/
        infografico:{titulo:'Lição 22. Animações do Analógico ao Digital',
        tituloSimplificado:'Animações',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Há muito tempo, os homens das cavernas fizeram as primeiras tentativas de criar uma ilusão de movimento com desenhos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Esses homens pré-históricos desenhavam animais com patas duplicadas. Quando alguém passava uma tocha sobre esse desenho na parede da caverna, as patas parecima se movimentar.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'No tempo dos faraós, no Egito, as pessoas desenhavam figuras em sequência com poses muito próximas umas das outras, dando a ideia de movimento.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'A mais de 5.000 anos atrás, alguém fez pinturas em um vaso, que, quando girado, produzia uma <b>animação</b>: um alce parecia pular e alcançar folhas de árvore.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Há aproximadamente 150 anos, surgiram brinquedos de animação em papel, como o <b>folioscópio</b>. Ele é um bloco de papel com desenhos em sequência, que, quando foleado rapidamente, produz uma animação.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Já o <b>taumatrópio</b> traz dois desenhos, em sua frente e verso. Quando girado rapidamente, permite ver os dois ao mesmo tempo como se fosse uma única imagem.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:7,
          predecessor:6,
          texto:'Um brinquedo um pouco mais sofisticado é o <b>zootrópio</b>, que alguém pode ser girar para criar uma animação com maior duração porque usa mais desenhos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:8,
          predecessor:7,
          texto:'Usando o zootrópio, inventores criativos produziram as primeiras animações em 3D, trocando os desenhos por bonecos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:9,
          predecessor:8,
          texto:'Todas essas invenções primitivas nos revelam o segredo da animação: o movimento que percebemos é apenas uma ilusão, criada a partir da troca rápida entre imagens paradas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:10,
          predecessor:9,
          texto:'Esse princípio continua sendo a base da animação moderna, que vemos seja na TV, cinema ou jogos de computadores.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:11,
          predecessor:10,
          texto:'Para vocês entenderem bem, vamos recriar a história da animação, produzindo inventos de todas as gerações até a animação digital!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
         ]}},
  
      licao23:{},

      licao24:{},

      licao25:{},

      licao26:{
        id:'CSXAULA26CODE',
        /** padroesCurriculares: 
        titulo:'Lição 26. Introdução ao Laboratório de Histórias.',**/
        infografico:{titulo:'Lição 26. Introdução ao Story Lab',
        tituloSimplificado:'O Story Lab',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
          cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Desde muito tempo atrás, as pessoas contam histórias para se conectar umas com as outras, expressando seus sonhos, medos e desejos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'A forma de contar essas histórias evoluiu com o tempo. Antes elas eram contadas em volta do fogo, depois com desenhos, livros, filmes e, mais recentemente, com animações feitas por computador. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:3,
          predecessor:2, 
          texto:'O "Story Lab" é um laboratório onde nós podemos criar e programar histórias digitais.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3, 
          texto:'Para começar, definimos um título, escrevemos o nome do autor e uma breve descrição da história.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Escolhemos então uma imagem de fundo, também chamada de <b>cenário</b>, para ocupar o <b>palco</b>, área da tela onde a história vai acontecer.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Podemos aplicar <b>cores</b> diversas ao cenário. Elas não são apenas decorativas, como veremos a seguir.', 
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'O próximo passo é escolher os <b>atores</b>, as personagens de nossa história. São eles que nós programamos... Após arrastar o ator para o palco, é possível mudar seu nome, tamanho e outras características.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Podemos programar os movimentos das ators. Eles podem andar, pular, cair... inclusive falar, pensar e gritar, tudo o que você imaginar. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:9,
          predecessor:8,
          texto:'Por fim, podemos acrescentar variados <b>elementos</b> ao cenário, arrastando das seções Utilitários, Cidade e Campo. E configurar estes elementos clicando sobre eles.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:10,
          predecessor:9,
          texto:'Quando um ator se encontra com um elemento podemos definir o que acontece. O ator cai? O elemento muda de cor ou faz alguma animação?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:11,
          predecessor:10,
          texto:'Do mesmo modo, podemos definir o que acontece quando o ator se encontra com uma casa com um certa cor.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
          {ordem:12,
          predecessor:11,
          texto:'Na seção "aparência" temos blocos que nos permitem narrar a história ou programar o diálogo entre os atores.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:13,
          predecessor:12,
          texto:'Legal, não? Com todas essas ferramentas, sua criatividade é o limite. Com o Story Lab, vocês podem criar cenas divertidas e surpreendentes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
         ]}},

        licao27:{},
  
      },



  capaVerso:{
		urlImagemTerceiraCapa:'',
    textoTerceiraCapa: '',
    textoUltimaCapa: 'John von Neumann foi um matemático húngaro, considerado um dos mais importantes matemáticos do século XX que fez parte do time de construtores do ENIAC.'
  },
}