let livro_cs3 ={

  /* metadados 2 */
  metadados:{
	  i18n:false,
	  formularioRegistro_campos_formatosValidos:['texto','numero','data','url','lista','nome','usuario','senha','usuarioAcessivel','senhaAcessivel'],
	  infografico_estilosValidos:['basicoPaisagem','basicoRetrato','explosaoPaisagem','circuitoPaisagem','cobraPaisagem','cobraPaisagem2', 'cobraRetrato','gPaisagem'] 
  },

  versao:'0.1.00',
  nomeFantasia: '',
  nomeTecnico:'CS3',
  resumo:'John von Neumann foi um matemático húngaro, considerado um dos mais importantes matemáticos do século XX que fez parte do time de construtores do ENIAC.',
  isbn:'',
  autores:[],
  editor:'',
  local:'',
  ano:'',

  versaoAdaptacao:'',
  nomeAdaptacaoo: '',
  autoresAdaptacao:[],
  local:'',
  escola:'',
  ano:'',
  url:'',
  codigoCid11:'', /* opc */
  descritivoPerfilAluno:'',
  resumoAdaptacao:'',


  capa:{
		urlImagemCapa:'',
		urlImagemSegundaCapa: '',
  },

  visaogeral:{
	  infografico:{
		  titulo:'Resumo do Módulo CSX',
		  /* idem licoes */
	  }},
  
   /* conteudo */
  unidade1:{
	  titulo:'',
	  descricao:'',
	  licao1:{
		  id:'CSXAULA01CODE',
		  /** padroesCurriculares: 
		  titulo:'Lição 01. ',**/
		  infografico:{titulo:'TODO Lição 01.',
		  tituloSimplificado:'',
		  estiloPadrao:'basicoPaisagem',
			/** urlVideo:'',
			urlPodcast:'', **/
			cenas:[
        {ordem:1,
        predecessor:0,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
		    imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:2,
        predecessor:1,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:3,
        predecessor:2,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:4,
        predecessor:3,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:5,
        predecessor:4,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:6,
        predecessor:5,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:7,
        predecessor:6,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:8,
        predecessor:7,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:9,
        predecessor:8,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:10,
        predecessor:9,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

      ]}},

    licao2:{},

    licao3:{
      id:'CSXAULA03CODE',
      /** padroesCurriculares: 
      titulo:'Lição 03. ',**/
		  infografico:{titulo:'TODO Lição 03.',
      tituloSimplificado:'',
      estiloPadrao:'basicoPaisagem',
      /** urlVideo:'',
      urlPodcast:'', **/
      cenas:[
        {ordem:1,
        predecessor:0,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:2,
        predecessor:1,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:3,
        predecessor:2,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:4,
        predecessor:3,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:5,
        predecessor:4,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:6,
        predecessor:5,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:7,
        predecessor:6,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:8,
        predecessor:7,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:9,
        predecessor:8,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:10,
        predecessor:9,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

      ]}},

    licao4:{
      id:'CSXAULA04CODE',
      /** padroesCurriculares: 
      titulo:'Lição 04. ',**/
		  infografico:{titulo:'TODO Lição 04.',
      tituloSimplificado:'',
      estiloPadrao:'basicoPaisagem',
      /** urlVideo:'',
      urlPodcast:'', **/
      cenas:[
        {ordem:1,
        predecessor:0,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:2,
        predecessor:1,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:3,
        predecessor:2,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:4,
        predecessor:3,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:5,
        predecessor:4,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:6,
        predecessor:5,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:7,
        predecessor:6,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:8,
        predecessor:7,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:9,
        predecessor:8,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:10,
        predecessor:9,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

      ]}},

    licao5:{
      id:'CSXAULA05CODE',
      /** padroesCurriculares: 
      titulo:'Lição 05. ',**/
		  infografico:{titulo:'TODO Lição 05.',
      tituloSimplificado:'',
      estiloPadrao:'basicoPaisagem',
      /** urlVideo:'',
      urlPodcast:'', **/
      cenas:[
        {ordem:1,
        predecessor:0,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:2,
        predecessor:1,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:3,
        predecessor:2,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:4,
        predecessor:3,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:5,
        predecessor:4,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:6,
        predecessor:5,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:7,
        predecessor:6,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:8,
        predecessor:7,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:9,
        predecessor:8,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:10,
        predecessor:9,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

      ]}},

    licao6:{},

    licao7:{},

  },

  unidade2:{
    titulo:'',
    descricao:'',
    licao8:{
      id:'CSXAULA08CODE',
      /** padroesCurriculares: 
      titulo:'Lição 08. ',**/
		  infografico:{titulo:'TODO Lição 08.',
      tituloSimplificado:'',
      estiloPadrao:'basicoPaisagem',
      /** urlVideo:'',
      urlPodcast:'', **/
      cenas:[
        {ordem:1,
        predecessor:0,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:2,
        predecessor:1,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:3,
        predecessor:2,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:4,
        predecessor:3,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:5,
        predecessor:4,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:6,
        predecessor:5,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:7,
        predecessor:6,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:8,
        predecessor:7,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:9,
        predecessor:8,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:10,
        predecessor:9,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

      ]}},

    licao9:{},

    licao10:{
      id:'CSXAULA10CODE',
      /** padroesCurriculares: 
      titulo:'Lição 10. ',**/
		  infografico:{titulo:'TODO Lição 10.',
      tituloSimplificado:'',
      estiloPadrao:'basicoPaisagem',
      /** urlVideo:'',
      urlPodcast:'', **/
      cenas:[
        {ordem:1,
        predecessor:0,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:2,
        predecessor:1,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:3,
        predecessor:2,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:4,
        predecessor:3,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:5,
        predecessor:4,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:6,
        predecessor:5,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:7,
        predecessor:6,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:8,
        predecessor:7,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:9,
        predecessor:8,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:10,
        predecessor:9,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

      ]}},

    licao11:{
      id:'CSXAULA11CODE',
      /** padroesCurriculares: 
      titulo:'Lição 11. ',**/
		  infografico:{titulo:'TODO Lição 11.',
      tituloSimplificado:'',
      estiloPadrao:'basicoPaisagem',
      /** urlVideo:'',
      urlPodcast:'', **/
      cenas:[
        {ordem:1,
        predecessor:0,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:2,
        predecessor:1,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:3,
        predecessor:2,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:4,
        predecessor:3,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:5,
        predecessor:4,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:6,
        predecessor:5,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:7,
        predecessor:6,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:8,
        predecessor:7,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:9,
        predecessor:8,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:10,
        predecessor:9,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

      ]}},

    licao12:{},

    licao13:{},

    licao14:{
      id:'CSXAULA14CODE',
      /** padroesCurriculares: 
      titulo:'Lição 14. ',**/
		  infografico:{titulo:'TODO Lição 14.',
      tituloSimplificado:'',
      estiloPadrao:'basicoPaisagem',
      /** urlVideo:'',
      urlPodcast:'', **/
      cenas:[
        {ordem:1,
        predecessor:0,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:2,
        predecessor:1,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:3,
        predecessor:2,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:4,
        predecessor:3,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:5,
        predecessor:4,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:6,
        predecessor:5,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:7,
        predecessor:6,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:8,
        predecessor:7,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:9,
        predecessor:8,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

        {ordem:10,
        predecessor:9,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        textoImpresso:1,
        imagemImpresso:1,
        urlImagem:'',
        promptImagem:'', 
        imagemFonte:'',
        textoDescritivoImagem:'',},

      ]}},

    },


    unidade3:{
      titulo:'',
      descricao:'',
      licao15:{
        id:'CSXAULA15CODE',
        /** padroesCurriculares: 
        titulo:'Lição 15. ',**/
        infografico:{titulo:'TODO Lição 15.',
        tituloSimplificado:'',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:2,
          predecessor:1,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:3,
          predecessor:2,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:4,
          predecessor:3,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:5,
          predecessor:4,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:6,
          predecessor:5,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:7,
          predecessor:6,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:8,
          predecessor:7,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:9,
          predecessor:8,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:10,
          predecessor:9,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
        ]}},

      licao16:{
        id:'CSXAULA16CODE',
        /** padroesCurriculares: 
        titulo:'Lição 16. Dados e Decomposição',**/
        infografico:{titulo:'Dados e Decomposição',
        tituloSimplificado:'Dados e Decomposição',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Vocês sabem o que são <b>dados</b> digitais?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:2,
          predecessor:1,
          texto:'Pensem neles como coisas que um computador guarda: nomes, lugares onde moramos, quantos anos temos, até fotos e vídeos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:3,
          predecessor:2,
          texto:'Um único <b>dado</b> sozinho, como a idade de alguém que não conhecemos, é só um número sem utilidade...',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:4,
          predecessor:3,
          texto:'Mas quando juntamos com outros dados como altura, endereço, nome, time preferido e foto de uma pessoa, os dados se tornam mais importantes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:5,
          predecessor:4,
          texto:'Por exemplo, se conhecemos os dados e vemos essa pessoa na rua, já saberemos muita coisa sobre ela!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'para essa cena chave, mostrar dados e fotos de uma pessoa em uma tela de celular e a mesma pessoa na rua', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:6,
          predecessor:5,
          texto:'Até agora, você vem resolvendo pequenos problemas no computador criando programas, algoritmos que o computador entende.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:7,
          predecessor:6,
          texto:'Mas muitos problemas maiores também envolvem dados...',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:8,
          predecessor:7,
          texto:'Por exemplo, se queremos fazer um aplicativo para cuidar de animais de estimação, é importante guardar dados para saber se cada animal é um gato ou cachorro, seu tamanho, raça e idade.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:9,
          predecessor:8,
          texto:'Com isso, podemos então fazer programas que se comportam diferente conforme cada animal, usando <b>condicionais</b>.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:10,
          predecessor:9,
          texto:'Por exemplo: se "animal = cachorro" então "passear por 30min com ele todo dia". Se animal = gato" então "deixar que explore o ambiente".',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:11,
          predecessor:10,
          texto:'Quando fazemos isso, nós estamos <b>decompondo</b> o problema, ou seja, dividindo ele em duas partes: dados e programas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:12,
          predecessor:11,
          texto:'Saber usar bem a <b>decomposição de problemas</b> nos ajudará a resolver problemas no computador e na vida.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:13,
          predecessor:12,
          texto:'Legal, né? Vamos entender poder da decomposição e da solução com dados e programas na prática!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
        ]}},

      licao17:{
        id:'CSXAULA17CODE',
        /** padroesCurriculares: 
        titulo:'Lição 17. ',**/
        infografico:{titulo:'TODO Lição 17.',
        tituloSimplificado:'',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:2,
          predecessor:1,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:3,
          predecessor:2,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:4,
          predecessor:3,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:5,
          predecessor:4,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:6,
          predecessor:5,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:7,
          predecessor:6,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:8,
          predecessor:7,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:9,
          predecessor:8,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:10,
          predecessor:9,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
        ]}},
  
      licao18:{},

      licao19:{},

      licao20:{},

      licao21:{
        id:'CSXAULA21CODE',
        /** padroesCurriculares: 
        titulo:'Lição 21. Busca e Privacidade',**/
        infografico:{titulo:'Busca e Privacidade',
        tituloSimplificado:'Busca e Privacidade',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Hoje vamos aprender a <b>navegar</b>, ou seja, <b>usar</b> a internet com segurança!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:2,
          predecessor:1,
          texto:'Pensem na <b>internet</b> como uma biblioteca gigante cheia de informações sobre tudo que vocês podem imaginar.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:3,
          predecessor:2,
          texto:'Quando queremos explorar essa biblioteca, usamos algo chamado <b>navegador</b>, que é como um guia que nos ajuda a achar o que precisamos nessa imensa biblioteca online.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:4,
          predecessor:3,
          texto:'Com o navegador, podemos procurar por qualquer coisa digitando em <b>sites de busca</b>.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:5,
          predecessor:4,
          texto:'Mas, temos que tomar cuidado com os <b>dados pessoais</b> que informamos na internet...',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:6,
          predecessor:5,
          texto:'<b>Dados pessoais</b> revelam coisas sobre nós, como onde moramos ou o que gostamos de fazer. E isso pode ser usado por pessoas com más intenções para nos enganar... o que, infelizmente, é muito comum.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:7,
          predecessor:6,
          texto:'Por isso, é muito importante não digitar esses dados na internet, quando os sites pedem, sem ter alguém orientando.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:8,
          predecessor:7,
          texto:'Também é bom evitar sites que parecem estranhos ou que oferecem coisas que são boas demais para ser verdade. Eles podem tentar fazer vocês baixarem programas ruins que estragam o computador e pegam suas informações.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:9,
          predecessor:8,
          texto:'Se algo parecer suspeito, falem com um adulto de confiança.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:10,
          predecessor:9,
          texto:'Com esses cuidados, podemos usar a internet de forma segura e divertida.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:11,
          predecessor:10,
          texto:'Prontos para começar a explorar a internet com segurança?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
        ]}},

      },

    unidade4:{
      titulo:'',
      descricao:'',
      licao22:{
        id:'CSXAULA22CODE',
        /** padroesCurriculares: 
        titulo:'Lição 22. ',**/
        infografico:{titulo:'TODO Lição 22.',
        tituloSimplificado:'',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:2,
          predecessor:1,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:3,
          predecessor:2,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:4,
          predecessor:3,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:5,
          predecessor:4,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:6,
          predecessor:5,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:7,
          predecessor:6,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:8,
          predecessor:7,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:9,
          predecessor:8,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:10,
          predecessor:9,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
        ]}},
  
      licao23:{},

      licao24:{},

      licao25:{},

      licao26:{
        id:'CSXAULA26CODE',
        /** padroesCurriculares: 
        titulo:'Lição 26. ',**/
        infografico:{titulo:'TODO Lição 26.',
        tituloSimplificado:'',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:2,
          predecessor:1,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:3,
          predecessor:2,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:4,
          predecessor:3,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:5,
          predecessor:4,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:6,
          predecessor:5,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:7,
          predecessor:6,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:8,
          predecessor:7,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:9,
          predecessor:8,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
          {ordem:10,
          predecessor:9,
          texto:'',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
  
        ]}},

        licao27:{},
  
      },



  capaVerso:{
		urlImagemTerceiraCapa:'',
    textoTerceiraCapa: '',
    textoUltimaCapa: 'John von Neumann foi um matemático húngaro, considerado um dos mais importantes matemáticos do século XX que fez parte do time de construtores do ENIAC.'
  },
}