let livro_cw2 ={

  /* metadados 2 */
  versao:'0.1.00',
  nomeFantasia: '',
  nomeTecnico:'CW2 - Fundamentos em Ciência da Computação 2',
  resumo:'Charles Babbage foi um cientista, matemático, filósofo, engenheiro mecânico e inventor inglês que é mais conhecido como o inventor que projetou o primeiro computador de uso geral, utilizando apenas partes mecânicas, a máquina analítica.',
  isbn:'',
  autores:[],
  editor:'',
  local:'',
  ano:'',
  url:'compsci_cw2_0_1',

  versaoAdaptacao:'',
  nomeAdaptacaoo: '',
  autoresAdaptacao:[],
  local:'',
  escola:'',
  ano:'',
  url:'',
  codigoCid11:'', /* opc */
  descritivoPerfilAluno:'',
  resumoAdaptacao:'',

  capa:{
		urlImagemCapa:'',
		urlImagemSegundaCapa: '',
  },
  
   formularioRegistro:{
	  titulo:'',
	  urlImagem:'',
	  campos:[
	   {rotulo:'Login Somos:',formato:'usuarioAcessivel'},{rotulo:'Senha:',formato:'senhaAcessivel'}
	  ]},
  
  visaogeral:{
	  infografico:{
		  titulo:'Resumo do Módulo CW2',
		  /* idem licoes */
	  }},

    /* conteudo */
    unidade1:{
      titulo:'Fundamentos de Programação',
      descricao:'Nesta unidade, você será apresentado ao computador, aos dispositivos eletrônicos e aos robôs, além de dar os primeiros passos em programação.<br/>Você começará a utilizar o pensamento computacional na resolução de desafios lógicos por meio de algoritmos.',
      licao1:{
        id:'CW2AULA01CODE',
        /** padroesCurriculares: 
        titulo:'Lição 01. Dispositivos Computacionais.',**/
        infografico:{titulo:'Computador e Dispositivos Computacionais',
        tituloSimplificado:'O Computador',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Hoje, nós vamos descobrir como é divertido programar computadores. Estes serão seus primeiros passos na ciência da computação.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Você já brincou com um computador ou celular? Eles são aparelhos eletrônicos e possuem diversas partes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'O computador de mesa, por exemplo, tem quatro partes: a torre, o teclado, o monitor e o mouse.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:`Na <b>torre</b> existem componentes como as memórias, onde o computador armazena dados. E o processor, que funciona como o "cérebro do computador".`,
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Com o <b>teclado</b> e o <b>mouse</b>, nós conseguimos digitar, mover e clicar em objetos exibidos na tela, chamada de <b>monitor</b>.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Podemos também conectar outros dispositivos ao computador, como caixas de som ou impressoras.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Celulares e tablets também são computadores, embora pequenos, para caberem na palma das nossas mãos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Mas existem computadores ainda menores, embutidos dentro de carros, TVs e até mesmo brinquedos. Eles tornam estes aparelhos mais inteligentes e capazes de nos ajudar no dia a dia.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:9,
          predecessor:8,
          texto:'Mas, afinal, o que é um computador? É uma máquina que pode ser programada para nos ajudar nas mais variadas tarefas, seja no trabalho, na escola ou em momentos de lazer.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:10,
          predecessor:9,
          texto:'Neste curso, vamos aprender a criar jogos, inventos eletrônicos, a programar robôs e montar inventos. Tudo isso é <b>ciência da computação</b>!',
          urlAudioTexto:'https://storage.googleapis.com/mindmakers/cpsciaudioinf/csx_i1_1.mp3',
          textoSimplificado:'Primeiros passos',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CSX/DispComp/img_1_new.jpg',
          promptImagem:'', 
          imagemFonte:'bing',
          textoDescritivoImagem:'Programador em frente ao computador',},
        
         ]}},


      licao2:{},


      licao3:{
        id:'CW2AULA03CODE',
        /** padroesCurriculares: 
        titulo:'Lição 03. Eletricidade e Dispositivos Eletrônicos.',**/
        infografico:{titulo:'Explorando a Eletricidade e Seus Segredos',
        tituloSimplificado:'Eletricidade',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'A <b>eletricidade</b> é um tipo de energia que chega em nossas casas por meio das chamadas <b>redes elétricas</b>, como podemos observar pelos grandes cabos e postes que vemos nas ruas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Em casa, usamos eletricidade para esquentar água, esfriar alimentos na geladeira e ligar aparelhos como lâmpadas, TVs e, é claro, os computadores e até robôs.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Computadores portáteis, robôs e outros aparelhos chamados <b>eletrônicos</b> podem funcionar sem estarem conectados à tomada, desde que possuam baterias.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Já as <b>baterias</b> são componentes que armazenam energia por um tempo. Quando a energia acaba, recarregamos as baterias nas tomadas que trazem energia da rede elétrica.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Existem muitos tipos de aparelhos eletrônicos, para diferentes finalidades. Neste curso, mais do que usar, vamos criar dispositivos eletrônicos variados.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
            
                  
          {ordem:6,
          predecessor:5,
          texto:'Todo aparelho eletrônico é formado por <b>componentes</b>. Vamos aprender quais são os principais componentes, antes de criar nossos próprios inventos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Um primeiro tipo de componente é chamado de <b>gerador</b>. Ele fornece energia para os demais componentes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Há também os <b>controladores</b>, componentes que as pessoas usam para controlar os aparelhos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:9,
          predecessor:8,
          texto:'Já os componentes <b>condutores</b> servem para transportar a energia elétrica entre os componentes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:10,
          predecessor:9,
          texto:'Por fim, os componentes <b>atuadores</b> são aqueles que executam a ação principal do aparelho, seja acender uma luz, fazer algum movimento ou outra qualquer.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:11,
          predecessor:10,
          texto:'Juntando esses quatro tipos de componentes, podemos criar diferentes inventos para explorar os mistérios da eletricidade.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpressoRecriado:'Juntando esses quatro tipos de componentes, podemos criar diferentes inventos para explorar os mistérios da eletricidade. A diversão e o aprendizado estão prestes a começar!',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:12,
          predecessor:11,
          texto:'A diversão e o aprendizado estão prestes a começar! Prontos para desvendar os segredos da eletricidade?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:0,
          imagemImpresso:0,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
         ]}},


      licao4:{
        id:'CW2AULA04CODE',
        /** padroesCurriculares: 
        titulo:'Lição 04. Algoritmo, Identificação de Padrão e Sequência.',**/
        infografico:{titulo:'Algoritmos no Nosso Dia a Dia',
        tituloSimplificado:'Algoritmos',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Um <b>algoritmo</b> é como uma receita que explica a uma pessoa ou máquina, passo a passo, como realizar uma tarefa de modo correto.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'r',},

          {ordem:2,
          predecessor:1,
          texto:'Algumas vezes, os algoritmos são representados por figuras ou símbolos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Outras vezes, podemos chamá-los de <b>diagramas</b>, que são desenhos com formas ligadas por linhas, onde cada forma representa um passo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Algoritmos podem ser escritos como uma lista numerada de passos para realizar uma tarefa simples.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Alguns algoritmos são muito grandes e complicados, como aqueles que ajudam astronautas a resolver problemas no espaço.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'No mundo computacional, os chamados <b>programas de computador</b> também são algoritmos, escritos em uma linguagem que o computador entende.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Um bom algoritmo é importante para que uma tarefa seja realizada de modo perfeito, seja por uma pessoa ou máquina.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Por isso, neste curso, vamos aprender algoritmos na prática, colocando a "mão na massa"!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          ]}},

      licao5:{
        id:'CW2AULA05CODE',
        /** padroesCurriculares: 
        titulo:'Lição 05. Robótica.',**/
        infografico:{titulo:'Robótica com o Robô Esfera',
        tituloSimplificado:'Robô Esfera',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[

          {ordem:1,
          predecessor:0,
          texto:'Um <b>robô</b> é uma máquina programável que executa tarefas automaticamente.', 
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Nós já vimos robôs em filmes e jogos... Eles podem ter pernas, rodas ou parecer com humanos. Mas vocês sabem como eles surgiram?', //Conferir com Alvim: frases para engajamento serão no plural (como está nessa frase) ou no singular?
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Os robôs têm origens nos autômatos, antigos bonecos que se moviam sozinhos, realizando movimentos simples.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Antigamente, para mudar algum movimento de um autômato, os inventores precisavam reconstruir suas partes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Já os robôs modernos possuem um computador como "cérebro". Por isso, basta alterar programas para modificar seus movimentos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Existem muitos tipos de robôs, utilizados para várias finalidades. Por exemplo, robôs industriais fazem tarefas como montar carros ou empacotar produtos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'E robôs cirúrgicos auxiliam os médicos a operar pacientes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},


          {ordem:8,
          predecessor:7,
          texto:'Já os robôs exploradores são capazes de se mover em locais perigosos e até em outros planetas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:9,
          predecessor:8,
          texto:'No nosso curso, vamos programar diferentes robôs, começando com um robô esfera, que se move como o BB-8 de Star Wars.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:10,
          predecessor:9,
          texto:'Podemos programar o robô esfera para se mover em diferentes velocidades e direções, mudar de cor, e muito mais.<p>Bem-vindo ao mundo dos robôs!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
         
        
         ]}},


        licao6:{
        id:'CW2AULA06CODE',
        /** padroesCurriculares: 
        titulo:'Lição 06. Projeto Taxibot.',**/
        infografico:{titulo:'Taxibot: Taxiamento Robotizado',
        tituloSimplificado:'Taxibot',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Vocês sabiam que os aviões são o meio de transporte mais rápido e seguro do mundo?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Eles foram inventados por um brasileiro chamado Santos Dumont!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Com suas grandes asas e turbinas poderosas, os aviões são feitos para voar, não para andar.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Damos o nome de <b>taxiamento</b> ao movimento que aviões fazem no chão, indo dos portões onde os passageiros embarcam até a pista do aeroporto, e vice-versa.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Mas usar turbinas para taxiamento gasta muito combustível e faz muito barulho.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Será que existe uma maneira melhor de mover os aviões no solo? Para resolver isso, foi desenvolvido o Taxibot!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'O Taxibot é um veículo <b>semirobotizado</b>, ou seja, é controlado por humanos, mas capaz de realizar muitas tarefas de forma automática.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Com mais segurança, menos combustível e menos barulho, o Taxibot leva os aviões entre portões e pistas sem ligar as turbinas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:9,
          predecessor:8,
          texto:'Mas sempre podemos melhorar! Que tal criar um taxibot totalmente robotizado que funcione só com programação?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
          ]}},


      licao7:{},	

    },


    unidade2:{
      titulo:'Condicionais, Robótica e Eventos Computacionais',
      descricao:'Nesta unidade, você aprenderá os conceitos de laços e expressões condicionais, utilizando-os para resolver desafios lógicos de programação e programar robôs.<br/>Você também aprenderá o conceito de programação orientada a eventos e usará um dispositivo eletrônico para criar seu próprio controle criativo de videogame, utilizando materiais diversos, como massinha ou lápis!',
      licao8:{
        id:'CW2AULA08CODE',
        /** padroesCurriculares: 
        titulo:'Lição 08. Laços.',**/
        infografico:{titulo:'Laço em Algoritmos',
        tituloSimplificado:'Laço',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Hoje, vamos aprender sobre um comando poderoso dos algoritmos: os <b>laços</b>, também conhecidos como <b>loops</b>, em inglês.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Os laços permitem que o computador repita comandos várias vezes sem que tenhamos que escrevê-los de novo e de novo no algoritmo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Usando laços, podemos fazer coisas impressionantes com poucos comandos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Por exemplo, ao criar um algoritmo para um robô industrial, podemos usar laços para instruir a repetição de ações como cortar, separar e parafusar peças.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Um algoritmo para um jogo de corrida pode usar um laço para fazer um carro dar 76 voltas na pista.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Já imaginou criar um programa para um jogo onde uma personagem caminha enquanto dá várias piruetas? Com os laços, isso fica fácil!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Os laços podem ser utilizados dentro de outros laços. A isso chamamos de <b>laços aninhados</b>.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Usando laços, nossos programas ficam mais poderosos e podemos criar coisas divertidas com menos esforço! Prontos para começar?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
         ]}},


      licao9:{
        id:'CW2AULA09CODE',
        /** padroesCurriculares: 
        titulo:'Lição 09. Expressões Condicionais.',**/
        infografico:{titulo:'Expressão Condicional: Se, Senão, se senão',
        tituloSimplificado:'Expressão Condicional',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
         cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Já percebeu quantas decisões tomamos todos os dias? Decidir qual cor de camisa vestir, estudar antes de brincar, escolher entre vôlei ou futebol... Tudo isso depende de diferentes condições.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Muitas vezes as pessoas nos dão instruções usando condições. Por exemplo: <p><code><b>se</b> está chovendo <br/>&nbsp;&nbsp;&nbsp;então leve guarda-chuva<br/>&nbsp;&nbsp;&nbsp;<b>senão</b> não leve guarda-chuva</code> <br/><br/>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', //Mae orientando um filho a levar a guarda-chuva
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Essas condições nos ajudam a decidir o que fazer em diferentes situações. Por exemplo, no trânsito: <p><code><b>se</b> o sinal estiver vermelho <br/>&nbsp;&nbsp;&nbsp;então pare<br/><br/><b>se</b> o sinal estiver verde <br/>&nbsp;&nbsp;&nbsp;então prossiga</code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Condições não são úteis apenas para orientar humanos, mas também para programar computadores e componentes eletrônicos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpressoRecriado:'Condições não são úteis apenas para orientar humanos, mas também para programar computadores e componentes eletrônicos. Por exemplo, os sinais de carro e pedestre estão conectados eletronicamente para garantir que nunca tenham a mesma cor.',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Por exemplo, os semáforos de carro e pedestre estão conectados eletronicamente. Seus componentes eletrônicos garantem que os dois nunca tenham a mesma cor.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:0,
          imagemImpresso:0,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Em algoritmos, utilizamos os termos <b>Se</b>, <b>Então</b> e <b>Senão</b> para expressar condicionais que uma pessoa ou uma máquina deverão obedecer. A isso chamamos <b>expressão condicional</b>. Veja um exemplo: <p><code><b>se</b> sinal = vermelho <br/>&nbsp;&nbsp;&nbsp;então pare<br/><br/><b>se</b> sinal = verde <br/>&nbsp;&nbsp;&nbsp;então prossiga</code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Note que, para escrever essas condições, usamos sinais matemáticos, como <b>igual (=)</b>, <b>maior que (>)</b> e <b>menor que (<)</b>: <p><code><b>se</b> local atual = centro <br/>&nbsp;&nbsp;&nbsp;então pare <br/><b>se</b> velocidade do carro > 80 km <br/>&nbsp;&nbsp;&nbsp;então diminua a velocidade <br/><b>se</b> combustível do carro < 2 litros <br/>&nbsp;&nbsp;&nbsp;então coloque combustível</code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'E então? Estão prontos para praticar programação com condicionais?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
         ]}},


      licao10:{},


      licao11:{
        id:'CW2AULA11CODE',
        /** padroesCurriculares: 
        titulo:'Lição 11. Projeto Biga-Robô.',**/
        infografico:{titulo:'História das Carruagens',
        tituloSimplificado:'Carruagens',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[

          {ordem:1,
          predecessor:0,
          texto:'Por volta de 3500 a.C., na Ásia Central, os seres humanos começaram a domar cavalos selvagens.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Após domesticar os cavalos, antigos inventores perceberam que poderiam utilizar sua força para diferentes finalidades.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Cavalos eram usados na agricultura para ajudar a preparar a terra, puxando ferramentas chamadas arados, e faziam moinhos girarem para auxiliar nas tarefas diárias.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Os cavalos também eram usados em veículos, como carroças ou carruagens, para levar objetos ou pessoas de um lugar para outro.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},


          {ordem:5,
          predecessor:4,
          texto:'Alguns veículos, como a biga romana, eram utilizados em corridas emocionantes, que atraíam tanto o público quanto as corridas de Fórmula 1 atuais.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Hoje em dia, não precisamos mais de cavalos para puxar carruagens. Podemos usar robôs para fazer essa tarefa.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Que tal explorarmos a ideia de conectar um tipo de biga ao robô e criar uma biga-robô? Soltem a imaginação e vamos inventar nossas próprias bigas robotizadas!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
         ]}},


      licao12:{},


      licao13:{
        id:'CW2AULA13CODE',
        /** padroesCurriculares: 
        titulo:'Lição 13. Eventos.',**/
        infografico:{titulo:'Eventos',
        tituloSimplificado:'Eventos',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Você sabe o que é um evento? Um <b>evento</b> é um acontecimento ou ação que pode disparar uma rotina, provando reações em resposta.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Por exemplo, imagine que você está brincando e, de repente, seu gato pula na sua frente. Qual seria sua reação a esse evento?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Na computação, muitos eventos são provocados pelos usuários, que são as pessoas que usam o computador.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Um <b>evento de usuário</b> é disparado quando alguém clica com o mouse ou aperta uma tecla como o botão Enter, entre outras.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Os programadores escrevem códigos para que os computadores respondam a esses eventos, abrindo janelas ou movendo personagens em jogos, por exemplo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},


          {ordem:6,
          predecessor:5,
          texto:'Celulares, tablets e até relógios inteligentes são computadores móveis que permitem diversos tipos de eventos do usuário através de toque na tela ou do movimento do dispositivo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Alguns programas podem funcionar sozinhos, mas são raros. A maioria dos programas precisa de eventos para funcionar, como jogos ou aplicativos de redes sociais.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Eles respondem às nossas ações, tais como apertar uma tecla, clicar no mouse ou mexer um joystick.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:9,
          predecessor:8,
          texto:'Os celulares e tablets têm <b>sensores</b> que podem enviar informações que podem disparar <b>eventos independentes</b>, sem qualquer ação do usuário.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'',
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:10,
          predecessor:9,
          texto:'Os programadores podem usar esses sensores de diversas formas. Por exemplo, se o aparelho ficar muito quente, um programa pode mandar um aviso para desligá-lo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'',
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
        
         ]}},


      licao14:{
        d:'CSXAULA14CODE',
        /** padroesCurriculares: 
        titulo:'Lição 14. Materiais Condutores e Não Condutores de Eletricidade.',**/
        infografico:{titulo:'Materiais Condutores e Não Condutores de Eletricidade',
        tituloSimplificado:'Materiais Condutores de Eletricidade',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'As redes elétricas têm fios que levam a eletricidade das fontes de energia até nossas casas. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
          {ordem:2,
          predecessor:1,
          texto:'Os fios são feitos de materiais como cobre e alumínio, que são bons condutores de eletricidade. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Cabos e fios são cobertos por um material chamado isolante, como plástico ou borracha, para evitar acidentes. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Além dos metais, a água e os alimentos, como frutas, também podem conduzir eletricidade. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Os seres humanos também podem conduzir eletricidade e sentir choques elétricos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Em nosso curso, usamos circuitos elétricos com carga baixa, que não são perigosos. Por isso, nós podemos utilizá-los com segurança, sem risco de choques.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Conheça agora o Makey Makey, um aparelho eletrônico que nos permite usar materiais condutores para disparar eventos no computador. ', //Alvim: avaliar se vamos fazer menção ao Makey Makey ou usar nome genérico.
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Um cacho de banana ou uma gelatina podem se tornar um teclado ou um mouse. Vamos experimentar?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

         
         ]}},

    },

    unidade3:{
      titulo:'Inventos Robotizados e Computação Segura',
      descricao:'Nesta unidade, você aprenderá sobre sensores, compreendendo suas correspondências com os órgãos do sentido humano e programando inventos eletrônicos que utilizam sensores e outros dispositivos eletrônicos.<br/>Você também compreenderá o conceito de informação, aprendendo sobre a importância de adotar cuidados para navegar na internet com segurança e escolher senhas seguras para suas contas digitais.',
      
      licao15:{
        id:'CW2AULA15CODE',
        /** padroesCurriculares: 
        titulo:'Lição 15. Geração e Distribuição de Energia.',**/
        infografico:{titulo:'Geração e Distribuição de Energia',
        tituloSimplificado:'Geração de Energia',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'A energia que movimenta nosso planeta vem do calor do sol, da força dos mares e do calor do centro da Terra, dando vida e movimento.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Com o tempo, nós também aprender a gerar energia elétrica para alimentar aparelhos diversos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
          {ordem:3,
          predecessor:2,
          texto:'Mas como a energia elétrica chega às nossas casas? A água gira turbinas em usinas hidroelétricas, que transformam esse movimento em eletricidade.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:4,
          predecessor:3,
          texto:'A eletricidade é transmitida através dos fios e postes da rede elétrica, que levam a energia até nossas casas, fazendas e fábricas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:5,
          predecessor:4,
          texto:'Quando queremos utilizar essa energia, basta conectar um aparelho à tomada.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:6,
          predecessor:5,
          texto:'Além das hidrelétricas, também conseguimos produzir energia com a luz do sol, o vento, o movimento das marés, combustíveis como a gasolina, o carvão, entre outros.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:7,
          predecessor:6,
          texto:'Que tal aprender mais sobre a geração da energia, conectando componentes virtuais que simulam sua distribuição? Estão prontos?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
              
        
         ]}},
      
      
      licao16:{
        id:'CW2AULA16CODE',
        /** padroesCurriculares: 
        titulo:'Lição 16. Sensores e os Órgãos do Sentido.',**/
        infografico:{titulo:'Sensores e os Sentidos Humanos',
        tituloSimplificado:'Sensores',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Nós usamos nossos olhos, ouvidos, boca, nariz e pele para perceber o mundo ao nosso redor. Essas são nossas partes do corpo que nos ajudam a sentir e descobrir coisas! ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
          {ordem:2,
          predecessor:1,
          texto:'O cérebro também é muito importante, pois ele recebe as informações dos nossos sentidos e nos ajuda a entender o que está acontecendo à nossa volta.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Assim como nós, robôs e aparelhos eletrônicos também podem ter "olhos" e "ouvidos"! Sensores são como nossos órgãos, que pegam informações do mundo ao redor e as enviam para os computadores, celulares ou robôs.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Os sensores de som são como orelhas eletrônicas! Eles pegam os sons do ambiente e os transformam em sinais que os computadores entendem. Um exemplo disso é o microfone, como aquele que usamos para gravar voz ou som.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Sabe as câmeras e filmadoras? Elas são como os olhos que capturam imagens, gravando fotos e vídeos!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Quando alguém encosta no nosso braço, o nosso cérebro sente o toque e reage. Da mesma forma, quando tocamos na tela do celular, o "cérebro" dele, que é o processador, decide o que fazer, como abrir um jogo ou um aplicativo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Assim como nossa pele sente calor ou frio, sensores especiais em prédios podem evitar incêndios ou controlar a temperatura, ligando o ar-condicionado, por exemplo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Existem até sensores que podem sentir cheiros ou gostos! Mas são muito caros e pouco usados.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:9,
          predecessor:8,
          texto:'Os robôs e eletrônicos têm sensores incríveis! Alguns podem ver luzes que nós não conseguimos enxergar ou ouvir sons que nós não conseguimos. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:10,
          predecessor:9,
          texto:'Existem muitos tipos diferentes de sensores. Podemos usá-los para inventar muitos dispositivos criativos. Que tal começarmos a experimentá-los já? ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
              
          ]}},
           


      licao17:{
        id:'CW2AULA17CODE',
        /** padroesCurriculares: 
        titulo:'Lição 17. Projeto Carro Robotizados.',**/
        infografico:{titulo:'O Carro: Passado e Futuro',
        tituloSimplificado:'O Carro',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Hoje, você vai descobrir como é divertido programar computadores e montar circuitos elétricos. Estes serão seus primeiros passos na ciência da computação.',
          urlAudioTexto:'https://storage.googleapis.com/mindmakers/cpsciaudioinf/csx_i1_1.mp3',
          textoSimplificado:'Primeiros passos',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CSX/DispComp/img_1_new.jpg',
          promptImagem:'Digital art illustration of a teenager with wide, excited eyes, sitting at her desk in front of her laptop. On one side, she is coding with bright, vibrant colors emanating from the screen, and on the other, she is tinkering with basic electrical circuits. This scene captures the joy and excitement of taking the first steps in computer science and discovering the fun in programming and electrical assembly', 
          imagemFonte:'bing',
          textoDescritivoImagem:'Programador em frente ao computador',},
        
         ]}},


      licao18:{},


      licao19:{
        id:'CW2AULA19CODE',
        /** padroesCurriculares: 
        titulo:'Lição 19. Programação em Par e Depuração.',**/
        infografico:{titulo:'Programação em Par e Depuração',
        tituloSimplificado:'Depuração',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          //texto: 'Vocês já ouviram o ditado que duas cabeças pensam melhor que uma? Muitas vezes, podemos resolver problemas difíceis mais facilmente quando trabalhamos em par.',
          texto:'<b>Programação em par</b> é quando duas pessoas trabalham juntas para escrever um programa de computador.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          {ordem:1,
            predecessor:0,
            //texto: 'Vocês já ouviram o ditado que duas cabeças pensam melhor que uma? Muitas vezes, podemos resolver problemas difíceis mais facilmente quando trabalhamos em par.',
            texto:'Muitas vezes, podemos resolver problemas difíceis mais facilmente quando trabalhamos em dupla.',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},
          
            
          {ordem:3,
          predecessor:2,
          texto:'Quando duas pessoas programam em par, uma digita e a outra procura <b>bugs</b>, ou seja, erros, antes mesmo de executar o programa. É como ajudar um amigo em um jogo, observando inimigos se aproximando.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:4,
          predecessor:3,
          texto:'Quando estamos programando em par existem dois papeis, o de "piloto" e o "copiloto". O piloto é quem comanda a programação, enquanto o copiloto debuga, ou seja quem depura o programa.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Depuração é o processo de encontrar e corrigir erros em um programa de computador, ou seja, resolver os bugs.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:6,
          predecessor:5,
          texto:'Siga essa dica importante: o piloto e o copiloto devem revesar suas funções para não ficarem cansados. Dessa forma sua dupla fará programas de alta qualidade, com menos bugs.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
         
          
          {ordem:7,
          predecessor:6,
          texto:'Então, lembrem-se, trabalhe em par para fazer bem feito! Prepare-se para trabalhar com um colega, revesando entre os papéis de piloto e copiloto.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},        
        
         ]}},


      licao20:{},


      licao21:{},	

    },

    unidade4:{
      titulo:'Animação e Computação Criativa',
      descricao:'Nesta unidade, você será introduzido ao universo da animação, explorando desde os primórdios das animações manuais até o desenvolvimento das animações digitais.<br/>Você aprenderá a programar suas próprias animações digitais, utilizando um laboratório para criar histórias e soltar sua criatividade, aplicando os fundamentos de programação aprendidos neste módulo.',
      licao22:{
        id:'CW2AULA22CODE',
        /** padroesCurriculares: 
        titulo:'Lição 22. Os Primórdios da Animação.',**/
        infografico:{titulo:'Animações do Analógico ao Digital',
        tituloSimplificado:'Animações',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Há muito tempo, na época dos homens das cavernas, foram feitas as primeiras tentativas de criar uma ilusão de movimento com desenhos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Os homens pré-históricos desenhavam animais com patas que se sobrepunham. Quando alguém passava uma tocha sobre o desenho na parede da caverna, parecia que os animais estavam se movimentando!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'No tempo dos faraós no Egito, as pessoas desenhavam figuras em paredes com poses muito próximas umas as outras, como histórias em quadrinhos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
            predecessor:3,
            texto:'A mais de 5.000 anos atrás, um artesão fez um vaso com alguns desenhos. Quando o vaso era girado, parecia que um alce estava pulando para alcançar folhas de árvore.',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},


          {ordem:5,
            predecessor:4,
            texto:'Há aproximadamente 150 anos, as pessoas começaram a fazer brinquedos de animação com papel, como o folioscópio, ou flip-book. É um bloco de papel com desenhos em sequência. Quando você passa as páginas rápido, parece que os desenhos estão se mexendo.',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:6,
            predecessor:5,
            texto:'O taumatrópio, um brinquedo popular no século 19, permitia ver duas imagens diferentes simultaneamente. Isso era possível ao colar dois desenhos em lados opostos de uma folha e girá-la rapidamente.',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},
            //Alvim: colocar séc XIX ou 19?
    
          
          {ordem:8,
            predecessor:7,
            texto:'Esses brinquedos de animação antigos continuaram a melhorar, resultando no zootrópio. Ele tinha um tambor circular com fendas onde você podia ver tiras de desenhos. Quando o tambor girava, os desenhos pareciam se mexer.',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},
          
          {ordem:9,
            predecessor:8,
            texto:'O zootrópio também inspirou as primeiras animações em 3D, usando bonecos posicionados de tal forma sobre um disco que, ao girar o disco, criava a ilusão de movimentação.',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:10,
            predecessor:9,
            texto:'Essas invenções nos permitiram descobrir algo muito importante: o movimento de animação que enxergamos é uma ilusão criada a partir de imagens paradas que são vistas rapidamente e o nosso cérebro as interpreta como objetos em movimento.',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:11,
            predecessor:10,
            texto:'Esse princípio é a base da animação moderna, incluindo os GIFs animados, que são arquivos com várias imagens paradas que são exibidas rapidamente.',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:12,
            predecessor:11,
            texto:'Vamos começar nossa jornada pela história da animação, desde seus primeiros passos até chegar ao mundo digital!',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},
        
         ]}},


      licao23:{},


      licao24:{},


      licao25:{},


      licao26:{
        id:'CW2AULA26CODE',
        /** padroesCurriculares: 
        titulo:'Lição 26. Introdução ao Laboratório de Histórias.',**/
        infografico:{titulo:'Introdução ao Story Lab',
        tituloSimplificado:'O Story Lab',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
          cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Desde muito tempo atrás, as pessoas contam histórias para se conectar umas com as outras. Nessas histórias as pessoas expressavam seus sonhos, medos e desejos, de acordo com as mais diferentes culturas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          //alvim: deixa cultura?

          {ordem:2,
          predecessor:1,
          texto:'A forma de contar histórias evoluiu com o tempo. Antes eram contadas em volta do fogo, depois com desenhos, livros, filmes e agora também com animações feitas por computador. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Com a programação, podemos fazer histórias animadas e interativas. Assim, quem está ouvindo pode fazer escolhas que mudam o final da história.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
            predecessor:3, 
            texto:'O "Story Lab" é um laboratório onde nós podemos criar histórias digitais. Para isso, escolha um título, prencha seu nome e faça uma breve descrição da história.',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},


          {ordem:5,
            predecessor:4,
            texto:'Nós podemos mudar o cenário, escolher diferentes imagens de fundo e mudar o tamanho das personagens e objetos. ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:6,
            predecessor:5,
            texto:'Podemos usar cores diferentes no cenário. Elas não servem apenas para decorar: as personagens podem interagir com elas durante a história. ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:7,
            predecessor:6,
            texto:'Devemos esolher as personagens e objetos que farão parte da história e os colocá-los no cenário. É possível mudar o nome, tamanho e outras características delas. ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},
          
          {ordem:8,
            predecessor:7,
            texto:'Alguns objetos têm movimentos pré-definidos. Somos capazes de escolher quando esses movimentos acontecem. Por exemplo, podemos:',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},
          
          {ordem:9,
            predecessor:8,
            texto:'1 - Decidir o que acontece quando as personagens encontram esses objetos. Elas caem? Mudam de cor? Fazem alguma animação? ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:10,
            predecessor:9,
            texto:'2 - Programar os movimentos das personagens. Elas podem andar, pular, cair, tudo o que você imaginar. ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:11,
            predecessor:10,
            texto:'Também podemos usar a seção "aparência" para programar a narração da história. O narrador conta as histórias enquanto as personagens as representam.',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:12,
            predecessor:11,
            texto:'Prontos para fazer suas histórias? Usem todos os comandos possíveis para contar uma história criativa e envolvente.',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},
        
         ]}},

      licao27:{
        id:'CW2AULA26CODE',
        /** padroesCurriculares: 
        titulo:'Lição 27. Projeto Missão Criativa - Minha Primeira Animação Digital',**/
        infografico:{titulo:'Missão Criativa CW2: História em Quadrinho Animada',
        tituloSimplificado:'Missão CW2',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Nesta aula, vamos começar o quarto e último projeto deste módulo. Vamos animar uma história divertida, em que cada integrante do grupo ficará responsável por animar uma "cena da história".',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:1,
          predecessor:0,
          texto:'Para isso, vocês devem utilizar o Caderno de Criações para esboçar a história, antes de partir para a criação, no Story Lab.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          
          {ordem:2,
          predecessor:1,
          texto:'Vejam alguns exemplos para se inspirar, como os projetos criativos que mostraremos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Ah, vale lembrar que os projetos são autorais! Se inspirem nos exemplos, mas criem suas próprias histórias, dando asas à imaginação.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Prontos para começar? Vamos lá!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        //Alvim: inserir contexto mais lúdico ou mais direcionado?
           ]}},


      licao28:{},	

    },

    capaVerso:{
      urlImagemTerceiraCapa:'',
      textoTerceiraCapa: '',
      textoUltimaCapa: 'Charles Babbage foi um cientista, matemático, filósofo, engenheiro mecânico e inventor inglês que é mais conhecido como o inventor que projetou o primeiro computador de uso geral, utilizando apenas partes mecânicas, a máquina analítica.'
    },

}