let livro_cw2 ={

  /* metadados 2 */
  versao:'0.1.00',
  nomeFantasia: '',
  nomeTecnico:'CW2 - Fundamentos em Ciência da Computação 2',
  resumo:'Charles Babbage foi um cientista, matemático, filósofo, engenheiro mecânico e inventor inglês que é mais conhecido como o inventor que projetou o primeiro computador de uso geral, utilizando apenas partes mecânicas, a máquina analítica.',
  isbn:'',
  autores:[],
  editor:'',
  local:'',
  ano:'',
  url:'compsci_cw2_0_1',

  versaoAdaptacao:'',
  nomeAdaptacaoo: '',
  autoresAdaptacao:[],
  local:'',
  escola:'',
  ano:'',
  url:'',
  codigoCid11:'', /* opc */
  descritivoPerfilAluno:'',
  resumoAdaptacao:'',

  capa:{
		urlImagemCapa:'',
		urlImagemSegundaCapa: '',
  },
  
   formularioRegistro:{
	  titulo:'',
	  urlImagem:'',
	  campos:[
	   {rotulo:'Login Somos:',formato:'usuarioAcessivel'},{rotulo:'Senha:',formato:'senhaAcessivel'}
	  ]},
  
  visaogeral:{
	  infografico:{
		  titulo:'Resumo do Módulo CW2',
		  /* idem licoes */
	  }},

    /* conteudo */
    unidade1:{
      titulo:'Fundamentos de Programação',
      descricao:'Nesta unidade, você será apresentado ao computador, aos dispositivos eletrônicos e aos robôs, além de dar os primeiros passos em programação.<br/>Você começará a utilizar o pensamento computacional na resolução de desafios lógicos por meio de algoritmos.',
      licao1:{
        id:'CW2AULA01CODE',
        /** padroesCurriculares: 
        titulo:'Lição 01. Dispositivos Computacionais.',**/
        infografico:{titulo:'Computador e Dispositivos Computacionais',
        tituloSimplificado:'O Computador',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Hoje, nós vamos descobrir como é divertido programar computadores. Estes serão seus primeiros passos na ciência da computação.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Você já brincou com um computador ou celular? Eles são aparelhos eletrônicos e possuem diversas partes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'O computador de mesa, por exemplo, tem quatro partes: a torre, o teclado, o monitor e o mouse.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:`Na <b>torre</b> existem componentes como as memórias, onde o computador armazena dados. E o processor, que funciona como o "cérebro do computador".`,
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Com o <b>teclado</b> e o <b>mouse</b>, nós conseguimos digitar, mover e clicar em objetos exibidos na tela, chamada de <b>monitor</b>.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Podemos também conectar outros dispositivos ao computador, como caixas de som ou impressoras.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Celulares e tablets também são computadores, embora pequenos, para caberem na palma das nossas mãos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Mas existem computadores ainda menores, embutidos dentro de carros, TVs e até mesmo brinquedos. Eles tornam estes aparelhos mais inteligentes e capazes de nos ajudar no dia a dia.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:9,
          predecessor:8,
          texto:'Mas, afinal, o que é um computador? É uma máquina que pode ser programada para nos ajudar nas mais variadas tarefas, seja no trabalho, na escola ou em momentos de lazer.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:10,
          predecessor:9,
          texto:'Neste curso, vamos aprender a criar jogos, inventos eletrônicos, a programar robôs e montar inventos. Tudo isso é <b>ciência da computação</b>!',
          urlAudioTexto:'https://storage.googleapis.com/mindmakers/cpsciaudioinf/csx_i1_1.mp3',
          textoSimplificado:'Primeiros passos',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CSX/DispComp/img_1_new.jpg',
          promptImagem:'', 
          imagemFonte:'bing',
          textoDescritivoImagem:'Programador em frente ao computador',},
        
         ]}},


      licao2:{},


      licao3:{
        id:'CW2AULA03CODE',
        /** padroesCurriculares: 
        titulo:'Lição 03. Eletricidade e Dispositivos Eletrônicos.',**/
        infografico:{titulo:'Explorando a Eletricidade e Seus Segredos!',
        tituloSimplificado:'Eletricidade',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'A <b>eletricidade</b> é um tipo de energia que chega em nossas casas por meio das chamadas <b>redes elétricas</b>, como podemos observar pelos grandes cabos e postes que vemos nas ruas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Em casa, usamos eletricidade para esquentar água, esfriar alimentos na geladeira e ligar aparelhos como lâmpadas, TVs e, é claro, os computadores e até robôs.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Computadores portáteis, robôs e outros aparelhos podem funcionar sem estarem conectados à tomada desde que possuam baterias.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'As <b>baterias</b> são componentes que armazenam energia por um tempo. Quando a energia acaba, recarregamos as baterias nas tomadas que trazem energia da rede elétrica.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Existem muitos tipos de aparelhos elétricos, usados para diversas atividades! Neste curso, vamos aprender não apenas a usar, mas também a fazer novos aparelhos para diferentes tarefas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
            
                  
          {ordem:6,
          predecessor:5,
          texto:'Todo aparelho eletrônico tem <b>componentes</b> importantes. Vamos aprender quais são os componentes principais antes de criarmos nossos próprios inventos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Os primeiros componentes são os <b>geradores</b>, que fornecem energia para os outros funcionarem.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Há também os <b>controladores</b>, que servem para controlar um ou mais componentes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:9,
          predecessor:8,
          texto:'Os <b>condutores</b> transmitem a energia de um componente para o outro.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:10,
          predecessor:9,
          texto:'Por fim, os <b>conversores</b> transformam a energia elétrica em luz ou movimento e realizam as funções principais de cada aparelho eletrônico.', // originalmente o nome desses componentes é aparelhos. Validar com Alvim.
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:11,
          predecessor:10,
          texto:'Juntando esses quatro tipos de componentes, poderemos criar nossos próprios inventos e explorar os mistérios da eletricidade.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpressoRecriado:'Juntando esses quatro tipos de componentes, poderemos criar nossos próprios inventos e explorar os mistérios da eletricidade. A diversão e o aprendizado estão prestes a começar!',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:12,
          predecessor:11,
          texto:'A diversão e o aprendizado estão prestes a começar!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:0,
          imagemImpresso:0,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
         ]}},


      licao4:{
        id:'CW2AULA04CODE',
        /** padroesCurriculares: 
        titulo:'Lição 04. Algoritmo, Identificação de Padrão e Sequência.',**/
        infografico:{titulo:'Algoritmos no Nosso Dia a Dia',
        tituloSimplificado:'Algoritmos',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Um <b>algoritmo</b> é como uma receita que explica a uma pessoa ou máquina, passo a passo, como realizar uma tarefa de modo correto.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'r',},

          {ordem:2,
          predecessor:1,
          texto:'Algumas vezes, os algoritmos são representados por figuras ou símbolos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Outras vezes, podemos chamá-los de <b>diagramas</b>, que são desenhos com formas ligadas por linhas, onde cada forma representa um passo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Algoritmos podem ser escritos como uma lista numerada de passos para realizar uma tarefa simples.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Alguns algoritmos são muito grandes e complicados, como aqueles que ajudam astronautas a resolver problemas no espaço.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'No mundo computacional, os chamados <b>programas de computador</b> também são algoritmos, escritos em uma linguagem que o computador entende.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Um bom algoritmo é importante para que uma tarefa seja realizada de modo perfeito, seja por uma pessoa ou máquina.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Por isso, neste curso, vamos aprender algoritmos na prática, colocando a "mão na massa"!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          ]}},

      licao5:{
        id:'CW2AULA05CODE',
        /** padroesCurriculares: 
        titulo:'Lição 05. Robótica.',**/
        infografico:{titulo:'Robótica com o Robô Esfera',
        tituloSimplificado:'Robô Esfera',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[

          {ordem:1,
          predecessor:0,
          texto:'Um <b>robô</b> é uma máquina programável que executa tarefas automaticamente.', 
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Nós já vimos robôs em filmes e jogos... Eles podem ter pernas, rodas ou parecer com humanos. Mas vocês sabem como eles surgiram?', //Conferir com Alvim: frases para engajamento serão no plural (como está nessa frase) ou no singular?
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Os robôs têm origens nos autômatos, antigos bonecos que se moviam sozinhos, realizando movimentos simples.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Antigamente, para mudar algum movimento de um autômato, os inventores precisavam reconstruir suas partes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Já os robôs modernos possuem um computador como "cérebro". Por isso, basta alterar programas para modificar seus movimentos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Existem muitos tipos de robôs, utilizados para várias finalidades. Por exemplo, robôs industriais fazem tarefas como montar carros ou empacotar produtos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'E robôs cirúrgicos auxiliam os médicos a operar pacientes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},


          {ordem:8,
          predecessor:7,
          texto:'Já os robôs exploradores são capazes de se mover em locais perigosos e até em outros planetas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:9,
          predecessor:8,
          texto:'No nosso curso, vamos programar diferentes robôs, começando com um robô esfera, que se move como o BB-8 de Star Wars.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:10,
          predecessor:9,
          texto:'Podemos programar o robô esfera para se mover em diferentes velocidades e direções, mudar de cor, e muito mais.<p>Bem-vindo ao mundo dos robôs!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
         
        
         ]}},


        licao6:{
        id:'CW2AULA06CODE',
        /** padroesCurriculares: 
        titulo:'Lição 06. Projeto Taxibot.',**/
        infografico:{titulo:'Taxibot: Taxiamento Robotizado',
        tituloSimplificado:'Taxibot',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Você sabia que os aviões são o meio de transporte mais rápido e seguro do mundo?', //Verificar com Alvim: usar plural ou singular na pergunta inicial?
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Eles foram inventados por um brasileiro chamado Santos Dumont!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Com suas grandes asas e turbinas poderosas, os aviões são feitos para voar, não para andar.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Quando os aviões se movem no chão, chamamos de taxiamento. Ou seja: é quando vão dos portões até a pista e vice-versa.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Mas usar turbinas para taxiamento gasta muito combustível e faz muito barulho.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Será que existe uma maneira melhor de mover os aviões no solo? Para resolver isso, foi desenvolvido o Taxibot!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'O Taxibot é um veículo meio robotizado, controlado por humanos, capaz de realizar muitas tarefas de forma automática.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Com mais segurança, menos combustível e menos barulho, o Taxibot leva os aviões entre portões e pista sem ligar as turbinas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:9,
          predecessor:8,
          texto:'Mas sempre podemos melhorar! Que tal criar um taxibot totalmente robotizado que funcione só com programação? Usem a criatividade!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
          ]}},


      licao7:{},	

    },


    unidade2:{
      titulo:'Condicionais, Robótica e Eventos Computacionais',
      descricao:'Nesta unidade, você aprenderá os conceitos de laços e expressões condicionais, utilizando-os para resolver desafios lógicos de programação e programar robôs.<br/>Você também aprenderá o conceito de programação orientada a eventos e usará um dispositivo eletrônico para criar seu próprio controle criativo de videogame, utilizando materiais diversos, como massinha ou lápis!',
      licao8:{
        id:'CW2AULA08CODE',
        /** padroesCurriculares: 
        titulo:'Lição 08. Laços.',**/
        infografico:{titulo:'Laço em Algoritmos',
        tituloSimplificado:'Laço',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Hoje, vamos aprender sobre um comando poderoso nos algoritmos: os <b>laços</b>, também conhecidos como <b>loops</b>, em inglês.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Os laços permitem que o computador repita comandos várias vezes sem que tenhamos que escrevê-los de novo e de novo no algoritmo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Usando laços, podemos fazer coisas impressionantes com poucos comandos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Por exemplo, ao criar um algoritmo para um robô industrial, podemos usar laços para instruir a repetição de atividades, como cortar, separar e parafusar peças.', //para um atleta, poderíamos usar laços para instruir a repetição de atividades, como pular e girar várias vezes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Um algoritmo para um jogo de corrida pode usar um laço para fazer um carro dar 76 voltas na pista.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Já imaginou criar um programa para um jogo onde um personagem caminha enquanto dá várias piruetas? Com os laços, isso fica fácil!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Os laços podem ser usados dentro de outros laços, e isso é chamado de <b>laços aninhados</b>.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Usando laços, nossos programas ficam mais poderosos e podemos criar coisas divertidas com menos esforço! Prontos para começar?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
         ]}},


      licao9:{
        id:'CW2AULA09CODE',
        /** padroesCurriculares: 
        titulo:'Lição 09. Expressões Condicionais.',**/
        infografico:{titulo:'Expressão Condicional: Se, Senão, se senão',
        tituloSimplificado:'Expressão Condicional',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
         cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Já percebeu quantas decisões tomamos todos os dias? Decidir qual cor de camisa vestir, estudar antes de brincar, escolher entre vôlei ou futebol – tudo é uma decisão baseada em diferentes condições.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Por exemplo: <p><code><b>se</b> está chovendo <br/>&nbsp;&nbsp;&nbsp;então leve guarda-chuva<br/>&nbsp;&nbsp;&nbsp;<b>senão</b> não leve guarda-chuva</code> <br/><br/>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Essas condições ajudam a decidir o que fazer em diferentes situações. Por exemplo, no trânsito: <p><code><b>se</b> o sinal estiver vermelho <br/>&nbsp;&nbsp;&nbsp;então pare<br/><br/><b>se</b> sinal o sinal estiver verde <br/>&nbsp;&nbsp;&nbsp;então prossiga</code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Condições não são úteis apenas para decisões humanas, mas também em algoritmos para programas de computador e componentes eletrônicos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpressoRecriado:'Condições não são úteis apenas para decisões humanas, mas também em algoritmos para programas de computador e componentes eletrônicos. Por exemplo, os sinais de carro e pedestre estão conectados eletronicamente para garantir que nunca tenham a mesma cor.',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Por exemplo, os semáforos de carro e pedestre estão conectados eletronicamente para garantir que nunca tenham a mesma cor.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:0,
          imagemImpresso:0,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Em algoritmos, usamos as <b>expressões condicionais</b> Se, Então e Senão para a tomada de decisões. Veja: <p><code><b>se</b> sinal = vermelho <br/>&nbsp;&nbsp;&nbsp;então pare<br/><br/><b>se</b> sinal = verde <br/>&nbsp;&nbsp;&nbsp;então prossiga</code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Para escrever essas condições, usamos sinais matemáticos, como <b>igual (=)</b>, <b>maior que (>)</b> e <b>menor que (<)</b>: <p><code><b>se</b> local atual = centro <br/>&nbsp;&nbsp;&nbsp;então pare <br/><b>se</b> velocidade do carro > 80 km <br/>&nbsp;&nbsp;&nbsp;então diminua a velocidade <br/><b>se</b> combustível do carro < 2 litros <br/>&nbsp;&nbsp;&nbsp;então coloque combustível</code>',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'E aí? Vocês estão prontos para praticar a programação com condicionais?', //Verificar com Alvim: plural ou singular?
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
         ]}},


      licao10:{},


      licao11:{
        id:'CW2AULA11CODE',
        /** padroesCurriculares: 
        titulo:'Lição 11. Projeto Biga-Robô.',**/
        infografico:{titulo:'História das Carruagens',
        tituloSimplificado:'Carruagens',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[

          {ordem:1,
          predecessor:0,
          texto:'Por volta de 3500 a.C., na Ásia Central, os seres humanos começaram a domar cavalos selvagens.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Após domesticar os cavalos, antigos inventores perceberam que poderiam utilizar sua força para diferentes finalidades.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Cavalos eram usados na agricultura para ajudar a preparar a terra, puxando ferramentas chamadas arados, e faziam moinhos girarem para auxiliar nas tarefas diárias.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Os cavalos também eram usados em veículos, como carroças ou carruagens, para levar objetos ou pessoas de um lugar para outro.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},


          {ordem:5,
          predecessor:4,
          texto:'Alguns veículos, como a biga romana, eram utilizados em corridas emocionantes, que atraíam tanto o público quanto as corridas de Fórmula 1 atuais.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Hoje em dia, não precisamos mais de cavalos para puxar carruagens. Podemos usar robôs para fazer essa tarefa.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Que tal explorarmos a ideia de conectar um tipo de biga ao robô e criar uma biga-robô? Soltem a imaginação e vamos inventar nossas próprias bigas robotizadas!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
         ]}},


      licao12:{},


      licao13:{
        id:'CW2AULA13CODE',
        /** padroesCurriculares: 
        titulo:'Lição 13. Eventos.',**/
        infografico:{titulo:'Eventos',
        tituloSimplificado:'Eventos',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Você conhece o que é um evento? São coisas que acontecem de surpresa ou de vez em quando. Não são coisas que acontecem todos os dias na mesma hora.',
          urlAudioTexto:'',
          textoSimplificado:'Primeiros passos',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Um evento é quando algo diferente acontece e pode mudar o que estamos fazendo, nos fazendo reagir de uma maneira diferente. Por exemplo, imagine que você está estudando quietinho e, de repente, seu gato pula na mesa. O que você faria?',
          urlAudioTexto:'',
          textoSimplificado:'Primeiros passos',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Na computação, as pessoas fazem coisas no computador, como clicar com o mouse ou apertar o botão Enter. Os programadores escrevem códigos para fazer o computador responder a essas ações, como abrir janelas ou mover personagens em jogos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Telefones, tablets e até relógios inteligentes são computadores que podemos levar com a gente e nos ajudam a fazer muitas coisas divertidas. Podemos tocá-los na tela ou movê-los para fazer coisas diferentes.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:' Alguns programas podem funcionar sozinhos, mas são raros. A maioria dos programas precisa de eventos para funcionar, como jogos ou aplicativos de redes sociais. Eles respondem quando a gente faz alguma coisa, como apertar uma tecla, clicar no mouse ou mexer num joystick.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:' Os celulares e tablets têm sensores que podem fazer coisas sozinhos, sem a gente tocar neles. Os programadores podem usar esses sensores de jeitos legais. Por exemplo, se o aparelho ficar muito quente, um programa pode mandar um aviso para a gente esfriá-lo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,imagemImpresso:1,
          urlImagem:'',
          promptImagem:'',
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
        
         ]}},


      licao14:{
        d:'CSXAULA14CODE',
        /** padroesCurriculares: 
        titulo:'Lição 14. Materiais Condutores e Não Condutores de Eletricidade.',**/
        infografico:{titulo:'Materiais Condutores e Não Condutores de Eletricidade',
        tituloSimplificado:'Materiais Condutores de Eletricidade',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'As redes elétricas têm fios que levam a eletricidade das fontes de energia até nossas casas. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
          {ordem:2,
          predecessor:1,
          texto:'Os fios são feitos de materiais como cobre e alumínio, que são bons condutores de eletricidade. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Cabos e fios são cobertos por um material chamado isolante, como plástico ou borracha, para evitar acidentes. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Além dos metais, a água e os materiais orgânicos, como frutas, também podem conduzir eletricidade. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Os seres humanos também podem conduzir eletricidade e sentir choques elétricos. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Em nosso curso, usamos circuitos elétricos com carga baixa, que não são perigosos. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Vamos experimentar? Com o Makey Makey, podemos usar materiais condutores para criar dispositivos criativos para computadores. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Um cacho de banana ou uma gelatina podem se tornar teclado ou mouse. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

         
         ]}},

    },

    unidade3:{
      titulo:'Inventos Robotizados e Computação Segura',
      descricao:'Nesta unidade, você aprenderá sobre sensores, compreendendo suas correspondências com os órgãos do sentido humano e programando inventos eletrônicos que utilizam sensores e outros dispositivos eletrônicos.<br/>Você também compreenderá o conceito de informação, aprendendo sobre a importância de adotar cuidados para navegar na internet com segurança e escolher senhas seguras para suas contas digitais.',
      
      licao15:{
        id:'CW2AULA15CODE',
        /** padroesCurriculares: 
        titulo:'Lição 15. Geração e Distribuição de Energia.',**/
        infografico:{titulo:'Geração e Distribuição de Energia',
        tituloSimplificado:'Geração de Energia',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'A energia que movimenta nosso planeta vem do calor do sol, da força dos mares e do calor do centro da Terra, dando vida e movimento.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Com o tempo, aprendemos a controlar várias formas de energia, como a elétrica, vista nos raios. Circuitos elétricos podem ser energizados por baterias ou pilhas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
          {ordem:3,
          predecessor:2,
          texto:'Mas como a energia elétrica chega às nossas casas? Máquinas transformam energias naturais, como em usinas hidroelétricas, onde a força da água gira turbinas, gerando eletricidade.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:4,
          predecessor:3,
          texto:'Essa eletricidade viaja por grandes fios, conhecidos como rede elétrica, distribuindo-se para nossas casas, fazendas e fábricas.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:5,
          predecessor:4,
          texto:'Quando queremos utilizar essa energia, basta conectar um aparelho à tomada.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:6,
          predecessor:5,
          texto:'Além das hidrelétricas, também conseguimos captar energia do calor, como ao queimarmos vegetais, e até mesmo da quebra de minúsculas partes que compõem a matéria, chamadas átomos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:7,
          predecessor:6,
          texto:'Compreender a história da geração de energia é incrível! Que tal praticar, concetando componentes eletrônicos que simulam essa distribuição? Estão prontos?',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
              
        
         ]}},
      
      
      licao16:{
        id:'CW2AULA16CODE',
        /** padroesCurriculares: 
        titulo:'Lição 16. Sensores e os Órgãos do Sentido.',**/
        infografico:{titulo:'Sensores e os Sentidos Humanos',
        tituloSimplificado:'Sensores',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Nós usamos nossos olhos, ouvidos, boca, nariz e pele para entender e brincar com o mundo à nossa volta. Essas são nossas partes do corpo que nos ajudam a sentir e descobrir coisas! ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
          {ordem:2,
          predecessor:1,
          texto:'Além dos nossos órgãos sensoriais, o cérebro também é muito importante. Ele recebe as informações dos nossos sentidos e nos ajuda a entender o que está acontecendo à nossa volta.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Assim como nós, robôs e coisas eletrônicas também podem ter "olhos" e "ouvidos"! Esses "sensores" são como seus órgãos, eles pegam informações do mundo ao redor e as enviam para os computadores, celulares ou robôs.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Os sensores de som são como orelhas eletrônicas! Eles pegam os sons do ambiente e os transformam em sinais que os computadores entendem. Um exemplo disso é o microfone, como aquele que usamos para gravar voz ou som.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Sabe as câmeras e filmadoras? Elas têm olhos mágicos que capturam fotos e vídeos! Esses "sensores de luz" são como os olhos humanos, transformando a luz em sinais que os aparelhos entendem.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:6,
          predecessor:5,
          texto:'Quando alguém toca em nosso braço, nosso cérebro sabe e responde. Da mesma forma, quando tocamos a tela do celular, o cérebro dele, o processador, decide o que fazer, como abrir um jogo ou um aplicativo.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:7,
          predecessor:6,
          texto:'Assim como nossa pele sente calor ou frio, sensores especiais em prédios podem evitar incêndios e controlar a temperatura, ligando o ar-condicionado quando precisamos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:8,
          predecessor:7,
          texto:'Existem até sensores que podem sentir cheiros ou gostos! Mas são bem caros e não são usados tanto assim.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:9,
          predecessor:8,
          texto:'Os robôs e eletrônicos têm sensores incríveis! Alguns podem ver luzes que não podemos e ouvir sons que estão longe demais para nós. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:10,
          predecessor:9,
          texto:'Existem muitos tipos diferentes de sensores legais por aí! Podemos usá-los para criar robôs e dispositivos super legais. Que tal começarmos a experimentar com eles? ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
              
          ]}},
           


      licao17:{
        id:'CW2AULA17CODE',
        /** padroesCurriculares: 
        titulo:'Lição 17. Projeto Carro Robotizados.',**/
        infografico:{titulo:'O Carro: Passado e Futuro',
        tituloSimplificado:'O Carro',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Hoje, você vai descobrir como é divertido programar computadores e montar circuitos elétricos. Estes serão seus primeiros passos na ciência da computação.',
          urlAudioTexto:'https://storage.googleapis.com/mindmakers/cpsciaudioinf/csx_i1_1.mp3',
          textoSimplificado:'Primeiros passos',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CSX/DispComp/img_1_new.jpg',
          promptImagem:'Digital art illustration of a teenager with wide, excited eyes, sitting at her desk in front of her laptop. On one side, she is coding with bright, vibrant colors emanating from the screen, and on the other, she is tinkering with basic electrical circuits. This scene captures the joy and excitement of taking the first steps in computer science and discovering the fun in programming and electrical assembly', 
          imagemFonte:'bing',
          textoDescritivoImagem:'Programador em frente ao computador',},
        
         ]}},


      licao18:{},


      licao19:{
        id:'CW2AULA19CODE',
        /** padroesCurriculares: 
        titulo:'Lição 19. Programação em Par e Depuração.',**/
        infografico:{titulo:'Programação em Par e Depuração',
        tituloSimplificado:'Depuração',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Trabalhar em par significa programar com um amigo. Isso é ótimo porque duas cabeças pensam melhor que uma. Juntas, podemos resolver problemas difíceis mais facilmente.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Programar em par ajuda a encontrar bugs, que são como erros em um programa.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
          {ordem:3,
          predecessor:2,
          texto:'Quando duas pessoas trabalham juntas, uma digita, e a outra procura erros antes mesmo de o programa rodar. É como ajudar um amigo em um jogo, observando inimigos se aproximando.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:4,
          predecessor:3,
          texto:'Sigam algumas dicas importantes para programar em par: o que digita é o "piloto" e o que procura erros é o "navegador".',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:5,
          predecessor:4,
          texto:'Além disso, ambos devem se revezar para não ficarem cansados.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:6,
          predecessor:5,
          texto:'Seguindo essas dicas, sua dupla fará programas de alta qualidade, com menos bugs.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:7,
          predecessor:6,
          texto:'Programar em par é melhor porque dois programadores juntos fazem programas com menos erros e de alta qualidade.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
          
          {ordem:8,
          predecessor:7,
          texto:'Então, lembrem-se, trabalhe em par para fazer bem feito!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},        
        
         ]}},


      licao20:{},


      licao21:{},	

    },

    unidade4:{
      titulo:'Animação e Computação Criativa',
      descricao:'Nesta unidade, você será introduzido ao universo da animação, explorando desde os primórdios das animações manuais até o desenvolvimento das animações digitais.<br/>Você aprenderá a programar suas próprias animações digitais, utilizando um laboratório para criar histórias e soltar sua criatividade, aplicando os fundamentos de programação aprendidos neste módulo.',
      licao22:{
        id:'CW2AULA22CODE',
        /** padroesCurriculares: 
        titulo:'Lição 22. Os Primórdios da Animação.',**/
        infografico:{titulo:'Animações do Analógico ao Digital',
        tituloSimplificado:'Animações',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Há muito tempo, lá na época dos homens das cavernas, eles tentavam fazer desenhos que parecessem se mexer, como mágica!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Eles desenhavam animais com patas que se sobrepunham. Quando alguém passava uma tocha sobre o desenho na parede da caverna, parecia que os animais estavam se mexendo!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'No tempo dos faraós no Egito, as pessoas desenhavam figuras em paredes que pareciam se mexer! Era como assistir a uma história em quadrinhos ganhando vida!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
            predecessor:3,
            texto:'Há muito tempo, mais de 5.000 anos atrás, um artesão fez um vaso com desenhos. Quando o vaso era girado, parecia que um alce estava pulando para alcançar folhas de árvore!',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},


          {ordem:5,
            predecessor:4,
            texto:'Há aproximadamente 150 anos, as pessoas começaram a fazer brinquedos de animação com papel, como o folioscópio, ou flip-book. É um bloco de papel com desenhos em sequência. Quando você passa as páginas rápido, parece que os desenhos estão se mexendo!',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:6,
            predecessor:5,
            texto:'O taumatrópio foi um brinquedo muito famoso no século XIX. Com ele, você podia ver duas imagens diferentes ao mesmo tempo, como um pássaro dentro de uma gaiola ou uma princesa beijando um príncipe!',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:7,
            predecessor:6,
            texto:'O fenaquistiscópio usava um disco giratório com desenhos do mesmo objeto em posições diferentes. Girando o disco na frente de um espelho, os desenhos pareciam se mover!',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},
          
          {ordem:8,
            predecessor:7,
            texto:'Esses brinquedos de animação antigos continuaram a melhorar, resultando no zootrópio. Ele tinha um tambor circular com fendas onde você podia ver tiras de desenhos. Quando o tambor girava, os desenhos pareciam se mexer!',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},
          
          {ordem:9,
            predecessor:8,
            texto:'O zootrópio também inspirou as primeiras animações em 3D, trocando os desenhos por bonecos!',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:10,
            predecessor:9,
            texto:'Essas invenções mostraram algo muito importante: o movimento que vemos é uma ilusão feita mostrando imagens paradas uma depois da outra para o nosso cérebro!',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:11,
            predecessor:10,
            texto:'Esse princípio é a base da animação moderna, até mesmo das digitais, como os GIFs animados. Os GIFs são arquivos com várias imagens, mostradas rapidamente uma após a outra para parecer que estão se movendo, como em um vídeo.',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:12,
            predecessor:11,
            texto:'Vamos começar nossa jornada pela história da animação, desde seus primeiros passos até chegar ao mundo digital!',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},
        
         ]}},


      licao23:{},


      licao24:{},


      licao25:{},


      licao26:{
        id:'CW2AULA26CODE',
        /** padroesCurriculares: 
        titulo:'Lição 26. Introdução ao Laboratório de Histórias.',**/
        infografico:{titulo:'Introdução ao Story Lab',
        tituloSimplificado:'O Story Lab',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
          cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Desde muito tempo atrás, as pessoas contam histórias para se conectar umas com as outras. As histórias mostram sonhos, medos e coisas que as pessoas querem, mostrando diferentes lugares e culturas. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'As histórias mudaram com o tempo. Antes eram contadas em volta do fogo, depois com desenhos, livros, filmes e agora também com animações feitas por computador. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Com a programação, podemos fazer histórias animadas e interativas. Assim, quem está ouvindo pode fazer escolhas que mudam o final da história. ',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
            predecessor:3, 
            texto:'O "Story Lab" é um lugar onde você pode criar histórias animadas e interativas. Comece escolhendo um título, seu nome e uma breve descrição da história. ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},


          {ordem:5,
            predecessor:4,
            texto:'Você pode mudar o cenário da história, escolhendo diferentes imagens de fundo e mudando o tamanho dos personagens e objetos. ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:6,
            predecessor:5,
            texto:'Use cores diferentes no cenário. Elas não são só para decorar; os personagens podem reagir a elas durante a história. ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:7,
            predecessor:6,
            texto:'Escolha os personagens e objetos que você quer na sua história e os coloque no cenário. Você pode mudar o nome, tamanho e outras coisas sobre eles. ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},
          
          {ordem:8,
            predecessor:7,
            texto:'Alguns objetos têm movimentos pré-definidos. Você pode escolher quando esses movimentos acontecem. ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},
          
          {ordem:9,
            predecessor:8,
            texto:'Decida o que acontece quando os personagens encontram esses objetos. Eles caem? Mudam de cor? Fazem alguma animação? ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:10,
            predecessor:9,
            texto:'Programe os movimentos dos personagens. Eles podem andar, pular, cair, tudo o que você imaginar. ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:11,
            predecessor:10,
            texto:'Use a seção "aparência" para programar a narração da história. Alguém pode narrar a história enquanto os personagens se movem. ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},

          {ordem:12,
            predecessor:11,
            texto:'Faça a história interativa usando comandos especiais. Assim, ela pode mudar dependendo do que quem está assistindo faz. ',
            urlAudioTexto:'',
            textoSimplificado:'',
            textoImpresso:1,
            imagemImpresso:1,
            urlImagem:'',
            promptImagem:'', 
            imagemFonte:'',
            textoDescritivoImagem:'',},
        
         ]}},

      licao27:{
        id:'CW2AULA26CODE',
        /** padroesCurriculares: 
        titulo:'Lição 27. Projeto Missão Criativa - Minha Primeira Animação Digital',**/
        infografico:{titulo:'Missão Criativa CW2: História em Quadrinho Animada',
        tituloSimplificado:'Missão CW2',
        estiloPadrao:'basicoPaisagem',
        /** urlVideo:'',
        urlPodcast:'', **/
        cenas:[
          {ordem:1,
          predecessor:0,
          texto:'Nesta aula, vamos começar o quarto e último projeto deste módulo. Vamos animar uma história divertida ou engraçada, em que cada integrante do grupo ficará responsável por animar uma "cena da estória".',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:1,
          predecessor:0,
          texto:'Para isso, vocês devem utilizar o Caderno de Criações para esboçar a estória, antes de partir para a criação, no Story Lab.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:2,
          predecessor:1,
          texto:'Confiram os critérios de avaliação na TV da Sala e lembrem-se: os projetos serão avaliados com base nesses critérios.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:3,
          predecessor:2,
          texto:'Vejam alguns exemplos para se inspirar, como as soluções de referência ou projetos criativos que mostraremos.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:4,
          predecessor:3,
          texto:'Ah, vale lembrar que os projetos são autorais! Se inspirem nos exemplos, mas organizem suas próprias ideias envolvendo, dando asas à imaginação.',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},

          {ordem:5,
          predecessor:4,
          texto:'Prontos para criar suas próprias histórias em quadrinho animadas? Vamos lá!',
          urlAudioTexto:'',
          textoSimplificado:'',
          textoImpresso:1,
          imagemImpresso:1,
          urlImagem:'',
          promptImagem:'', 
          imagemFonte:'',
          textoDescritivoImagem:'',},
        
           ]}},


      licao28:{},	

    },

    capaVerso:{
      urlImagemTerceiraCapa:'',
      textoTerceiraCapa: '',
      textoUltimaCapa: 'Charles Babbage foi um cientista, matemático, filósofo, engenheiro mecânico e inventor inglês que é mais conhecido como o inventor que projetou o primeiro computador de uso geral, utilizando apenas partes mecânicas, a máquina analítica.'
    },

}