let livro_cw3 ={

  /* metadados 2 */
  versao:'0.1.00',
  nomeFantasia: '',
  nomeTecnico:'CW3',
  resumo:'Módulo adequado para o Ensino Fundamental - Anos Iniciais, dando sequência ao módulo CW2. Aborda o conceito de algoritmo e seus componentes lógicos como laços, funções, condições, operadores relacionais, comparativos, eventos, classes, objetos, aleatoriedade e padrões, de modo lúdico e prático, por meio do uso de dispositivos computacionais.',
  resumoCapa: 'A telefonia evoluiu com dispositivos móveis e redes de alta velocidade, possibilitados pela computação. Smartphones e apps de mensagens tornam a comunicação instantânea e acessível.',
  nomeTecnicoEn: "CW3e",
  resumoEn: "Module suitable for Elementary School - Early Years, continuing from the CW2 module. It covers the concept of algorithms and their logical components such as loops, functions, conditions, relational operators, comparatives, events, classes, objects, randomness, and patterns, in a playful and practical way, through the use of computing devices.",
  resumoCapaEn: "Telephony has evolved with mobile devices and high-speed networks enabled by computing. Smartphones and messaging apps make communication instant and accessible.",

  isbn:'',
  autores:['Paulo Alvim, Anderson Borges'],
  editor:'Fernanda Oliveira, Miguel Mendonça de Goffredo',
  local:'',
  ano:'2025',
  url:'',

  versaoAdaptacao:'',
  nomeAdaptacaoo: '',
  autoresAdaptacao:[],
  local:'',
  escola:'',
  ano:'',
  url:'',
  codigoCid11:'', /* opc */
  descritivoPerfilAluno:'',
  resumoAdaptacao:'',

  capa:{
		urlImagemCapa:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/cw3_frente.png',
		urlImagemSegundaCapa:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/cw3_verso.png',
    urlImagemCapaEn:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/cw3e%20-%20frente.png',
		urlImagemSegundaCapaEn:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/cw3e%20-%20verso.png',},

  formularioRegistro:{
    titulo:'',
    urlImagem:'',
    campos:[{rotulo:'Login Somos:',formato:'usuarioAcessivel'},{rotulo:'Senha:',formato:'senhaAcessivel'}]},

  /*visaogeral:{
    titulo:'',
    descricao:'',
    licao1:{id:'',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
      cenas:[				
        {ordem:1,
        predecessor:0,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        urlImagem:'',
        textoImpresso:0,
        textoImpressoRecriado:'',
        promptImagem:'',
        imagemImpresso:0,
        imagemFonte:'',
        textoDescritivoImagem:'',},
        ]}},
        },*/
      
  unidade1:{
    titulo:'',
    descricao:'',
    licao1:{id:'CW3AULA01',
    infografico:{titulo:'Lição 01. Comparando Valores com Operadores Relacionais',
    tituloSimplificado:'Operadores Relacionais',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'Já aprendemos sobre <b>condicionais</b>, usando comandos como: <code><b>se</b> sinal = vermelho <br/>&nbsp;&nbsp;<b>então</b> pare <br/><b>se</b> sinal = verde <br/>&nbsp;&nbsp;<b>então</b> prossiga</code>',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L1/cogna-ia-image.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem de um semáforo para carros com três luzes: a luz de cima, vermelha, deverá estar acesa, enquanto as duas outras deverão estar apagadas',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},

      {ordem:2,
      predecessor:1,
      texto:'Após o “se”, podemos comparar valores com operadores relacionais, usando sinais matemáticos como: <b>Igual (=)</b> → Verifica se dois valores são iguais. <br/><b>Maior que (>)</b> → Verifica se um valor é maior que o outro. <br/><b>Menor que (<)</b> → Verifica se um valor é menor que o outro. <br/><b>Maior ou igual a (>=)</b> → Verifica se um valor é maior ou igual ao outro. <br/><b>Menor ou igual a (<=)</b> → Verifica se um valor é menor ou igual ao outro. <br/><b>Diferente de (≠)</b> → Verifica se dois valores são diferentes',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},

      {ordem:3,
      predecessor:2,
      texto:'Por exemplo, usamos o <b>igual (=)</b> para comparar se valores são iguais. <code><b>se</b> 2 = 2<br/>&nbsp;&nbsp;<b>então</b> exiba “os números são iguais”</code>',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L1/img2.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem indicando que o número 2 é igual ao número 2',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},

      {ordem:4,
      predecessor:3,
      texto:'Usamos o “maior que” (>) para comparar se um número é maior que outro. Por exemplo: <code><b>se</b> 130 > 120 <br/>&nbsp;&nbsp;<b>então</b> mova</code> Como 130 é maior que 120, o comando "mova" é executado.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},

      {ordem:5,
      predecessor:4,
      texto:'Esse teste condicional pode ser usado para ver se uma criança pode entrar na roda gigante: <code><b>se</b> altura > 120 cm <br/>&nbsp;&nbsp;<b>então</b> suba na roda gigante <br/>&nbsp;&nbsp;<b>senão</b> não suba na roda gigante</code> Se a altura for 110 cm, o programa diz que não pode subir, porque 110 não é maior que 120.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L1/img5.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem de uma fila de crianças aguardando para entrar na roda gigante, mas tendo que passar pela regua de limite de altura primeiro',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},

      {ordem:6,
      predecessor:5,
      texto:'Usamos o “menor que” (<) para comparar se um número é menor que outro. Por exemplo: <code><b>se</b> nota < 60 <br/>&nbsp;&nbsp;<b>então</b> reprovar aluno na matéria <br/>&nbsp;&nbsp;<b>senão</b> aprovar aluno na matéria</code>',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L1/img6.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem de uma criança recebendo o boletim escolar, com uma nota em azul, escrito "80" e uma nota em vermelho, escrito "50"',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},

      {ordem:7,
      predecessor:6,
      texto:'Além dos sinais "=", ">" e "<", também podemos usar os operadores "maior ou igual a" (>=) e "menor ou igual a" (<=). <code><b>se</b> velocidade <= 80 km/h <br/>&nbsp;&nbsp;<b>então</b> não multar motorista <br/>&nbsp;&nbsp;<b>senão</b> multar motorista</code>Nesse caso, se a velocidade for maior que 80 (por exemplo, 81), então o motorista é multado.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L1/img7.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem de um policial rodoviário com uma câmera apontada para um carro que passa correndo por ele, pronto para multar o motorista',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},

      {ordem:8,
      predecessor:7,
      texto:'Também podemos usar o operador “diferente de” (≠) para comparar valores. Veja o exemplo: <code><b>se</b> senha digitada ≠ senha correta <br/>&nbsp;&nbsp<b>então</b> exiba "Senha incorreta! Tente novamente."',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},

      {ordem:9,
      predecessor:8,
      texto:'Vamos praticar? Com expressões relacionais, seus programas vão longe...',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      ]}},
        
    licao2:{id:'CW3AULA02',
    infografico:{titulo:'Lição 02. Laço Repita Enquanto',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'Hoje vamos aprender um novo tipo de laço muito importante na programação: o laço "repita enquanto".',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},

      {ordem:2,
      predecessor:1,
      texto:'Esse comando é usado quando não sabemos, com antecedência, quantas vezes o laço precisa ser repetido.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},

      {ordem:3,
      predecessor:2,
      texto:'Imaginem um barco que está afundando porque tem um furo no casco e está enchendo de água. O comandante precisa instruir seu ajudante a tirar a água com um balde para evitar que o barco afunde.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},

      {ordem:4,
      predecessor:3,
      texto:'Mas ele não sabe quantos baldes de água serão necessários para esvaziar o barco. Então, ele daria uma instrução como: "Enquanto houver água no barco, retire a água com este balde."',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},

      {ordem:5,
      predecessor:4,
      texto:'Em um programa de computador, esse comando poderia ser escrito assim: <code><b>repita enquanto</b> houver água no barco <br/>&nbsp;&nbspretire um balde de água</code>',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},

      {ordem:6,
      predecessor:5,
      texto:'Nos videogames, por exemplo, quando um jogador precisa coletar moedas que aparecem aleatoriamente à sua frente, o jogo pode usar um comando como: <code><b>repita enquanto</b> houver moedas à frente <br/>&nbsp;&nbspcolete moeda',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L2/L2_6.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem de um personagem de videogame que tem várias moedas à sua frente, pronto para pegá-las',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},

      {ordem:7,
      predecessor:8,
      texto:'Em ambos os exemplos acima, o comando dentro do laço será repetido várias vezes. Mas percebam que o número de execuções do comando pode variar em  diferentes situações.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},

      {ordem:8,
      predecessor:7,
      texto:'Agora é a sua vez! Use o "repita enquanto" para resolver desafios que não podem ser resolvidos com o laço "repita N vezes".',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
    
    licao3:{id:'CW3AULA03',
    infografico:{titulo:'Lição 03. Laço Repita Até',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'Hoje vamos conhecer outro tipo de laço muito útil na programação: o laço "repita até".',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},

      {ordem:2,
      predecessor:1,
      texto:'Assim como o laço “repita enquanto”, o laço “repita até” também é usado quando não sabemos, com antecedência, quantas vezes o laço será repetido.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:3,
      predecessor:2,
      texto:'No laço <b>repita enquanto</b>, a repetição acontece enquanto uma condição for verdadeira.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},

      {ordem:4,
      predecessor:3,
      texto:'Já no laço <b>repita até</b>, a repetição acontece até que uma condição seja verdadeira. Vamos ver um exemplo! ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Imagine que um aventureiro está explorando uma caverna escura e precisa encontrar a saída. Ele continua andando no escuro até encontrar a porta de saída. Se formos pensar nesse problema como um algoritmo, podemos escrever: <code><b>repita até</b> encontrar a saída <br/>&nbsp;&nbspcontinue andando</code>',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L3/L3_5.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista de uma moça negra jovem, aventureira, andando dentro de uma caverna escura, à procura da saída',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Isso significa que o aventureiro vai continuar andando enquanto a saída ainda não foi encontrada. Assim que ele encontrar a saída, o laço para automaticamente.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Agora, vamos comparar com o exemplo do barco enchendo de água. Usando o laço "repita enquanto": <code><b>repita enquanto</b> houver água no barco <br/>&nbsp;&nbspretire um balde de água</code>',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Esse laço continua enquanto houver água no barco. Assim que a água acabar, o laço <b>para</b>.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'Usando o laço "repita até", poderíamos reescrevê-lo assim: <code><b>repita</b> até o barco estar seco <br/>&nbsp;&nbspretire um balde de água</code>',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:10,
      predecessor:9,
      texto:'Aqui, o laço funciona da mesma maneira, mas a forma como pensamos é diferente: ele vai parar quando o barco estiver completamente seco.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:11,
      predecessor:10,
      texto:'Agora é sua vez!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},

    licao4:{id:'CW3AULA04',
    infografico:{titulo:'Lição 04. Êxodo Rural e Êxodo Urbano',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'Nosso país é muito grande e as pessoas vivem em diferentes lugares: em cidades grandes, pequenas, no campo e na praia. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Ao longo da história, muitas pessoas mudaram de lugar para buscar uma vida melhor.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Quando muitas pessoas saem de um lugar e vão para outro, chamamos isso de Êxodo, que significa "saída" ou "mudança de lugar".',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'O êxodo pode ser de dois tipos: Êxodo Rural – quando as pessoas saem do campo para morar na cidade.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Por exemplo no Brasil, entre os anos 1960 e 1980, muitas pessoas saíram do campo e foram para as grandes cidades para procurar trabalho e melhorar de vida. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Mas as cidades cresceram muito rápido e surgiram desafios, como trânsito intenso e aumento da violência.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Êxodo Urbano: das cidades para o campo. Por isso, depois dos anos 2000, mais pessoas começaram a sair das grandes cidades para o campo, em busca de uma vida mais tranquila ou porque estavam sem trabalho nas cidades.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'E vocês, gostam mais da cidade ou do campo?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L4/L4_8.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem do tipo pintura a óleo que mostre de um lado a vida simples no campo e do outro, a vida moderna na cidade',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'Nosso próximo desafio vai explorar as vantagens e desvantagens da vida na cidade e no campo, com a ajuda de robôs!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},

    licao5:{},

    licao6:{},

    licao7:{id:'CW3AULA07',
    infografico:{titulo:'Interface Física',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},          
    
    },

  unidade2:{
    titulo:'',
    descricao:'',
    licao8:{id:'CW3AULA08',
    infografico:{titulo:'Lição 08. Dados e Informações',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'Os dados estão em todos os lugares e são muito importantes!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Dados são pequenos pedaços de informação ainda sem significado completo. Quando organizamos e damos um contexto aos dados, eles viram informação.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Exemplo: O número 15 sozinho é apenas um dado. Mas se dissermos que 15 é a temperatura do dia, agora temos uma informação útil!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Os dados podem ser de diferentes tipos: Números (exemplo: 1, 2, 100), Palavras ou textos (exemplo: "Sol", "Casa", "Brinquedo"), Imagens (fotos, desenhos, gráficos)',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Dados que mudam e dados que não mudam: Constantes: São dados que nunca mudam, como os 7 dias da semana. Variáveis: São dados que podem mudar, como a temperatura do dia.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Por que os dados são importantes? ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Nosso mundo digital usa dados para tomar decisões, criar novas tecnologias e até ajudar nas nossas vidas!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Nos videogames, os dados guardam a pontuação e o progresso do jogador. Na escola, usamos dados para ver as notas das provas. Nos mapas digitais, os dados mostram onde estamos e para onde queremos ir.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'Os computadores e os programas usam dados o tempo todo! Por isso, é importante aprender a organizá-los e usá-los do jeito certo.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
          
    licao9:{id:'CW3AULA09',
    infografico:{titulo:'Lição 09. Sistema Binário – Como os Computadores Entendem Letras',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'Os computadores podem trabalhar com textos, números, imagens, músicas e vídeos.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Mas você sabia que, para entender tudo isso, eles usam apenas dois dígitos?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Os computadores funcionam com o formato digital, que usa apenas os dígitos 0 e 1.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Isso acontece porque os computadores trabalham com eletricidade, e esses dois dígitos representam sinais elétricos: <br/>&nbsp;&nbsp1 – Ligado <br/>&nbsp;&nbsp0 – Desligado',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Mas como os computadores entendem as letras?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Para transformar letras em 0s e 1s, os computadores usam uma tabela chamada ASCII.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CWX/i19%20-%20Sistema%20Bin%C3%A1rio%20-%20Letras/slide%203.jpg',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'cwx',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Cada letra tem um código especial na tabela ASCII. Esse código é formado por oito dígitos binários (bits), sempre usando apenas 0s e 1s.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Por exemplo, veja como o computador armazena algumas letras: <br/>&nbsp;&nbspA → 01000001 <br/>&nbsp;&nbspC → 01000011 <br/>&nbsp;&nbspS → 01010011 ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CWX/i19%20-%20Sistema%20Bin%C3%A1rio%20-%20Letras/slide%204.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'cwx',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'Agora, vamos ver como uma palavra inteira é transformada em código binário!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:10,
      predecessor:9,
      texto:'A palavra "casa" vira: <code>01100011 01100001 01110011 01100001</code>',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CWX/i19%20-%20Sistema%20Bin%C3%A1rio%20-%20Letras/slide%205.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'cwx',
      textoDescritivoImagem:'',},
        
      {ordem:11,
      predecessor:10,
      texto:'Cada conjunto de oito dígitos binários representa uma letra.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:12,
      predecessor:11,
      texto:'Agora é sua vez de escrever nomes em binário para desvendar esse código misterioso por trás dos computadores!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
    
    licao10:{id:'CW3AULA10',
    infografico:{titulo:'Internet e Buscadores WEB (Com e Sem IA)',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao11:{id:'CW3AULA11',
    infografico:{titulo:'Compartilhamento de Dados em Mídias Digitais',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao12:{id:'CW3AULA12',
    infografico:{titulo:'Lição 12. A Revolução da Internet das Coisas',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'Vocês já sabem que a internet conecta computadores pelo mundo. Mas ela pode fazer muito mais!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Hoje, os computadores ficaram tão pequenos que podem estar dentro de geladeiras, lâmpadas, carros e robôs como o Sphero.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Agora, imaginem se não apenas os computadores estivessem conectados à internet, mas todos os aparelhos da sua casa.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Essa é a ideia da Internet das Coisas, abreviada como IdC ou IoT (do inglês, Internet of Things).',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Como a Internet das Coisas funciona?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Vocês já viram luzes que acendem sozinhas quando alguém passa? Isso acontece porque elas têm sensores próximos, conectados a elas.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Agora, imaginem se o sensor pudesse falar com outros aparelhos mais distantes, como a TV, o videogame ou o ar-condicionado.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Se tudo estivesse conectado, os aparelhos da casa inteira poderiam saber quando uma pessoa chega e se preparar para recebê-la!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'1. O sensor de presença detecta e avisa os aparelhos que alguém chegou. <br/>2. A TV liga no seu programa favorito. <br/>3. O ar-condicionado ajusta a temperatura. <br/>4. E um robô pode abrir a porta e até trazer seu lanche! ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:10,
      predecessor:9,
      texto:'Tudo isso porque os aparelhos conversam entre si pela internet.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:11,
      predecessor:10,
      texto:'No futuro, vocês poderão falar com aparelhos como sua geladeira, mesmo estando fora de casa e perguntar: "Tem suco de uva para eu tomar quando chegar?"',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:12,
      predecessor:11,
      texto:'A geladeira poderá responder e até sugerir um local para comprar suco.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:13,
      predecessor:12,
      texto:'E esse futuro de ficção científica da Internet das Coisas será criado por vocês! Vamos começar?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao13:{id:'CW3AULA13',
    infografico:{titulo:'Projeto Automação Residencial com  IdC (IoT)',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao14:{},          
      
    },

  unidade3:{
    titulo:'',
    descricao:'',
    licao15:{id:'CW3AULA15',
    infografico:{titulo:'Lição 15. Pixel e Cores',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'Vocês sabiam que as imagens na tela do computador são feitas de milhares de pequenos pontos? Esses pontos são chamados de pixels!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'O que são pixels?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Um pixel é a menor parte de uma imagem digital, e cada pixel tem uma única cor. Como há muitos pixels juntos, eles formam as imagens que vemos na tela. Em telas antigas de videogames e computadores, era fácil ver cada pixel separadamente.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Mas como as telas criam cores para os pixels?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Para formar imagens coloridas, os computadores usam três cores principais, ou primárias: Vermelho (Red), Verde (Green) e Azul (Blue)',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
       
      {ordem:6,
      predecessor:5,
      texto:'Essas cores são chamadas de RGB, porque vêm do inglês: Red, Green, Blue.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Misturando essas três cores em diferentes quantidades, é possível criar todas as demais cores da tela...',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'E como enxergamos as cores?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'Um cientista chamado James Clerk Maxwell, que viveu há mais de 100 anos, foi quem descobriu como criar fotos coloridas misturando cores.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:10,
      predecessor:9,
      texto:'Ele também descobriu que nem todo mundo vê as cores do mesmo jeito. Façam um teste: Este vestido é “branco e dourado” ou “azul e preto”?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CWX/i24%20-%20Pixel%20e%20Cores/slide%208.jpg',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'cwx',
      textoDescritivoImagem:'',},
        
      {ordem:11,
      predecessor:10,
      texto:'Sim, cada pessoa pode enxergar as cores de um jeito diferente...',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:12,
      predecessor:11,
      texto:'Agora é sua vez! Vamos criar imagens usando pixels?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
          
    licao16:{id:'CW3AULA16',
    infografico:{titulo:'Lição 16. Desenhos 3D – Criando Profundidade em Imagens',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'Vocês sabiam que o mundo ao nosso redor tem três dimensões? ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Os objetos que vemos têm altura, largura e profundidade. A profundidade é também chamada de espessura ou volume.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Uma folha de papel parece ter apenas largura e altura, mas se olharmos bem de perto, veremos que ela tem uma pequena espessura.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Mas desenhos no papel ou na tela são 2D. Eles possuem apenas largura e altura. Então, como é criada a sensação de 3D que vemos nos desenhos?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Os artistas descobriram três truques para fazer os desenhos 2D parecerem estar em 3D!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'1. Usando a Perspectiva, uma técnica de desenho que usa linhas inclinadas e distantes para criar a sensação de espaço. Desenhistas usam essa técnica para ilustrar cidades, ruas e prédios que parecem reais! ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Olhem pinturas de Leonardo da Vinci! Ele usava a perspectiva para criar imagens super realistas!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'2. Usando Luzes e Sombras, que é outro truque para criar profundidade em desenhos.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'Quando um objeto recebe luz, uma parte dele fica mais clara e outra fica mais escura. Sombras ajudam a mostrar volume e dão um efeito mais realista.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:10,
      predecessor:9,
      texto:'O artista Caravaggio era um mestre nisso! Ele usava luz e sombra para dar vida às suas pinturas.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:11,
      predecessor:10,
      texto:'3. Enganando o Cérebro com Linhas. Os desenhistas também fazem os traços mudarem de direção para criar a ilusão de profundidade.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:12,
      predecessor:11,
      texto:'Se as linhas seguem certas direções, nosso cérebro entende que a imagem tem volume. Vamos testar?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:13,
      predecessor:12,
      texto:'Olhem esta figura: Vocês conseguem ver uma mão escondida nela?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:14,
      predecessor:13,
      texto:'Agora é sua vez de se aprofundar no curioso mundo dos desenhos 3D!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
      
    licao17:{id:'CW3AULA17',
    infografico:{titulo:'Lição 17. 3D Estereoscópico',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'Vocês já aprenderam a usar perspectiva, sombras e linhas curvas para criar desenhos em 3D.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Mas existe um truque ainda mais incrível para criar imagens que parecem saltar da tela: a estereoscopia!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Como Funciona?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'A estereoscopia acontece porque nossos dois olhos veem o mundo de ângulos um pouco diferentes. <br/>- Fechem um olho e olhem para um objeto. <br/>- Agora troquem de olho.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Perceberam que a posição do objeto parece mudar um pouquinho?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Nosso cérebro junta essas duas imagens e cria a sensação de profundidade e volume.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Foi com essa ideia que um cientista britânico chamado Charles Wheatstone inventou o primeiro estereoscópio no século 19!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Como Criamos o 3D Estereoscópico?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'O estereoscópio mostra duas imagens 2D do mesmo objeto, cada uma com um pequeno deslocamento, uma para cada olho.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:10,
      predecessor:9,
      texto:'O cérebro junta essas imagens e cria a ilusão de que estamos vendo algo em 3D de verdade!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:11,
      predecessor:10,
      texto:'Mas o estereoscópio original era difícil de usar. Então, inventores como Carlos de Almeida criaram técnicas mais simples, como os óculos anaglíficos.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:12,
      predecessor:11,
      texto:'Os óculos anaglíficos usam lentes coloridas que filtram cores diferentes, para separar duas imagens sobrepostas.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L17/L17_12.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem que mostre um óculos anaglífico',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:13,
      predecessor:12,
      texto:'Nos cinemas modernos, óculos mais avançados fazem cada olho ver uma imagem diferente, criando um efeito 3D impressionante!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:14,
      predecessor:13,
      texto:'Os filmes em 3D são gravados com câmeras que têm duas lentes, funcionando como nossos olhos.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:15,
      predecessor:14,
      texto:'E, no cinema, um projetor especial envia uma imagem para a lente esquerda e outra para a lente direita dos óculos 3D.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:16,
      predecessor:15,
      texto:'Essa é também a base dos óculos de Realidade Virtual.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:17,
      predecessor:16,
      texto:'Agora é sua vez de programar desenhos 3D estereoscópicos - e aprender a base da Realidade Virtual!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao18:{id:'CW3AULA18',
    infografico:{titulo:'Lição 18. Programação 3D',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'Vocês já assistiram a filmes de animação 3D ou jogaram games com gráficos realistas?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Sabiam que tudo isso é criado com programação e modelagem 3D?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Esses ambientes simulam o espaço tridimensional no computador, permitindo criar, mover e girar objetos virtuais como se estivessem no mundo real.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Com programação 3D, podemos desenhar formas com altura, largura e profundidade...',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Depois, podemos mover e rotacionar esses objetos, entendendo como eles se comportam em um espaço de três dimensões.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Combinando várias formas básicas, com cubos, cilindros e cones, conseguimos simular estruturas incríveis, como monumentos históricos. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Agora chegou a sua vez. Prontos para começar a explorar o universo da programação 3D?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao19:{},
  
    licao20:{id:'CW3AULA20',
    infografico:{titulo:'Modelagem de Monumentos',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao21:{},          
      
    },
    
  unidade4:{
    titulo:'',
    descricao:'',
    licao22:{id:'CW3AULA22',
    infografico:{titulo:'Lição 22. Linguagem de Programação Scratch',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'Hoje vamos falar sobre uma linguagem de programação muito versátil, o <b>Scratch</b>.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'O Scratch é uma linguagem de programação voltada para criação e programação de jogos e histórias animadas.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Ele foi desenvolvido pelo MIT, o famoso Instituto de Tecnologia de Massachusetts, e se tornou um grande sucesso, utilizado por milhões de alunos e adultos ao redor do mundo.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Em nosso curso, utilizaremos uma versão do Scratch integrada à Plataforma Mind Makers.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Com isso, não precisaremos fazer um novo cadastro no site scratch.mit.edu, evitando logins e senhas duplicadas.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'E o melhor de tudo, tudo que vocês aprenderem funcionará exatamente da mesma maneira nos dois ambientes!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'No Scratch, os personagens são conhecidos como <b>atores</b>.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CSX/LingProgrScr/img_3.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'cwx',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Um ator pode ter várias <b>fantasias</b>, representando diferentes posições ou vestimentas que ele pode adotar em momentos específicos de um jogo ou história.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L22/L22_8.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
       
      {ordem:9,
      predecessor:8,
      texto:'Vocês podem enriquecer seus jogos ou histórias adicionando <b>efeitos sonoros</b> especiais, incluindo músicas e uma variedade de sons, como "o fechar de uma porta", uma buzina e outros.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CSX/LingProgrScr/img_4.jpg',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'cwx',
      textoDescritivoImagem:'',},
        
      {ordem:10,
      predecessor:9,
      texto:'O <b>palco</b> é o espaço onde a ação ocorre.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CSX/LingProgrScr/img_5.jpg',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'cwx',
      textoDescritivoImagem:'',},
        
      {ordem:11,
      predecessor:10,
      texto:'É neste retângulo que todos os personagens se movem.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L22/L22_11.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:12,
      predecessor:11,
      texto:'O palco pode ser decorado com diferentes <b>cenários</b> de fundo disponíveis, transportando seus atores para locais como o espaço, estádios de futebol, paisagens nevadas ou interiores de casas, por exemplo.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CSX/LingProgrScr/img_6.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'cwx',
      textoDescritivoImagem:'',},
        
      {ordem:13,
      predecessor:12,
      texto:'Mas é com a programação que damos vida ao espetáculo!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L22/L22_13.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:14,
      predecessor:13,
      texto:'É ela que nos permite mover os atores, trocar cenários, produzir sons, exibir pontuações e muito mais.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/cpsciimageinf/CSX/LingProgrScr/img_7.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'cwx',
      textoDescritivoImagem:'',},
        
      {ordem:15,
      predecessor:14,
      texto:'<i>O limite é a sua imaginação.</i>',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:16,
      predecessor:15,
      texto:'Vamos começar a criar e programar nossas próprias histórias e jogos no Scratch?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:17,
      predecessor:16,
      texto:'O mundo da programação está esperando por vocês.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
          
    licao23:{},
      
    licao24:{},
  
    licao25:{},
  
    licao26:{},
  
    licao27:{id:'CW3AULA27',
    infografico:{titulo:'Lição 27. Missão: Animação da Família',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'Neste projeto, sua equipe criará uma cena animada divertida no Scratch, trazendo vocês e seus familiares como personagens!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Sigam as seguintes orientações gerais: Usem o smartphone para tirar fotos de vocês mesmos em várias poses.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Com o apoio do facilitador, utilizem um software para remover o fundo das imagens.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Façam um remix de seus primeiros programas no Scratch e importem suas imagens como fantasias dos personagens.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Vocês também podem recortar as fotos e substituir apenas a cabeça dos personagens em seus projetos.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Executem o programa e vejam como podem ser os protagonistas de suas próprias animações no Scratch!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Como missão para casa, tirem fotos também de seus familiares.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Na próxima aula, finalizem a animação recortando as novas fotos e ajustando a programação.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:9,
      predecessor:8,
      texto:'Dica: programem um diálogo entre os personagens inspirado em acontecimentos reais!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:10,
      predecessor:9,
      texto:'Prontos para começar?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao28:{},          
      
    },
      
      /*
      glossarioBilingue:{  }
      */
    
      capaVerso:{
        urlImagemTerceiraCapa:'',
        textoTerceiraCapa:``,
    
        textoUltimaCapa: ``
        },
}