let livro_cw3 ={

  /* metadados 2 */
  versao:'0.1.00',
  nomeFantasia: '',
  nomeTecnico:'CW3',
  resumo:'Módulo adequado para o Ensino Fundamental - Anos Iniciais, dando sequência ao módulo CW2. Aborda o conceito de algoritmo e seus componentes lógicos como laços, funções, condições, operadores relacionais, comparativos, eventos, classes, objetos, aleatoriedade e padrões, de modo lúdico e prático, por meio do uso de dispositivos computacionais.',
  resumoCapa: 'A telefonia evoluiu com dispositivos móveis e redes de alta velocidade, possibilitados pela computação. Smartphones e apps de mensagens tornam a comunicação instantânea e acessível.',
  nomeTecnicoEn: "CW3e",
  resumoEn: "Module suitable for Elementary School - Early Years, continuing from the CW2 module. It covers the concept of algorithms and their logical components such as loops, functions, conditions, relational operators, comparatives, events, classes, objects, randomness, and patterns, in a playful and practical way, through the use of computing devices.",
  resumoCapaEn: "Telephony has evolved with mobile devices and high-speed networks enabled by computing. Smartphones and messaging apps make communication instant and accessible.",

  isbn:'',
  autores:['Paulo Alvim, Anderson Borges'],
  editor:'Fernanda Oliveira, Miguel Mendonça de Goffredo',
  local:'',
  ano:'2025',
  url:'',

  versaoAdaptacao:'',
  nomeAdaptacaoo: '',
  autoresAdaptacao:[],
  local:'',
  escola:'',
  ano:'',
  url:'',
  codigoCid11:'', /* opc */
  descritivoPerfilAluno:'',
  resumoAdaptacao:'',

  capa:{
		urlImagemCapa:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/cw3_frente.png',
		urlImagemSegundaCapa:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/cw3_verso.png',
    urlImagemCapaEn:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/cw3e%20-%20frente.png',
		urlImagemSegundaCapaEn:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/cw3e%20-%20verso.png',},

  formularioRegistro:{
    titulo:'',
    urlImagem:'',
    campos:[{rotulo:'Login Somos:',formato:'usuarioAcessivel'},{rotulo:'Senha:',formato:'senhaAcessivel'}]},

  /*visaogeral:{
    titulo:'',
    descricao:'',
    licao1:{id:'',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
      cenas:[				
        {ordem:1,
        predecessor:0,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        urlImagem:'',
        textoImpresso:0,
        textoImpressoRecriado:'',
        promptImagem:'',
        imagemImpresso:0,
        imagemFonte:'',
        textoDescritivoImagem:'',},
        ]}},
        },*/
      
  unidade1:{
    titulo:'',
    descricao:'',
    licao1:{id:'CW3AULA01',
    infografico:{titulo:'Comparando Valores com Operadores Relacionais',
    tituloSimplificado:'Operadores Relacionais',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
        
    licao2:{id:'CW3AULA02',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
    
    licao3:{id:'CW3AULA03',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},

    licao4:{id:'CW3AULA04',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},

    licao5:{},

    licao6:{},

    licao7:{id:'CW3AULA07',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},          
    
    },

  unidade2:{
    titulo:'',
    descricao:'',
    licao8:{id:'CW3AULA08',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
          
    licao9:{id:'CW3AULA09',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
    
    licao10:{id:'CW3AULA10',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao11:{id:'CW3AULA11',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao12:{id:'CW3AULA12',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao13:{id:'CW3AULA13',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao14:{},          
      
    },

  unidade3:{
    titulo:'',
    descricao:'',
    licao15:{id:'CW3AULA15',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
          
    licao16:{id:'CW3AULA16',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
      
    licao17:{id:'CW3AULA17',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao18:{id:'CW3AULA18',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao19:{},
  
    licao20:{id:'CW3AULA20',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao21:{},          
      
    },
    
  unidade4:{
    titulo:'',
    descricao:'',
    licao22:{id:'CW3AULA22',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
          
    licao23:{},
      
    licao24:{},
  
    licao25:{},
  
    licao26:{},
  
    licao27:{id:'CW3AULA27',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      ]}},
  
    licao28:{},          
      
    },
      
      /*
      glossarioBilingue:{  }
      */
    
      capaVerso:{
        urlImagemTerceiraCapa:'',
        textoTerceiraCapa:``,
    
        textoUltimaCapa: ``
        },
}