let livro_cw4 ={

  /* metadados 2 */
  versao:'0.1.00',
  nomeFantasia: '',
  nomeTecnico:'CW4',
  resumo:'Módulo adequado para o Ensino Fundamental, dando sequência ao módulo CW3. Amplia, de modo lúdico e divertido, os conhecimentos sobre algoritmos e programação, além de abordar expressões aritméticas simples, juntamente com a aplicação de condicionais e geração de aleatoriedades. Aborda a postura ética nas comunicações através de meios digitais e exercita a identificação de fake news.',
  resumoCapa: 'A computação na medicina permite diagnósticos precisos com equipamentos avançados e facilita o compartilhamento de registros médicos. Telemedicina e robótica cirúrgica melhoram o acesso e a qualidade dos cuidados médicos.',
  nomeTecnicoEn: "CW4e",
  resumoEn: "Module suitable for Elementary School, continuing from the CW3 module. It expands, in a playful and fun way, knowledge about algorithms and programming, as well as covering simple arithmetic expressions, along with the application of conditionals and the generation of randomness. It addresses ethical behavior in digital communications and exercises the identification of fake news.",
  resumoCapaEn: "Computing in medicine allows for precise diagnostics with advanced equipment and facilitates the sharing of medical records. Telemedicine and surgical robotics improve access and quality of medical care.",

  isbn:'',
  autores:[],
  editor:'',
  local:'',
  ano:'',

  versaoAdaptacao:'',
  nomeAdaptacaoo: '',
  autoresAdaptacao:[],
  local:'',
  escola:'',
  ano:'',
  url:'',
  codigoCid11:'', /* opc */
  descritivoPerfilAluno:'',
  resumoAdaptacao:'',

  capa:{
    urlImagemCapa:'https://storage.googleapis.com/mindmakers/Computational%20World/CW4/cw4_frente.png',
    urlImagemSegundaCapa:'https://storage.googleapis.com/mindmakers/Computational%20World/CW4/cw4_verso.png',
    urlImagemCapaEn:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/cw4e%20-%20frente.png',
    urlImagemSegundaCapaEn:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/cw4e%20-%20verso.png',},
  
  formularioRegistro:{
    titulo:'',
    urlImagem:'',
    campos:[{rotulo:'Login Somos:',formato:'usuarioAcessivel'},{rotulo:'Senha:',formato:'senhaAcessivel'}]},
  
   /*visaogeral:{
    titulo:'',
    descricao:'',
    licao1:{id:'',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
      cenas:[				
        {ordem:1,
        predecessor:0,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        urlImagem:'',
        textoImpresso:0,
        textoImpressoRecriado:'',
        promptImagem:'',
        imagemImpresso:0,
        imagemFonte:'',
        textoDescritivoImagem:'',},
        ]}},
        },*/
      
        unidade1:{
          titulo:'',
          descricao:'',
          licao1:{id:'CW3AULA01',
            infografico:{titulo:'Lição 01. Êxodo Rural e Êxodo Urbano',
            tituloSimplificado:'',
            estiloPadrao:'basicoPaisagem',
            video:'',
            cenas:[				
              {ordem:1,
              predecessor:0,
              texto:'Nosso país é muito grande e as pessoas vivem em diferentes lugares: em cidades grandes, pequenas, no campo e na praia. ',
              urlAudioTexto:'',
              textoSimplificado:'',
              urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L4/L4_1.png',
              textoImpresso:1,
              textoImpressoRecriado:'',
              promptImagem:'gere uma image em estilo pintura à óleo que mostre os diferentes tipos de locais de moradia: cidade pequena, cidade grande, praia e campo',
              imagemImpresso:1,
              imagemFonte:'cogna ia',
              textoDescritivoImagem:'',},
                
              {ordem:2,
              predecessor:1,
              texto:'Ao longo da história, muitas pessoas mudaram de lugar para buscar uma vida melhor.',
              urlAudioTexto:'',
              textoSimplificado:'',
              urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L4/L4_2.png',
              textoImpresso:1,
              textoImpressoRecriado:'',
              promptImagem:'gere uma image em estilo pintura à óleo que mostre um pequeno grupo de pessoas em êxodo rural, em busca de melhores condições de trabalho e vida na cidade grande',
              imagemImpresso:1,
              imagemFonte:'cogna ia',
              textoDescritivoImagem:'',},
                
              {ordem:3,
              predecessor:2,
              texto:'Quando muitas pessoas saem de um lugar e vão para outro, chamamos isso de Êxodo, que significa <b>saída</b> ou <b>mudança de lugar</b>.',
              urlAudioTexto:'',
              textoSimplificado:'',
              urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L4/L4_3.png',
              textoImpresso:1,
              textoImpressoRecriado:'',
              promptImagem:'gere uma imagem em estilo pintura à óleo que mostre uma pequena família arrumando o caminhão de mudança',
              imagemImpresso:1,
              imagemFonte:'cogna ia',
              textoDescritivoImagem:'',},
                
              {ordem:4,
              predecessor:3,
              texto:'O êxodo pode ser de dois tipos: Êxodo Rural – quando as pessoas saem do campo para morar na cidade.',
              urlAudioTexto:'',
              textoSimplificado:'',
              urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L4/L4_4.png',
              textoImpresso:1,
              textoImpressoRecriado:'',
              promptImagem:'gere uma imagem em estilo pintura à óleo de uma pequena família que está deixando a fazenda e indo para a cidade',
              imagemImpresso:1,
              imagemFonte:'cogna ia',
              textoDescritivoImagem:'',},
                
              {ordem:5,
              predecessor:4,
              texto:'Por exemplo no Brasil, entre os anos 1960 e 1980, muitas pessoas saíram do campo e foram para as grandes cidades para procurar trabalho e melhorar de vida.',
              urlAudioTexto:'',
              textoSimplificado:'',
              urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L4/L4_5.png',
              textoImpresso:1,
              textoImpressoRecriado:'',
              promptImagem:'Gere uma imagem em estilo pintura à óleo que retrate uma pequena família do campo indo em diração à cidade grande.',
              imagemImpresso:1,
              imagemFonte:'cogna ia',
              textoDescritivoImagem:'',},
                
              {ordem:6,
              predecessor:5,
              texto:'Mas as cidades cresceram muito rápido e surgiram desafios, como trânsito intenso e aumento da violência.',
              urlAudioTexto:'',
              textoSimplificado:'',
              urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L4/L4_6.png',
              textoImpresso:1,
              textoImpressoRecriado:'',
              promptImagem:'gere uma imagem em estilo pintura à óleo de uma cidade grande que enfrenta problemas como a poluição e o trânsito pesado',
              imagemImpresso:1,
              imagemFonte:'cogna ia',
              textoDescritivoImagem:'',},
                
              {ordem:7,
              predecessor:6,
              texto:'Êxodo Urbano: das cidades para o campo. Por isso, depois dos anos 2000, mais pessoas começaram a sair das grandes cidades para o campo, em busca de uma vida mais tranquila ou porque estavam sem trabalho nas cidades.',
              urlAudioTexto:'',
              textoSimplificado:'',
              urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L4/L4_7.png',
              textoImpresso:1,
              textoImpressoRecriado:'',
              promptImagem:'gere uma imagem em estilo pintura a óleo de uma pequena família. Essa família parece ser bem moderna, e podem ser vistos de costas, olhando para uma casa no campo, prontos para morar lá. Ao lado da família, podem ser vistas algumas malas bem modernas, de rodinha',
              imagemImpresso:1,
              imagemFonte:'cogna ia',
              textoDescritivoImagem:'',},
                
              {ordem:8,
              predecessor:7,
              texto:'E vocês, gostam mais da cidade ou do campo?',
              urlAudioTexto:'',
              textoSimplificado:'',
              urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L4/L4_8.png',
              textoImpresso:1,
              textoImpressoRecriado:'',
              promptImagem:'gere uma imagem do tipo pintura a óleo que mostre de um lado a vida simples no campo e do outro, a vida moderna na cidade',
              imagemImpresso:1,
              imagemFonte:'cogna ia',
              textoDescritivoImagem:'',},
                
              {ordem:9,
              predecessor:8,
              texto:'Nosso próximo desafio vai explorar as vantagens e desvantagens da vida na cidade e no campo, com a ajuda de robôs!',
              urlAudioTexto:'',
              textoSimplificado:'',
              urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW3/L4/L4_92.png',
              textoImpresso:1,
              textoImpressoRecriado:'',
              promptImagem:'Gere uma imagem em estilo pintura à óleo que retrate as diferenças entre a vida no campo e a vida na cidade. A imagem deve mostrar um contraste claro entre a tranquilidade e a natureza do campo, com elementos como fazendas, animais e paisagens verdes, e a agitação e modernidade da cidade, com prédios altos, trânsito e luzes brilhantes. A pintura deve ser detalhada e capturar a essência de ambos os estilos de vida.',
              imagemImpresso:1,
              imagemFonte:'cogna ia',
              textoDescritivoImagem:'',},
              ]}},

            },
      
            /*
            glossarioBilingue:{  }
            */
          
            capaVerso:{
              urlImagemTerceiraCapa:'',
              textoTerceiraCapa:``,
          
              textoUltimaCapa: ``
              },
      }