let livro_cw6 ={

  /* metadados 2 */
  versao:'0.1.00',
  nomeFantasia: '',
  nomeTecnico:'CW6',
  resumo:'Módulo adequado para o Ensino Fundamental - Anos Finais, como sequência ao módulo CW5 ou CWX. Aborda novos recursos de programação e também redes de computadores e o funcionamento da internet, por meio de práticas divertidas de simulação da "entrega de mensagens digitais". Este módulo ainda prossegue abordando novos conceitos da ciência da computação relacionados à programação de computadores, eletrônica, internet das coisas e criatividade digital, desenvolvendo técnicas e habilidades do Pensamento Computacional para resolução de problemas, tais como decomposição, identificação de padrões, abstração, algoritmo e análise de dados.',
  resumoCapa: 'A música foi transformada pela computação. Softwares de edição e sintetizadores digitais facilitam a criação musical, e plataformas de streaming permitem acesso a vastas bibliotecas musicais.',
   nomeTecnicoEn: "CW6e",
  resumoEn: "Module suitable for Elementary School - Upper Grades, as a continuation of the CW5 or CWX module. It covers new programming resources as well as computer networks and the functioning of the internet through fun practices of simulating the 'delivery of digital messages.' This module also continues to address new computer science concepts related to computer programming, electronics, the Internet of Things, and digital creativity, developing Computational Thinking techniques and skills for problem-solving, such as decomposition, pattern recognition, abstraction, algorithms, and data analysis.",
  resumoCapaEn: "Music has been transformed by computing. Editing software and digital synthesizers facilitate music creation, and streaming platforms provide access to vast music libraries.", 
  
  isbn:'',
  autores:['Paulo Alvim, Miguel Mendonça de Goffredo'],
  editor:'Anderson Borges, Fernanda Oliveira',
  local:'',
  ano:'2025',
  url:'',
  capa:{
		urlImagemCapa:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/cw6_frente.png',
		urlImagemSegundaCapa:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/cw6_verso.png',
    urlImagemCapaEn:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/cw6e%20-%20frente.png',
		urlImagemSegundaCapaEn:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/cw6e%20-%20verso.png',},

  formularioRegistro:{
    titulo:'',
    urlImagem:'',
    campos:[{rotulo:'Login Somos:',formato:'usuarioAcessivel'},{rotulo:'Senha:',formato:'senhaAcessivel'}]},

  /*visaogeral:{
    titulo:'',
    descricao:'',
    licao1:{id:'',
    infografico:{titulo:'',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
      cenas:[				
        {ordem:1,
        predecessor:0,
        texto:'',
        urlAudioTexto:'',
        textoSimplificado:'',
        urlImagem:'',
        textoImpresso:0,
        textoImpressoRecriado:'',
        promptImagem:'',
        imagemImpresso:0,
        imagemFonte:'',
        textoDescritivoImagem:'',},
        ]}},
        },*/
      
  unidade1:{
    titulo:'',
    descricao:'',
    licao1:{id:'CW6AULA1',
    infografico:{titulo:'Lição 01. Introdução a Variáveis',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[				
      {ordem:1,
      predecessor:0,
      texto:'As variáveis estão em toda parte!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L1/L1_1.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo cinematic que retrate o conceito de variáveis em computação',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Elas aparecem no cabeçalho da sua prova, no placar de um jogo de videogame e até na tela do seu celular quando você recebe uma mensagem. São pedaços de informação que podem mudar o tempo todo.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L1/L1_2.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo cinematic de uma tela de computador onde está passando um jogo de aventura e que mostre um placar no canto superior direito com o número 100',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Na programação, podemos pensar nas variáveis como <b>caixas</b> que guardam diferentes valores.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L1/L1_3.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo cinematic de uma caixa de papelão aberta',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'O nome da variável é como uma etiqueta na caixa. O valor da variável é o que está dentro dela naquele momento.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L1/L1_4.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo cinematic de uma caixa de papelão aberta. Esta caixa está vazia e tem uma etiqueta em branco bem grande na frente',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Imagine que temos uma caixa chamada <b>idade</b> e dentro dela colocamos um papel com o número <b>12</b>. Nesse caso, o nome da variável é <b>idade</b> e seu valor é <b>12</b>.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L1/L1_5.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo cinematic de uma caixa de papelão aberta. Desta caixa está saindo o número 12 e tem uma etiqueta branca na caixa',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Mas as variáveis não guardam só números! Elas também podem armazenar palavras, imagens e até sons.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L1/L1_6.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo cinematic de uma caixa de papelão aberta. Desta caixa estão saindo ícones de fotos e notas musicais',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Se tivermos uma variável chamada <b>personagem</b> e dentro dela estiver a imagem do seu avatar favorito no jogo, então esse será o valor da variável. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L1/L1_7.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo cinematic de uma caixa de papelão aberta. Desta caixa está saindo um personagem de videogame e tem uma etiqueta branca na caixa',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Se tivermos uma variável chamada <b>nome</b> e dentro dela estiver escrito <b>Marcos</b>, então essa variável guarda um texto.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L1/L1_8.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo cinematic de uma caixa de papelão aberta. Desta caixa está saindo a palavra "MARCOS" e podemos ver, na frente da caixa, uma grande etiqueta branca, sem nenhum texto',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'No computador, o nome da variável indica onde seu valor está guardado na memória. Mas não precisamos nos preocupar com isso, pois as linguagens de programação fazem tudo funcionar de maneira simples.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L1/L1_9.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo cinematic de um close-up em um pente de memória do computador',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:10,
      predecessor:9,
      texto:'Os programadores usam variáveis para guardar informações, fazer contas e comparar valores, como a quantidade de moedas que um personagem tem ou quantas tentativas restam em um jogo.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L1/L1_10.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo cinematic de um adolescente asiático visto de costas, programando o computador',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:11,
      predecessor:10,
      texto:'Além dos jogos, as variáveis estão em muitos aplicativos que você usa no dia a dia.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L1/L1_11.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma 8imagem estilo cinematic de uma jovem mulher negra vista de costas, sentada ao computador, enquanto mexe no celular',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:12,
      predecessor:11,
      texto:'Por exemplo, quando você recebe uma mensagem no celular, o nome do contato e o conteúdo da mensagem são armazenados em variáveis.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L1/L1_12.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo cinematic de uma mão jovem segurando um smartphone que está recebendo uma mensagem de texto',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:13,
      predecessor:12,
      texto:'Sem variáveis, os programas não poderiam lembrar de nada! Elas são a memória dos computadores.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L1/L1_13.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo cinematic que retrate as variáveis agindo como a memória do computador',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
      ]}},
        
    licao2:{id:'CW6AULA2',
    infografico:{titulo:'Lição 02. Introdução a Formulários',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'Os dados são muito valiosos no mundo digital. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_1.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo isométrico que retrate o mundo digital e os dados',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Agora, você vai aprender a coletar informações criando formulários eletrônicos! ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_2.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo isométrico que retrate um formulário',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Os formulários são muito usados no dia a dia, como em cadastros, pesquisas e até em jogos. Eles possuem três elementos principais: campos de entrada, botões e mensagens de texto.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_3.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Campos de entrada permitem que os usuários digitem informações em diferentes formatos, como textos, números, datas e muito mais. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_4.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo isométrico de um computador com um formulário para a pessoa responder',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Para adicionar campos de entrada a um formulário, basta arrastar os blocos para a área de programação, organizá-los no layout e definir um rótulo para cada um.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_5.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Além dos campos simples, existem formatos específicos para facilitar a entrada de dados.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_6.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Listas de seleção: apresentam um conjunto de opções para o usuário escolher uma delas. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_7.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
      
      {ordem:8,
      predecessor:7,
      texto:'Botões de rádio: funcionam como as listas, mas são ideais quando há poucas opções, como "Masculino" e "Feminino".',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_8.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'Caixas de marcação: permitem escolher entre “Sim” e “Não” (marcado ou desmarcado). ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_9.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:10,
      predecessor:9,
      texto:'Campos de texto com várias linhas: usados quando o usuário precisa escrever algo mais longo, como observações. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_10.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:11,
      predecessor:10,
      texto:'Além dos campos de entrada, formulários também possuem botões e ícones clicáveis, que servem para executar ações, como salvar os dados preenchidos.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_11.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:12,
      predecessor:11,
      texto:'Para criar um botão no formulário, basta arrastar o bloco do botão, posicioná-lo no layout e definir o texto que aparecerá nele.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_12.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:13,
      predecessor:12,
      texto:'Outra parte importante dos formulários são as mensagens de retorno, que mostram informações para o usuário, como confirmações ou alertas. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_13.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'produção interna',
      textoDescritivoImagem:'',},
      
      {ordem:14,
      predecessor:13,
      texto:'Para adicionar uma mensagem de texto, basta arrastar o bloco, definir o texto inicial e posicioná-lo no formulário.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_14.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:15,
      predecessor:14,
      texto:'Esse texto pode ser alterado depois via programação, dependendo das ações do usuário.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_15.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:16,
      predecessor:15,
      texto:'Agora que conhece as possibilidades, veja como ficaria um formulário para cadastrar jogadores de futebol:',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_16.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:17,
      predecessor:16,
      texto:'Os formulários são a maneira mais comum de coletar dados, permitindo que programas organizem informações e tornem nossa vida mais fácil e produtiva! ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L2/L2_17.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem estilo isométrico que retrate um formulário',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},				
      ]}},
    
    licao3:{id:'CW6AULA3',
    infografico:{titulo:'Lição 03. Introdução à Internet das Coisas',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'Imagine que você está chegando em casa à noite. Assim que se aproxima da porta, uma luz acende sozinha. Isso acontece porque um sensor de presença detectou seu movimento e ativou a lâmpada automaticamente. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L3/L3_1.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista de uma porta. É noite e alguém se aproxima da porta, chegando em casa. Uma luz acima da porta se acende quando a pessoa chega',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Neste caso, a luz e o sensor estão conectados pelo mesmo circuito elétrico, funcionando juntos.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L3/L3_2.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista de um sensor de presença conectado a uma lâmpada que fica acima no teto de uma porta, por meio de um circuito elétrico',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Mas agora, imagine que qualquer objeto possa se conectar à internet e trocar informações com outros dispositivos, não importa a distância entre eles.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L3/L3_3.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista de uma sala com um ar condicionado e um echodot trocando informações por meio da wifi',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Isso é o que chamamos de Internet das Coisas (IdC) ou IoT (Internet of Things). Trata-se de uma rede de aparelhos inteligentes conectados à internet, que se comunicam entre si. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L3/L3_4.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista de uma smart tv e um echodot conectados à internet, representando a internet das coisas',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'E essas “coisas” podem ser qualquer objeto do dia a dia: <br/>&nbsp;&nbsp✔️ Eletrodomésticos, como geladeiras e máquinas de lavar. <br/>&nbsp;&nbsp✔️ Carros e relógios inteligentes.<br/>&nbsp;&nbsp✔️ Sensores em indústrias e até roupas e tênis conectados!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L3/L3_5.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista de um robô industrial de montagem de carros/gere uma imagem realista de um carro que se dirige sozinho/gere uma imagem realista de um smartwatch/gere uma imagem realista de uma geladeira smart',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'A Internet das Coisas permite que os aparelhos funcionem de forma mais inteligente, adaptando-se automaticamente às informações que recebem, mesmo que venham de longe.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L3/L3_6.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista de uma moça jovem operando a geladeira smart de uma casa por meio do telefone na cozinha de uma casa',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Por exemplo, aquele sensor de presença que detectou sua chegada à noite poderia fazer muito mais do que apenas acender uma lâmpada.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L3/L3_7.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista de uma porta. É noite e alguém se aproxima da porta, chegando em casa. Uma luz acima da porta se acende quando a pessoa chega',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Ele poderia: <br/>&nbsp;&nbsp✔️ Avisar seus familiares que você chegou em casa com segurança. <br/>&nbsp;&nbsp✔️ Ligar outras luzes internas automaticamente. <br/>&nbsp;&nbsp✔️ Programar o micro-ondas para esquentar seu lanche antes mesmo de você entrar.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L3/L3_8.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista de um microondas esquentando um lanche automaticamente',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'Mas a IdC não se limita a casas inteligentes. Ela também é usada em grandes espaços e até cidades!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L3/L3_9.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista da vista aérea de uma cidade',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:10,
      predecessor:9,
      texto:'Prédios comerciais como shoppings, rodoviárias e aeroportos podem economizar energia, ajustando o ar-condicionado automaticamente conforme a quantidade de pessoas no local.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L3/L3_10.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista de um shopping center',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:11,
      predecessor:10,
      texto:'Cidades inteligentes usam sensores para monitorar o tráfego, a qualidade do ar e os ruídos. Esses sensores enviam informações para as autoridades em tempo real, ajudando a melhorar os serviços públicos.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L3/L3_11.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista de um centro de informações de uma cidade inteligente',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:12,
      predecessor:11,
      texto:'Na indústria, a IdC permite automatizar processos, monitorar máquinas à distância e tornar a produção mais eficiente.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L3/L3_12.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista de um robô montador de carros',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
        
      {ordem:13,
      predecessor:12,
      texto:'Agora, vamos explorar juntos o potencial da Internet das Coisas, imaginando e simulando como esses dispositivos inteligentes funcionam no mundo real!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L3/L3_13.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem realista que retrate o conceito de internet das coisas',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},				
      ]}},

    licao4:{id:'CW6AULA4',
    infografico:{titulo:'Lição 04. Generalização de Algoritmos ',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'A generalização nos permite resolver não somente um problema, mas diversos problemas semelhantes com um só algoritmo. Isso nos permite criar programas de computador mais flexíveis, reutilizáveis e poderosos.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Vamos aprender sobre a generalização de algoritmos usando formas geométricas como exemplo.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Perceba como são os algoritmos específicos, capazes de desenhar um triângulo e um quadrado.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'O uso de variáveis nos permite “generalizar” essas soluções. Veja como os algoritmos agora são idênticos, apenas usando valores diferentes para as variáveis.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Se acrescentarmos mais um polígono, como um pentágono, notamos que a semelhança prossegue...',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'E podemos inclusive simplificar ainda mais nossa solução, se identificarmos a correlação entre os ängulos e número de lados. Veja:',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Finalmente, chegamos a uma solução mais generalizada, que é capaz de desenhar qualquer polígono, bastando que o usuário nos informa o número de lados!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Essa mesma técnica de generalização pode ser usada em qualquer algoritmo, sempre que identificamos semelhanças nos comandos e valores de dados que variam a cada caso.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'A generalização é uma técnica poderosa da programação. Fique atento às variáveis!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},				
      ]}},

    licao5:{id:'CW6AULA5',
    infografico:{titulo:'Lição 05. Dispensadora de Remédio',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'A administração correta de medicamentos é essencial para a saúde dos pacientes.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L5/L5_1.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem em estilo digital art de uma mãe dando um xarope para tosse para uma criança de aproximadamente 12 anos',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
      
      {ordem:2,
      predecessor:1,
      texto:'Muitas pessoas precisam tomar diversos remédios, cada um com sua dosagem específica e horários diferentes, algo que pode ser difícil de lembrar.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L5/L5_2.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem em estilo digital art de um adolescente com alguns remédios sobre a mesa, organizando-os',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
      
      {ordem:3,
      predecessor:2,
      texto:'Errar o medicamento ou a dosagem correta pode comprometer o sucesso do tratamento e prejudicar a saúde do paciente.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:4,
      predecessor:3,
      texto:'Um aparelho inovador que pode ajudar muito nesse desafio é uma Dispensadora de Remédios Automatizada.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L5/L5_4.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem em estilo digital art de um aparelho dispensador de remédios automatizado',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
      
      {ordem:5,
      predecessor:4,
      texto:'Esse aparelho poderia ser programado para liberar automaticamente a quantidade correta de medicamento nos dias e horários certos, evitando falhas no tratamento.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:6,
      predecessor:5,
      texto:'Agora, sua equipe tem o desafio de tornar esse projeto uma realidade: projetar e programar uma dispensadora de remédios que seja eficiente, precisa e confiável!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L5/L5_6.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem em estilo digital art de duas crianças de aproximadamente 12 anos. As duas crianças estão programando em um computador num ambiente de sala de aula',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},				
      ]}},

    licao6:{},

    licao7:{id:'CW6AULA7',
    infografico:{titulo:'Lição 07. Laços “Para”',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'Já aprendemos sobre o laço "repita", que é usado para repetir comandos um certo número de vezes.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L7/L7_1.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'O “laço para" vai além! Ele nos permite acompanhar cada repetição usando uma variável de controle.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Isso significa que podemos saber em qual repetição estamos, modificar o ponto de partida e até alterar o passo da contagem.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Vamos ver alguns algoritmos do dia a dia que mostram o poder do <b>laço para</b>.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Imagine que você está tirando cartas de um baralho virado para baixo, e quer descobrir a posição do Ás de Copas. Basta fazer a condicional dentro do laço e, quando achar o Ás de Copas, emitir o valor da variável de controle.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'É também possível usar passos negativos no “laço para”! Pense em uma contagem regressiva para o lançamento de um foguete: basta iniciar de 10, terminar em zero e definir um passo –1!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Com o <b>laço para</b>, podemos também dar passos diferentes de 1. Por exemplo, para exibir todos os números pares entre 2 e 20: ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Devido à sua flexibilidade, os <b>laços para</b> são usados com muita frequência em programação. Chegou a sua vez!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},				
      ]}},          
    
    },

  unidade2:{
    titulo:'',
    descricao:'',
    licao8:{id:'CW6AULA8',
    infografico:{titulo:'Lição 08. Funções',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'Funções são blocos de código que reúnem comandos para realizar uma tarefa específica e podem ser chamadas várias vezes em um programa.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L8/L8_1.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'produção interna',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Sem funções, seria preciso repetir a mesma sequência de comandos diversas vezes, tornando o programa maior e mais difícil de entender.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'O nome da função deve ser claro e significativo, indicando exatamente o que ela faz.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Uma vez criada, uma função pode ser executada apenas chamando seu nome, como se fosse um comando comum da linguagem.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L8/L8_4.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'produção interna',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Programadores experientes possuem muitas bibliotecas de funções. Ao enfrentar um novo problema, eles reutilizam funções já criadas anteriormente, acelerando o desenvolvimento de projetos complexos, como grandes videogames.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L8/L8_5.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'produção interna',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Exemplo do dia a dia: Imagine que você tem um restaurante e quer definir algoritmos para a equipe preparar diferentes “cafés da manhã”, cada um com nomes e opções variadas. Alguns incluem ovos fritos, outros suco de laranja, outros nem tanto.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Os algoritmos que ensinam o preparo dos itens dos diferentes cafés da manhã poderiam ser funções, como “fazer suco de laranja”, “fritar ovos” e “fazer pão com manteiga”. E o programa que organiza o preparo dos cafés, em si, chamaria essas funções.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L8/L8_7.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'produção interna',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Dessa forma, se surgir a necessidade de oferecer um novo tipo de “café da manhã”, como o “café da manhã da casa”, você apenas precisa chamar as funções já existentes e adicionar apenas as partes que forem diferentes! ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L8/L8_8.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'produção interna',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'Muito interessante, não? Funções são essenciais na programação, permitindo a criação de programas menores, mais organizados e fáceis de entender! ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},				
      ]}},
          
    licao9:{},
    
    licao10:{id:'CW6AULA10',
    infografico:{titulo:'Lição 10. Funções com Parâmetros ',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'Já aprendemos o uso básico de funções, sem utilizar parâmetros. As funções sem parâmetro executam seus comandos internos exatamente da mesma forma em todas as chamadas. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L10/L10_1.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'print',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Mas imagine que temos um programa com repetições de grupos de comandos muito parecidos, mas com pequenas variações em cada caso.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'As funções com parâmetros permitem criar funções que se adaptam a essas variações. Podemos criar uma função que receba um valor como “parâmetro” e use esse valor para executar seus comandos de forma ligeiramente diferente a cada chamada.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'O programa chama a função passando um valor, que pode ser diferente a cada vez. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Funções podem receber vários parâmetros e retornar um valor, tornando-se incrivelmente flexíveis e poderosas! ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Por exemplo, uma função de um sistema escolar pode receber a matrícula de um aluno e um ano letivo como parâmetros, e devolver a nota final do aluno no ano.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Ou uma função matemática pode calcular a área de diferentes formas geométricas.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Repare como a chamada de uma função com parâmetros e retorno se parece com outros comandos que você já utilizou. Na verdade, esses comandos “nativos” são funções já criadas pelos desenvolvedores da linguagem de programação. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'Você pode criar e salvar funções em sua biblioteca pessoal, tornando sua linguagem de programação mais poderosa e ampliando suas possibilidades.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:10,
      predecessor:9,
      texto:'As funções vão levar seus programas para outro nível de capacidade!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},				
      ]}},
  
    licao11:{},
  
    licao12:{id:'CW6AULA12',
    infografico:{titulo:'Lição 12. Batalha Naval Robotizada',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'O jogo Batalha Naval é um clássico que desafia a estratégia e a orientação espacial dos jogadores.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L12/L12_1.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem em estilo comic art do jogo de tabuleiro batalha naval',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
      
      {ordem:2,
      predecessor:1,
      texto:'Na versão tradicional, cada jogador posiciona navios, submarinos e hidroaviões em seu lado do tabuleiro, mantendo a localização secreta do adversário. Em seguida, ambos se revezam enviando coordenadas de ataque para tentar atingir a frota inimiga.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L12/L12_2.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem em estilo comic art de duas crianças, de aproximadamente 12 anos. Elas estão sentadas no chão, jogando batalha naval',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
      
      {ordem:3,
      predecessor:2,
      texto:'Quando erram, os atacantes recebem a mensagem "água" e perdem a vez. Quando acertam, recebem o aviso sobre qual embarcação foi atingida e podem tentar novamente.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L12/L12_3.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem em estilo comic art de um splash de água, como se uma pedra tivesse sido jogada',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
      
      {ordem:4,
      predecessor:3,
      texto:'Vence quem conseguir destruir primeiro toda a frota adversária.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L12/L12_4.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem em estilo comic art de um close-up de um barquinho de brinquedo afundando na água',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
      
      {ordem:5,
      predecessor:4,
      texto:'Neste projeto, seu desafio é criar e programar uma Batalha Naval Robotizada, uma versão moderna, "do século 21", que permite que quatro jogadores participem simultaneamente.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L12/L12_5.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L12/L12_5.png',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
      
      {ordem:6,
      predecessor:5,
      texto:'Cada jogador deverá programar seu robô para bombardear automaticamente a frota do adversário do quadrante ao lado, no sentido horário, enviando apenas as coordenadas desejadas por texto ou voz.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L12/L12_6.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem em estilo comic art do robô Sphero em close-up rolando pelo chão de uma sala de aula',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},
      
      {ordem:7,
      predecessor:6,
      texto:'Além disso, o placar da batalha precisa ser atualizado automaticamente após cada ataque! Preparados para essa batalha tecnológica?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'https://storage.googleapis.com/mindmakers/Computational%20World/CW6/L12/L12_7.png',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'gere uma imagem em estilo comic art de duas crianças de aproximadamente 12 anos programando um computador em um ambiente de sala de aula',
      imagemImpresso:1,
      imagemFonte:'cogna ia',
      textoDescritivoImagem:'',},				
      ]}},
  
    licao13:{},
  
    licao14:{},          
      
    },

  unidade3:{
    titulo:'',
    descricao:'',
    licao15:{},
          
    licao16:{},
      
    licao17:{},
  
    licao18:{id:'CW6AULA18',
    infografico:{titulo:'Lição 18. Tabelas, Registros e Metadados',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'Tabelas são estruturas que organizam dados em linhas e colunas, facilitando a visualização e o uso de muitas informações em bancos de dados.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Cada coluna de uma tabela representa um tipo de dado específico, que é preenchido nas várias linhas da tabela. E cada linha é chamada de registro. Um registro guarda todos os dados relacionados a um único item ou pessoa. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'Por exemplo, uma tabela de alunos de uma escola terá um registro para cada aluno, e cada registro pode conter o nome, a idade e a nota do aluno.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Em uma tabela, cada registro pode ter dados diferentes para cada aluno, mas cada coluna segue um tipo específico.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'Por exemplo, a coluna “nome” é do tipo “texto”, a coluna “idade” é do tipo “número inteiro” e a coluna “nota” é do tipo “número decimal”.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Esses dados que descrevem as colunas, como nome e tipo, são chamados de metadados. Eles definem o que pode ser armazenado em cada coluna, ajudando a entender a estrutura dos dados e impedindo que sejam gravados dados do tipo errado.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'Por exemplo, se os metadados definem que a coluna “idade” aceita apenas números inteiros, um programa não conseguirá salvar uma letra nessa coluna, evitando erros.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Nossa vida digital está repleta de tabelas em grandes bancos de dados, que armazenam as informações dos sites e aplicativos em tabelas com dezenas de colunas e, às vezes, milhões de registros.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:9,
      predecessor:8,
      texto:'Essas tabelas ficam guardadas nos servidores de internet – por isso, dizemos que elas fazem parte do “back-end”, ou seja, dos bastidores das aplicações.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:10,
      predecessor:9,
      texto:'Nesta lição, vamos revelar como funcionam os bastidores das tabelas de dados!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},				
      ]}},
  
    licao19:{id:'CW6AULA19',
    infografico:{titulo:'Lição 19. Inventário Escolar Inteligente',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'Imagine que você precisa organizar seu quarto, listando todos os brinquedos, livros e roupas que possui, e anotando detalhes importantes sobre eles. Essa lista organizada e detalhada é chamada de inventário.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:2,
      predecessor:1,
      texto:'Empresas fazem inventários com frequência, para saber exatamente quantos bens possuem, qual o estado de conservação desses bens e o seu valor atual.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:3,
      predecessor:2,
      texto:'Uma escola pode fazer um inventário das mesas, cadeiras, computadores, TVs e outros bens que possui, para controlar quais precisam ser trocados e até mesmo descobrir se algum desapareceu! Ter esse controle garante que nada importante fique esquecido.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:4,
      predecessor:3,
      texto:'Por isso, a escola EDUTEC decidiu criar um Inventário Escolar Inteligente! Sua equipe foi escolhida para resolver esse desafio, criando uma tabela de dados e um formulário eletrônico que vão organizar tudo facilmente no mundo digital.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:5,
      predecessor:4,
      texto:'Várias entrevistas já foram feitas com funcionários, professores e outros colaboradores da escola, para entender quais bens precisam ser registrados e quais informações são essenciais para guardar.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:6,
      predecessor:5,
      texto:'Agora é com vocês: analisem as entrevistas, descubram quais dados precisam ser cadastrados e criem um formulário agradável e simples de usar!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},				
      ]}},
  
    licao20:{},
  
    licao21:{id:'CW6AULA21',
    infografico:{titulo:'Lição 21. Compactação de Arquivos',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[	
      {ordem:1,
      predecessor:0,
      texto:'Os computadores usam arquivos digitais para armazenar diversos tipos de dados, como textos, imagens, sons, vídeos e muito mais.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:2,
      predecessor:1,
      texto:'Cada arquivo tem um formato específico, que indica como as informações estão organizadas e como podem ser usadas. Esses formatos são identificados por <b>sufixos</b> (como .docx, .txt, .bmp, .wav, .avi) e <b>ícones</b>, que podem variar dependendo se o computador usa Windows, Mac ou Linux.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:3,
      predecessor:2,
      texto:'A compactação de arquivos é uma técnica usada para reduzir o tamanho desses arquivos, facilitando tanto o seu armazenamento quanto sua transferência pela internet.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:4,
      predecessor:3,
      texto:'Quando compactamos um arquivo, removemos partes redundantes ou representamos os dados de maneira mais eficiente, seguindo duas técnicas principais:',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:5,
      predecessor:4,
      texto:'<b>Compactação sem perda:</b> essa técnica preserva todos os dados originais, permitindo que o arquivo seja restaurado exatamente como era. É comum em arquivos de texto e programas.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:6,
      predecessor:5,
      texto:'Um exemplo clássico é o formato <b>ZIP</b>, que agrupa vários arquivos em um único arquivo compactado sem perder nenhuma informação.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:7,
      predecessor:6,
      texto:'<b>Compactação com perda:</b> aqui, alguns dados são removidos para reduzir ainda mais o tamanho do arquivo, o que pode afetar um pouco a qualidade, mas geralmente de forma que o ouvido ou o olho humano nem percebe.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
        
      {ordem:8,
      predecessor:7,
      texto:'Esse tipo é muito usado em arquivos de áudio, vídeo e imagens, como nos formatos <b>MP3</b> para som, <b>JPEG</b> para imagens e <b>MP4</b> para vídeos. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:9,
      predecessor:8,
      texto:'Mas, por que compactar arquivos?  Compactar arquivos tem várias vantagens: <br/>&nbsp;&nbsp<b>Economia de espaço:</b> Ocupa menos espaço de armazenamento. <br/>&nbsp;&nbsp<b>Facilidade de envio:</b> Arquivos menores são mais rápidos para enviar por e-mail ou pela internet. <br/>&nbsp;&nbsp<b>Velocidade:</b> Acelera os processos de download e upload.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:10,
      predecessor:9,
      texto:'Compactar arquivos é uma habilidade útil que nos ajuda ser mais eficientes no mundo digital. Vamos compactar? ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},			
      ]}},          
      
    },
    
  unidade4:{
    titulo:'',
    descricao:'',
    licao22:{id:'CW6AULA22',
    infografico:{titulo:'Lição 22. Internet: Das Redes Locais à Rede Mundial',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'Quando você nasceu, a internet já existia.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:2,
      predecessor:1,
      texto:'Mas os primeiros computadores eram isolados e solitários. Dava para jogar um videogame, criar um texto ou um vídeo, mas tudo rodava localmente, restrito a uma mesma pessoa, no mesmo computador. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:3,
      predecessor:2,
      texto:'A história começou a mudar com a ideia de conectar computadores próximos, por meio de cabos que permitissem a troca de arquivos entre eles: surgiam as primeiras “redes” de computadores. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:4,
      predecessor:3,
      texto:'As primeiras redes eram chamadas de “redes locais”, porque as conexões estavam restritas a computadores próximos em um mesmo local, como uma escola, empresa ou casa. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:5,
      predecessor:4,
      texto:'Mas então surgiu a internet, uma <b>rede mundial</b> de computadores inventada em 1989 por Tim Berners-Lee, um cientista da computação inglês. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:6,
      predecessor:5,
      texto:'Através dela, computadores dispersos pelo mundo passaram a poder se comunicar, compartilhando dados e aplicações se baseando em um padrão chamado World Wide Web (www).',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:7,
      predecessor:6,
      texto:'Na internet, computadores maiores chamados de “servidores” contém arquivos ou aplicações que servem páginas de dados em um formato textual conhecido como HTML (Hyper-text markup language).',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:8,
      predecessor:7,
      texto:'As páginas HTML contêm dados e hiperlinks para outros servidores web e páginas dispersas pela internet, formando um grande emaranhado de conexões que inspirou o termo “web” (teia).',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:9,
      predecessor:8,
      texto:'Com o tempo, os programas conhecidos como “navegadores de internet”, ou browsers, foram ficando cada vez mais sofisticados, sendo capazes de apresentar o conteúdo HTML de modo rápido, elegante e contendo recursos multimídia como sons, imagens e os vídeos que assistimos hoje. ',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:10,
      predecessor:9,
      texto:'Mas, como qualquer tecnologia inovadora e revolucionária, a rede mundial de computadores também veio com seus riscos: golpes digitais, vírus de computador e notícias falsas foram se tornando mais frequentes...',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:11,
      predecessor:10,
      texto:'O que exige um preparo de nossa parte – conhecer a internet tecnicamente nos ajudará a navegar com mais consciência, segurança e pensamento crítico.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},				
      ]}},
          
    licao23:{id:'CW6AULA23',
    infografico:{titulo:'Lição 23. Tecnologias da Internet: DNS, IP e Roteadores ',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'Você já aprendeu que a internet é uma enorme rede de computadores conectados. Mas como cada computador consegue encontrar outro dentro dessa rede gigantesca?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:2,
      predecessor:1,
      texto:'Cada computador conectado à internet possui um número único chamado endereço <b>IP</b> (Internet Protocol). Pense no IP como um número de telefone, mas para computadores.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:3,
      predecessor:2,
      texto:'Um endereço IP pode parecer assim: 216.239.38.21. Porém, esses números são difíceis para nós decorarmos. Por isso, usamos nomes mais fáceis, como www.youtube.com ou www.google.com.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:4,
      predecessor:3,
      texto:'Para transformar esses nomes fáceis (chamados de <b>URLs</b>) em endereços IP numéricos, usamos um serviço especial chamado <b>DNS</b> (Domain Name System).',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:5,
      predecessor:4,
      texto:'O DNS funciona como o aplicativo de contatos no seu celular. Quando você quer ligar ou enviar mensagens para um amigo, não precisa decorar o número dele, basta buscar pelo nome.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:6,
      predecessor:5,
      texto:'Da mesma forma, quando você digita um endereço como www.youtube.com, o DNS encontra rapidamente o número IP certo para você acessar o site desejado.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:7,
      predecessor:6,
      texto:'Agora, como as informações chegam do seu computador até outro computador do outro lado do mundo? Para isso, usamos equipamentos chamados <b>roteadores</b>.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:8,
      predecessor:7,
      texto:'Roteadores são aparelhos que funcionam como carteiros da internet. Eles recebem as informações e as encaminham pelos melhores caminhos até chegarem ao destino correto.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:9,
      predecessor:8,
      texto:'Em casa, o roteador conecta seus dispositivos (celular, computador, videogame) à internet. Nas redes maiores, muitos roteadores trabalham juntos para encaminhar dados entre cidades, países e continentes.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:10,
      predecessor:9,
      texto:'Quando você envia uma mensagem ou acessa um site, esses dados viajam por vários roteadores até alcançarem o destino. Tudo isso acontece em frações de segundo!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:11,
      predecessor:10,
      texto:'Então, quando você digita uma URL no navegador, o DNS encontra o IP do site, e os roteadores levam sua solicitação até o computador correto, que envia a página de volta para você.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:12,
      predecessor:11,
      texto:'Agora que vocês já foram apresentados às tecnologias fundamentais da internet, chegou a hora de aprender, na prática, como os endereços IP, DNS e roteadores funcionam, usando um incrível simulador da Internet!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},				
      ]}},
      
    licao24:{id:'CW6AULA24',
    infografico:{titulo:'Lição 24. Websites Dinâmicos',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'Você provavelmente acessa websites, ou simplesmente "sites", todos os dias, seja para jogar, estudar ou assistir vídeos.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:2,
      predecessor:1,
      texto:'Alguns sites são chamados de estáticos porque exibem sempre o mesmo conteúdo para todos os visitantes. São como cartazes digitais: toda vez que alguém acessa, eles mostram as mesmas informações contidas em um arquivo de texto, como por exemplo o "index.html".',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:3,
      predecessor:2,
      texto:'Já outros sites são dinâmicos. Eles montam suas páginas quando alguém acessa, buscando informações atualizadas diretamente em tabelas de bancos de dados.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:4,
      predecessor:3,
      texto:'Os sites dinâmicos têm grandes vantagens. Uma delas é exibir informações atualizadas instantaneamente. Por exemplo, se um novo produto é cadastrado no banco de dados, ele já aparece automaticamente no site!',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:5,
      predecessor:4,
      texto:'Por outro lado, os sites estáticos precisam de técnicos que saibam editar arquivos HTML manualmente e depois liberá-los no servidor web. Esse processo é mais lento e sujeito a erros.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:6,
      predecessor:5,
      texto:'Sites de lojas online (chamados de e-commerce) são dinâmicos, pois os produtos são guardados numa tabela de dados. Ao adicionar ou remover produtos dessa tabela, o site passa a exibir essas alterações automaticamente, sem necessidade de editar arquivos ou páginas manualmente.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:7,
      predecessor:6,
      texto:'Neste projeto, sua equipe precisa criar um website dinâmico, que exiba automaticamente os produtos que deseja vender.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:8,
      predecessor:7,
      texto:'Vocês deverão conceber e criar uma tabela com os produtos escolhidos, e programar uma função para buscar esses produtos diretamente da tabela sempre que alguém acessar seu site. Preparados para começar?',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},				
      ]}},
  
    licao25:{},
  
    licao26:{},
  
    licao27:{id:'CW6AULA27',
    infografico:{titulo:'Lição 27. Obsolescência de Dispositivos Eletrônicos ',
    tituloSimplificado:'',
    estiloPadrao:'basicoPaisagem',
    video:'',
    cenas:[
      {ordem:1,
      predecessor:0,
      texto:'Obsolescência é o processo pelo qual dispositivos eletrônicos se tornam ultrapassados ou inutilizáveis ao longo do tempo.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:2,
      predecessor:1,
      texto:'O tempo útil de vida de um dispositivo eletrônico varia conforme o tipo de aparelho e a tecnologia utilizada.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:3,
      predecessor:2,
      texto:'Smartphones, por exemplo, geralmente têm um tempo útil médio entre 3 e 5 anos, enquanto computadores podem durar de 4 a 6 anos ou até mais, dependendo do uso e da manutenção.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:4,
      predecessor:3,
      texto:'A obsolescência pode ser causada por vários fatores, como avanços tecnológicos, desgaste físico e falta de suporte para atualizações de software.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:5,
      predecessor:4,
      texto:'Outro motivo válido para a troca de um dispositivo pode ser o custo-benefício da utilização energética dos aparelhos.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:6,
      predecessor:5,
      texto:'Dispositivos mais antigos tendem a consumir mais energia. Aparelhos novos em geral são projetados para um uso mais eficiente, podendo reduzir os custos de eletricidade e o impacto no meio ambiente.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:7,
      predecessor:6,
      texto:'Por outro lado, muitas pessoas trocam dispositivos eletrônicos, mesmo quando não há ganho significativo de eficiência energética, influenciadas por moda, detalhes estéticos ou pequenas melhorias não essenciais. Isso acontece mesmo quando o aparelho atual ainda atende plenamente ao seu propósito.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:8,
      predecessor:7,
      texto:'É essencial avaliar cuidadosamente se a substituição é realmente necessária, pois a troca excessiva gera impacto ambiental, tanto pelo aumento da produção quanto pelo descarte indevido.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:9,
      predecessor:8,
      texto:'Antes de descartar um dispositivo, verifique se ele pode ser atualizado ou reparado, prolongando sua vida útil e evitando esses impactos.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:10,
      predecessor:9,
      texto:'E se um aparelho eletrônico chegou mesmo ao fim da vida útil, a reciclagem é fundamental para minimizar o impacto ambiental, já que muitos componentes desses aparelhos podem ser reutilizados ou reciclados.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},
      
      {ordem:11,
      predecessor:10,
      texto:'Portanto, seja consciente! Antes de considerar uma troca, reflita sobre a real obsolescência do dispositivo eletrônico, compare sua eficiência energética e, se for mesmo preciso descartar, use reciclagem.',
      urlAudioTexto:'',
      textoSimplificado:'',
      urlImagem:'',
      textoImpresso:1,
      textoImpressoRecriado:'',
      promptImagem:'',
      imagemImpresso:1,
      imagemFonte:'',
      textoDescritivoImagem:'',},				
      ]}},
  
    licao28:{},          
      
    },
      
      /*
      glossarioBilingue:{  }
      */
    
      capaVerso:{
        urlImagemTerceiraCapa:'',
        textoTerceiraCapa:``,
    
        textoUltimaCapa: `A música foi transformada pela computação. Softwares de edição e sintetizadores digitais facilitam a criação musical, e plataformas de streaming permitem acesso a vastas bibliotecas musicais.`
        },
}